### ISSUE TITLE
secretflow/scql 镜像拉取异常

### ISSUE THREAD

**Issue by songsong124** [secretflow/scql#10]
![image](https://user-images.githubusercontent.com/56468127/228502020-67b726db-9c0f-4b20-bfda-d6d4c21250e4.png)
镜像源：https://registry.hub.docker.com
Docker pull  secretflow/scql 镜像 不能正常拉取。帮忙看下有什么问题

**Comment by anakinxc** [comment]
看起来是网络问题

**Comment by TY-cc** [comment]
@songsong124 贴主，能加个WX嘛，方便对SCQL的互相讨论学习。我的微信Cch_1015
感谢

**Comment by songsong124** [comment]
ok
