### ISSUE TITLE
多机部署后，无法查询数据

### ISSUE THREAD

**Issue by cs1317** [secretflow/scql#109]
我参考https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/getting_started/deployment#create-docker-compose-file
部署了两方的SCQLEngine以及SCDB，但在测试SCQL，使用scdbclient进行两方联合查询时，报错：
![image](https://github.com/secretflow/scql/assets/50541363/e61ee4e3-ea71-451d-a30c-07dc55101fd7)
容器里可以单独查询数据：
![image](https://github.com/secretflow/scql/assets/50541363/923cce76-a806-4086-b69e-2e366872fb92)
但使用scdbclient就无法执行查询:
![image](https://github.com/secretflow/scql/assets/50541363/b6a7cc9e-ffc0-48fa-87a4-7f12adfdb4d3)

**Comment by jingshi-ant** [comment]
从报错上看是SCQLEngine访问MySQL错误，辛苦check下SCQLEngine配置中的连接串相关配置是否正确，以及在该节点内能否访问到对应MySQL

**Comment by cs1317** [comment]
各个SCQLEngine启动的容器(engine-alice和engine-bob)里，是可以正常查询本节点的数据的

**Comment by jingshi-ant** [comment]
mysql监听的是localhost还是具体的ip呢，如果不涉及隐私的话，方便分享下SCQLEngine的具体配置吗？

**Comment by cs1317** [comment]
各个SCQLEngine监听的是localhost,alice 的gflags.conf:
--listen_port=8080
--datasource_router=embed
--enable_scdb_authorization=true
--engine_credential=credential_alice
--server_enable_ssl=false
--scdb_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=alice;user=root;password=cs940303;host=**localhost**;auto-reconnect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
这是我的SCQLEngine和SCDB配置
[config.zip](https://github.com/secretflow/scql/files/12093473/config.zip)

**Comment by jingshi-ant** [comment]
感觉可能是host的原因，建议尝试将配置中的host=localhost改为host=127.0.0.1

**Comment by jingshi-ant** [comment]
嗯，也辛苦确认下mysql的port是不是默认的3306.

**Comment by cs1317** [comment]
换成实际的ip也不行，容器里检查了mysql端口号是3306
![image](https://github.com/secretflow/scql/assets/50541363/af655e8f-dc7e-4861-9590-46b0df3ca23e)

**Comment by jingshi-ant** [comment]
> "connection_str":"

能否展示下在SCQLEngine的container内部访问mysql的过程？
因为文档里的mysql是个独立容器，从描述里看，您是每个SCQLEngine配置了本地的mysql？

**Comment by cs1317** [comment]
就是很正常的mysql -uroot -pcs940303，然后use alice;  然后select * from user_credit;
![image](https://github.com/secretflow/scql/assets/50541363/d1bb11d8-956d-4cb1-8ca6-eda3f88b169c)

**Comment by jingshi-ant** [comment]
确认下：对于SCQLEngine Alice来说，MySQL是个独立的容器，而不是和SCQLEngine在同一个容器中？（确认下我理解的对不对。。）
那host应该填具体的容器名：alice-mysql  bob-mysql

**Comment by cs1317** [comment]
确实是这个原因，问题得到解决

**Comment by cs1317** [comment]
> > "connection_str":"
> 
> 能否展示下在SCQLEngine的container内部访问mysql的过程？ 因为文档里的mysql是个独立容器，从描述里看，您是每个SCQLEngine配置了本地的mysql？

SCQLEngine能否直接配置本地的mysql，alice_init.sql这种形式限制了我们业务中使用scql

**Comment by jingshi-ant** [comment]
> > > "connection_str":"
> > 
> > 
> > 能否展示下在SCQLEngine的container内部访问mysql的过程？ 因为文档里的mysql是个独立容器，从描述里看，您是每个SCQLEngine配置了本地的mysql？
> 
> SCQLEngine能否直接配置本地的mysql，alice_init.sql这种形式限制了我们业务中使用scql

可以配置的，在SCQLEngine中填正确可访问的host、port即可。

**Comment by cs1317** [comment]
![image](https://github.com/secretflow/scql/assets/50541363/6a9d222d-0ce9-4ca7-a6b5-d849cd6977b7)
您的意思是：配置了正确可访问的host、port后，红框中的部分就可以去掉了？

**Comment by jingshi-ant** [comment]
是的，只要有可访问的mysql服务，这个就不需要了。
