### ISSUE TITLE
请问stdgrm的服务该怎么部署？

### ISSUE THREAD

**Issue by shenpeilin** [secretflow/scql#110]
我在https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/getting_started/deployment
中看到的事例是使用toygrm，但这种方式显然是没有办法用在生产环境中的。我看到还有另一种方式是stdgrm，这个似乎需要启动一个grm服务，但我没看到关于这个服务如何部署的文档。
虽然找到了https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/reference/grm
但这看起来是一个接口文档也不是部署文档。
所以请问grm服务的部署方式是什么呢？

**Comment by 6fj** [comment]
Hi @tongke6 你可以看一下吗，感谢！

**Comment by tongke6** [comment]
@shenpeilin 生产可用的 GRM 服务需要集成方根据 GRM 接口自己去实现的。SCDB 对接集成方的 GRM 服务的时候，把 scdb 的配置文件里的 grm.grm_mode 改成 stdgrm，grm.host 填成实现的 GRM 服务的地址。
