### ISSUE TITLE
在 SCQL 中实现单方算子 abs

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#112]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：在 SCQL 中实现单方算子 `abs`
- 技术方向：SCQL
- 任务难度：进阶🌟🌟

## 详细要求
在 SCQL 中实现单方算子`abs`，按照《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 代码规范：代码规范参考  https://github.com/secretflow/scql/blob/main/CONTRIBUTING.md 
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/scql 

## 能力要求
- 熟悉 SQL 语法
- 熟悉 Go 语言
- 熟悉 SCQL 代码结构

## 操作说明
- 请先查看《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 可参考 [SCQL 单方算子 cos 的实现](https://github.com/secretflow/scql/pull/108)

**Comment by cs1317** [comment]
# 添加测试用例
![image](https://github.com/secretflow/scql/assets/50541363/728721c8-ccf1-4111-8d0a-d82887918827)
![image](https://github.com/secretflow/scql/assets/50541363/a452acd9-33c2-4758-8b09-235c15e605ae)

**Comment by cs1317** [comment]
# 运行测试
go test ./pkg/planner/core/...
![image](https://github.com/secretflow/scql/assets/50541363/f8a32a4b-aa2b-456b-930a-2c450c6121e1)
可以复现 [新增单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)中的错误，且错误原因是abs算子未实现

**Comment by cs1317** [comment]
# 代码中实现abs算子
![image](https://github.com/secretflow/scql/assets/50541363/f39e0174-2415-42ec-9636-5b2fd970e3ca)
![image](https://github.com/secretflow/scql/assets/50541363/1b330f29-12e3-462f-8e13-020dd7ef5248)

**Comment by cs1317** [comment]
# 再次运行测试，测试通过
![image](https://github.com/secretflow/scql/assets/50541363/28a0956f-0a18-4276-b106-04cb549b1424)
