### ISSUE TITLE
在 SCQL 中实现单方算子 round

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#113]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：在 SCQL 中实现单方算子 `round`
- 技术方向：SCQL
- 任务难度：进阶🌟🌟

## 详细要求
在 SCQL 中实现单方算子`round`，按照《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 代码规范：代码规范参考  https://github.com/secretflow/scql/blob/main/CONTRIBUTING.md 
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/scql 

## 能力要求
- 熟悉 SQL 语法
- 熟悉 Go 语言
- 熟悉 SCQL 代码结构

## 操作说明
- 请先查看《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 可参考 [SCQL 单方算子 cos 的实现](https://github.com/secretflow/scql/pull/108)

**Comment by cs1317** [comment]
# 添加round测试用例
![img_v2_9d9bda4a-5383-4800-8f50-39939e3c3aal_MIDDLE](https://github.com/secretflow/scql/assets/50541363/9b8bddad-a253-45e0-b99e-a8bdeceefe7b)

**Comment by cs1317** [comment]
# 运行测试  go test ./pke/planner/core/...
![img_v2_597bf933-64fa-4cf9-b102-446c46d8f52l_MIDDLE](https://github.com/secretflow/scql/assets/50541363/c0e1d563-94f4-4c37-bbe2-547fa277aa9a)
报错：缺少round算子的相关实现

**Comment by cs1317** [comment]
# 在pkg/expression/expression_to_stmt.go中添加round算子
vim pkg/expression/expression_to_stmt.go
![img_v2_2d407cdf-374a-4756-8364-b3a1035cb1dl_MIDDLE](https://github.com/secretflow/scql/assets/50541363/5d5e5750-bd9e-429d-900c-866cd4f79c46)

**Comment by cs1317** [comment]
# 再次运行测试
![img_v2_2c5ac382-0113-47d7-9837-06fc53b55e5l_MIDDLE](https://github.com/secretflow/scql/assets/50541363/6eb8ae5c-5237-42d6-a7a0-1bd2215daa80)
