### ISSUE TITLE
在 SCQL 中实现单方算子 floor

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#115]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：在 SCQL 中实现单方算子 `floor`
- 技术方向：SCQL
- 任务难度：进阶🌟🌟

## 详细要求
在 SCQL 中实现单方算子`floor`，按照《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 代码规范：代码规范参考  https://github.com/secretflow/scql/blob/main/CONTRIBUTING.md 
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/scql 

## 能力要求
- 熟悉 SQL 语法
- 熟悉 Go 语言
- 熟悉 SCQL 代码结构

## 操作说明
- 请先查看《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 可参考 [SCQL 单方算子 cos 的实现](https://github.com/secretflow/scql/pull/108)

**Comment by cs1317** [comment]
cs1317 Give it to me

**Comment by cs1317** [comment]
# 下载scql源码
![img_v2_0f345a43-60a7-4f70-9d6e-be867ba747fl_MIDDLE](https://github.com/secretflow/scql/assets/50541363/169f9cc9-dc55-4317-bb7c-032bac449419)

**Comment by cs1317** [comment]
# 添加floor测试用例
![ejDqf6jR3a](https://github.com/secretflow/scql/assets/50541363/c7a858ab-5e07-4cdd-b903-01212618ae48)

**Comment by cs1317** [comment]
# 运行测试 go test ./pke/planner/core/...
![xlEEtvrUY3](https://github.com/secretflow/scql/assets/50541363/fe2ec7ed-4402-4c84-8d74-03ebb74a59ce)
报错：缺少floor算子的相关实现

**Comment by cs1317** [comment]
# 再次运行测试
![Ql2xYXdNEe](https://github.com/secretflow/scql/assets/50541363/df2950ae-2c4e-46c0-b156-67acde3b8010)
