### ISSUE TITLE
在 SCQL 中实现单方算子 instr

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#117]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：在 SCQL 中实现单方算子 `instr`
- 技术方向：SCQL
- 任务难度：进阶🌟🌟

## 详细要求
在 SCQL 中实现单方算子 `instr`，按照《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 代码规范：代码规范参考  https://github.com/secretflow/scql/blob/main/CONTRIBUTING.md 
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/scql 

## 能力要求
- 熟悉 SQL 语法
- 熟悉 Go 语言
- 熟悉 SCQL 代码结构

## 操作说明
- 请先查看《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 可参考 [SCQL 单方算子 cos 的实现](https://github.com/secretflow/scql/pull/108)

**Comment by cs1317** [comment]
cs1317 Give it to me

**Comment by cs1317** [comment]
# 下载scql源码
![img_v2_0f345a43-60a7-4f70-9d6e-be867ba747fl_MIDDLE](https://github.com/secretflow/scql/assets/50541363/169f9cc9-dc55-4317-bb7c-032bac449419)

**Comment by cs1317** [comment]
# 添加instr测试用例
vim pkg/planner/core/testdata/runsql_in.json
![image](https://github.com/secretflow/scql/assets/50541363/9d0fee8e-9aec-4c53-8dc1-30013148887c)

**Comment by cs1317** [comment]
# 运行测试 go test ./pkg/planner/core/...
![image](https://github.com/secretflow/scql/assets/50541363/09c55997-a588-4fab-bd69-0f80593b8aa7)
报错：缺少instr算子的相关实现

**Comment by cs1317** [comment]
# 在pkg/expression/expression_to_stmt.go中添加instr算子实现
 vim pkg/expression/expression_to_stmt.go
![image](https://github.com/secretflow/scql/assets/50541363/91de6375-ccf0-4f92-982a-6e8de58f3094)

**Comment by cs1317** [comment]
# 再次运行测试
![image](https://github.com/secretflow/scql/assets/50541363/a56b6468-4c03-4667-982a-54a2daa09984)
