### ISSUE TITLE
在 SCQL 中实现单方算子 length

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#118]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：在 SCQL 中实现单方算子 `length`
- 技术方向：SCQL
- 任务难度：进阶🌟🌟

## 详细要求
在 SCQL 中实现单方算子 `length`，按照《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 代码规范：代码规范参考  https://github.com/secretflow/scql/blob/main/CONTRIBUTING.md 
- 提交说明：关联该 issue 并提交代码至 https://github.com/secretflow/scql 

## 能力要求
- 熟悉 SQL 语法
- 熟悉 Go 语言
- 熟悉 SCQL 代码结构

## 操作说明
- 请先查看《[SCQL 单方算子贡献指南](https://www.yuque.com/secret-flow/admin/zhguqtvx200zheqg)》进行逐步贡献操作
- 可参考 [SCQL 单方算子 cos 的实现](https://github.com/secretflow/scql/pull/108)

**Comment by cs1317** [comment]
cs1317 Give it to me

**Comment by AgravicCastle** [comment]
AgravicCastle give it to me
