### ISSUE TITLE
关于MPC协议的选择对参与方数量的影响

### ISSUE THREAD

**Issue by WandQ** [secretflow/scql#119]
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  spu:
    protocol: SEMI2K
    field: FM64
    sigmoid_mode: SIGMOID_REAL

上述配置中的protocol支持ABY3，CHEETAH和SEMI2K，官方文档中建议使用经过充分测试的SEMI2K，但是貌似其三元组来自可信第三方，有一定安全隐患。官方推荐配置为什么选择SEMI2K呢？使用另外两个是否更安全？
CHEETAH和ABY3在SCQL项目中，对参与方数量会有限制吗？比如使用CHEETAH时，三方数据源情况下，能否计算，怎么确定计算方？使用ABY3时，两方数据源，怎么选定的计算方，四方时怎么选定的计算方？

**Comment by jingshi-ant** [comment]
1.推荐SEMI2K的原因：该协议适合2方、3方以及多方的联合分析，使用范围更广。
2.SEMI2K中triple三元组的安全性确实需要独立第三方保证，CHEETAH/ABY3则不需要；但考虑到当前的scql架构中scdb也需要独立第三方，因此从架构整体看，即使选用其他协议，整体的安全水位并没有提升。
3.CHEETAH只适用两方联合分析的场景；ABY3则是三方场景，参与方的数量根据query中table（数据源）的来源定，如果table来自两方，则是两方。；四方及更多场景当前因为实现上的限制，暂只支持SEMI2K，暂未针对ABY3协议去根据一定规则选择特定计算方。
补充：如果数据分析的场景固定且为三方场景，选择ABY3在性能上有一定收益，也可简化第三方triple的部署（具体性能收益和query及数据有关）
因为问题较多，可能有的没回答到位，辛苦补充~

**Comment by WandQ** [comment]
明白了，感谢解答。
