### ISSUE TITLE
PSI协议问题

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/scql#12]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 0.6.13b0

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
no
```

### Reproduction code to reproduce the issue.

```shell
scql 中的join 用到了PSI的技术，请问下这里面的PSI协议的输入是明文还是秘密份额,我注意到PSI协议应该是基于KKRT的，那输入应该是明文形式？如果执行MPC Protocol，各方需要将自己的秘密分给其他方吗
```

**Comment by tongke6** [comment]
对的，目前 SCQL 的 JOIN 是基于 PSI 实现的，用的是 ECDH-PSI 协议。一般而言，用户的 query 是先 join 两方表再做联合的分析。JOIN 之前，join 的 key 是单方 private 的，输入到 PSI 是明文形式。做完 JOIN 操作后，若有多方的计算，会通过 secret-sharing 的方式进入到密态。

**Comment by Repo-Zhuang** [comment]
谢谢您的回答。我还有一些问题：
1.scql的ECDH-PSI支持两方以上的求交吗？
2.那如果是基于ECDH的话，在百万量级的集合里，其性能怎么样，隐语有相应的优化吗？
3.如果输入到 PSI 是明文形式，那么执行完PSI后，谁将拥有执行完PSI后的交集结果，这个结果是明文存在的吗，如果是明文存在的话，这里会有隐私风险吗？
再次感谢您的回答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 下午4:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [secretflow/scql] PSI协议问题 (Issue #12)





 
对的，目前 SCQL 的 JOIN 是基于 PSI 实现的，用的是 ECDH-PSI 协议。一般而言，用户的 query 是先 join 两方表再做联合的分析。JOIN 之前，join 的 key 是单方 private 的，输入到 PSI 是明文形式。做完 JOIN 操作后，若有多方的计算，会通过 secret-sharing 的方式进入到密态。

**Comment by tongke6** [comment]
1. 多方的 JOIN 可以通过两两 JOIN 实现；
2. ECDH-PSI 的计算瓶颈主要在 CPU 上，如果 CPU 支持 AVX512 ifma 指令集，隐语 PSI 是可以利用它做加速的。百万数据量级的性能，请 @zhanglei486 帮忙回答下。
3.  JOIN 操作的结果是两边的表对齐，所以双方都会得到交集结果。JOIN 之后，JOIN 的双方只会得到JOIN key 交集结果的信息，不会拿到不在交集里的 JOIN key 的信息。

**Comment by Repo-Zhuang** [comment]
谢谢您的回答！最后一个问题就是为什么scql选择基于DH的PSI而不是基于OPRF的PSI，据我了解，基于OPRF(based on OT extension)的PSI在量级大时效率会好些，是出于通信代价的考虑吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [secretflow/scql] PSI协议问题 (Issue #12)





  
多方的 JOIN 可以通过两两 JOIN 实现；
 
ECDH-PSI 的计算瓶颈主要在 CPU 上，如果 CPU 支持 AVX512 ifma 指令集，隐语 PSI 是可以利用它做加速的。百万数据量级的性能，请 @zhanglei486 帮忙回答下。
 
JOIN 操作的结果是两边的表对齐，所以双方都会得到交集结果。JOIN 之后，JOIN 的双方只会得到JOIN key 交集结果的信息，不会拿到不在交集里的 JOIN key 的信息。

**Comment by Repo-Zhuang** [comment]
好的，感谢
