### ISSUE TITLE
CCL API

### ISSUE THREAD

**Issue by luckymlog** [secretflow/scql#13]
有设置CCL的API吗？

**Comment by tongke6** [comment]
你好，SCQL 提供同步和异步查询接口，详见：https://www.secretflow.org.cn/docs/scql/en/development/scql_api.html#

可以通过查询接口，以 GRANT 语句的形式进行 CCL 设置。

CCL 设置语法可参考：https://www.secretflow.org.cn/docs/scql/en/reference/scql_manual.html#grant-revoke-statement

**Comment by imwangyt** [comment]
using the scdb api to submit `grant` statement？
