### ISSUE TITLE
Multi-machine installation

### ISSUE THREAD

**Issue by songsong124** [secretflow/scql#14]
Hello! Is there any installation documentation for the deployment of SCQL on different machines？

**Comment by tongke6** [comment]
There is no documentation for this right now, we expect it to be available next week.

**Comment by songsong124** [comment]
Hello, it was proposed last week that the SQL multi-party deployment document would be provided this week. Up to now, hasn't the multi-party SQL document been provided? When will it be available

**Comment by tongke6** [comment]
@songsong124 thanks for your patient ~

You could read [deployment](https://github.com/secretflow/scql/blob/main/docs/getting_started/deployment.rst) to learn about multi-machine deployment.

**Comment by songsong124** [comment]
![image](https://user-images.githubusercontent.com/56468127/230851416-4500a680-a8aa-49a6-84c0-6eda84c1966c.png)多机器安装，安装SCDB 的docker 容器报错、因容器里没有/home/admin/configs/toy_grm.json 这个文件？导致容器启动失败么？

**Comment by tongke6** [comment]
@songsong124 从错误日志的信息看，是这个原因导致的。

请确认下，安装 scdb 的宿主机 scdb 目录里是有 `toy_grm.json` 文件，详见：https://github.com/secretflow/scql/blob/main/docs/getting_started/deployment.rst#25-start-scdb-service

**Comment by songsong124** [comment]
![image](https://user-images.githubusercontent.com/56468127/230854864-c4cf619d-5d56-4310-8f03-5b6bfbad0336.png)
 有 toy_grm.json 文件

**Comment by tongke6** [comment]
抱歉，是文档里有一个错误：https://github.com/secretflow/scql/blob/7be62dc807db85fb7b7045c4be7d90c8ca0dfa82/docs/getting_started/deployment.rst?plain=1#L299
内容应该是 `- ./toy_grm.json:/home/admin/configs/toy_grm.json` 

我一会儿提个 PR fix。

**Comment by songsong124** [comment]
收到，谢谢

**Comment by songsong124** [comment]
![image](https://user-images.githubusercontent.com/56468127/230873333-095f3bca-8bdf-46fc-a340-0ae4a1e6acab.png)
查询连接超时。这里可能是哪里配置有问题？

**Comment by songsong124** [comment]
![image](https://user-images.githubusercontent.com/56468127/230873717-c7814f4d-c1de-4116-ae62-638742f04cfc.png)
报错日志，如上图所示

**Comment by tongke6** [comment]
@songsong124 方便进一下 SCDB 的容器里，分别 ping 一下 Alice 和 Bob 的 SCQLEngine 吗，即 `192.168.118.207` 和 `192.168.118.208`

**Comment by songsong124** [comment]
![image](https://user-images.githubusercontent.com/56468127/230878616-96ff1940-63f9-406a-a7f8-3ade25f5925c.png)
貌似ping 不通

**Comment by tongke6** [comment]
那说明 scdb 到 alice 以及 bob 的 SCQLEngine 之间的网络不通。

在 SCDB 所在的宿主机上，可以 ping 通这两个地址吗？

**Comment by tongke6** [comment]
BTW，请问下 `192.168.118.207`、 `192.168.118.208`、  `192.168.118.209` 这三个 IP 是三台物理机的 IP 地址吗？网络拓扑结构是怎样的

**Comment by songsong124** [comment]
是 在同一网段下的虚拟机

**Comment by songsong124** [comment]
在虚拟机 下能正常ping 通 192.168.118.207、 192.168.118.208、 192.168.118.209，进入docker 不能ping通其他节点ip。只能ping通本机ip

**Comment by tongke6** [comment]
方便在虚拟机和docker容器里分别执行下 `ip route` 看下输出吗？

在 `192.168.118.209` 的虚拟机上，执行下 `traceroute 192.168.118.207` 看下输出（此操作可能需要安装 traceroute 软件）。

**Comment by songsong124** [comment]
我清空iptables 和docker ，重新启动 好像可以了。

**Comment by songsong124** [comment]
您好！Global Resource Manager  这个文档 https://github.com/secretflow/scql/blob/main/docs/getting_started/deployment.rst 对应的具体接口是什么呢，或者有更详细的说明吗？
![image](https://user-images.githubusercontent.com/56468127/231096031-3bb838a1-4e44-455f-8d3e-2b6a284b6b98.png)

**Comment by tongke6** [comment]
@songsong124 您是想使用 ToyGRM 作为 demo 验证吗？还是想自己实现 GRM 服务用于生产环境

**Comment by songsong124** [comment]
我想使用GRM 服务用于生产环境

**Comment by tongke6** [comment]
GRM 服务比较贴近具体的业务，涉及参与方的管理、数据表schema等元数据的管理，以及资源的权限验证等。

我们没有提供默认的 GRM 实现，只定义了一套 SCQL 与 GRM 服务交互的接口，接口详见：https://github.com/secretflow/scql/blob/main/docs/reference/grm.rst

SCQL 与 GRM 服务的关系，可参考文档：https://github.com/secretflow/scql/blob/main/docs/development/integrate_scql_system.rst

**Comment by songsong124** [comment]
好的，谢谢

**Comment by tongke6** [comment]
@TY-cc 请问是在一台机器上安装么？同一台机器上要注意端口冲突问题，换个不冲突的端口。

**Comment by TY-cc** [comment]
对于alice还有bob还有scdb服务分别设置了不同的端口，报了如下的错误
`err: Post "//127.21.0.1:8083/public/submit_and_get": unsupported protocol scheme ""`

**Comment by taochen-ant** [comment]
你好，这是client向scdb发送请求时报错的吗？如果是这样，你可以尝试一下host参数前加上http即
./scdbclient prompt --host=http://127.21.0.1:8083

**Comment by TY-cc** [comment]
可以了，搞定了。感谢，另外deployment教程很清晰。另外咨询下，多机器下，三方都需要安装scdbclient服务么？

**Comment by TY-cc** [comment]
> 你好，这是client向scdb发送请求时报错的吗？如果是这样，你可以尝试一下host参数前加上http即 ./scdbclient prompt --host=http://127.21.0.1:8083

下面这个错误是因为什么？
`err: Post "https://127.21.0.1:8083/public/submit_and_get": dial tcp 127.21.0.1:8083: connect: connection refused`

**Comment by tongke6** [comment]
> > 你好，这是client向scdb发送请求时报错的吗？如果是这样，你可以尝试一下host参数前加上http即 ./scdbclient prompt --host=http://127.21.0.1:8083
> 
> 下面这个错误是因为什么？ `err: Post "https://127.21.0.1:8083/public/submit_and_get": dial tcp 127.21.0.1:8083: connect: connection refused`

scdb server 运行状态是正常的吗？重试还存在这个问题吗？

**Comment by TY-cc** [comment]
是使用docker logs -f scdb-scdb-1查看scdb的状态么？报告如下
`2023-04-14 13:13:55.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:13:56.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:13:57.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:13:57.4141 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:11.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:14:11.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:14:11.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:11.4141 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:19.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:14:19.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:14:19.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:19.4141 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:27.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:14:27.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:14:27.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:27.4141 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:38.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:14:38.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:14:38.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:38.4141 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:43.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:14:43.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:14:43.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:43.4141 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.3:3306: connect: connection refused
2023-04-14 13:14:47.4141 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-14 13:14:47.4141 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-14 13:14:48.4141 INFO main.go:122 Starting to serve request with http...
`

重试也是存在这个问题

**Comment by tongke6** [comment]
@TY-cc I see, 这是 scdb 状态异常导致的。

SCDB 无法连接数据库 
> 04-14 13:14:43.4141 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97 [error] failed to initialize database, got error dial tcp 172.21.0.3:3306: connect: connection refused

请确保 scdb 可以正常访问 config.yml 里配置的数据库。

**Comment by taochen-ant** [comment]
> 可以了，搞定了。感谢，另外deployment教程很清晰。另外咨询下，多机器下，三方都需要安装scdbclient服务么？

scdbclient只是一个方便展示的工具，其本质是向scdb发送post请求，你也可以直接向scdb发送post请求，scdbclient的安装取决于你的需求

**Comment by taochen-ant** [comment]
> Starting

前面的报错，应该是mysql还没有启动好，scdb在不停访问mysql被拒绝导致的。最后的日志显示看起来scdb已经能正常工作了

**Comment by taochen-ant** [comment]
> > 你好，这是client向scdb发送请求时报错的吗？如果是这样，你可以尝试一下host参数前加上http即 ./scdbclient prompt --host=http://127.21.0.1:8083
> 
> 下面这个错误是因为什么？ `err: Post "https://127.21.0.1:8083/public/submit_and_get": dial tcp 127.21.0.1:8083: connect: connection refused`

麻烦https改成http再尝试一下，示例里是没有开启https,如果你想开启https可以参考https://www.secretflow.org.cn/docs/scql/en/development/scql_config_manual.html#config-for-tls

**Comment by tongke6** [comment]
> > Starting
> 
> 前面的报错，应该是mysql还没有启动好，scdb在不停访问mysql被拒绝导致的。最后的日志显示看起来scdb已经能正常工作了

是的，出现了 `Starting to serve request with http `  日志之后，就表明 scdb 状态正常了，此时，使用 scdbclient  连 scdb 应该是 OK 的

**Comment by TY-cc** [comment]
换成http也还是不行哟
`[submit and get]err: Post "http://127.21.0.1:8083/public/submit_and_get": dial tcp 127.21.0.1:8083: connect: connection refused
`
现在能执行的操作只有切换用户(在alice，bob，root之间切换)，其他指令都会出现上述错误

**Comment by TY-cc** [comment]
不能访问127.21.0.1:8083，我怀疑是ip有问题，不过我的scdb服务是基于docker构建的，docker构建后有个新增ip就是127.21.0.1。我先网上找找解决办法。感谢！辛苦了！

**Comment by TY-cc** [comment]
搞定了，需要使用 docker inspect xx(容器名字)找IP地址，在信息的最后部分有个IPAddress就是容器的IP，我的是172.21.0.2。修改成这个IP就好了，感谢！！！

**Comment by taochen-ant** [comment]
> > > 可以了，搞定了。感谢，另外deployment教程很清晰。另外咨询下，多机器下，三方都需要安装scdbclient服务么？
> > 
> > 
> > scdbclient只是一个方便展示的工具，其本质是向scdb发送post请求，你也可以直接向scdb发送post请求，scdbclient的安装取决于你的需求
> 
> 请问这个有指导教程么？对这方面不是很了解

你可以参考https://www.secretflow.org.cn/docs/scql/en/development/scql_api.html中的api, 使用curl等命令发送post请求，也可以参考client的相关代码https://github.com/secretflow/scql/blob/main/pkg/scdb/client/client.go#L101

**Comment by TY-cc** [comment]
非常感谢，您的具体例子明确告诉了详细用法，这样我可以模仿扩展其他API的用法，对我这个菜鸟来说帮了大忙，我现在就去试试。
感谢感谢！

**Comment by TY-cc** [comment]
> 简单来说就是 scdb启动后，会监听相应的地址，以quickstart为例，scdb的监听端口为localhost:8080， 此时你根据API向该端口发送指定信息，会收到相应的回复， 比如说你通过public/submit_and_get提交query ` curl -X POST http://localhost:8080/public/submit_and_get -H "Content-Type: application/json" -d '{ "user": { "user": { "account_system_type": "NATIVE_USER", "native_user": { "name": "root", "password": root" } }, "grm_token": "sometoken" }, "query": "show databases;", "biz_request_id": "1234" }'` 随后你会收到相应的回复 `{"status":{"code":0, "message":"", "details":[]}, "out_columns":[{"name":"Database", "shape":{"dim":[{"dim_value":"1"}, {"dim_value":"1"}]}, "elem_type":"STRING", "option":"VALUE", "annotation":null, "ss":{"ss":["demo"]}}], "scdb_session_id":"********", "affected_rows":"0"}`

您好，昨天按此提交了查询指令，但是收到回复错误码100，表示不可用的查询体。
检查了localhost：8080端口，该端口的是正常工作的
对查询语句中的 name, password 以及grm_token按照user.json中对应用户修改也不起作用
下面是详细报错
`{"status":{"code":100,"message":"invalid request body","details":[]},"scdb_session_id":""}`

**Comment by tyrone-yu** [comment]
> { "user": { "user": { "account_system_type": "NATIVE_USER", "native_user": { "name": "root", "password": root" } }, "grm_token": "sometoken" }, "query": "show databases;", "biz_request_id": "1234" }

@TY-cc json 格式不对 password 后面的 root 少了一个引号，导致 json 无法解析

**Comment by TY-cc** [comment]
> > { "user": { "user": { "account_system_type": "NATIVE_USER", "native_user": { "name": "root", "password": root" } }, "grm_token": "sometoken" }, "query": "show databases;", "biz_request_id": "1234" }
> 
> @TY-cc json 格式不对 password 后面的 root 少了一个引号，导致 json 无法解析

是的，问题解决了，眼睛真尖啊
感谢！

**Comment by songsong124** [comment]
您好，目前SCQL 目前支持查询哪些数据库呢？PGSQL、和ORACLE 支持吗？

**Comment by tongke6** [comment]
> 您好，目前SCQL 目前支持查询哪些数据库呢？PGSQL、和ORACLE 支持吗？

目前仅支持 MySQL 协议兼容的数据库，未来会考虑支持 PostgreSQL，csv 等数据源的接入支持。

请问，在您们的使用场景里有对数据库类型的倾向吗，方便给我们提供一些输入吗？

**Comment by songsong124** [comment]
oracle 、PostgreSQL、hive、csv 这些常见数据源

**Comment by tongke6** [comment]
@songsong124 您方便新建一个扩展数据源的 Feature Request 的 issue 吗？我们好用它来追踪这个需求~

**Comment by songsong124** [comment]
好的
