### ISSUE TITLE
官方文档快速开始部署后出错

### ISSUE THREAD

**Issue by mtl802** [secretflow/scql#147]
**Describe the bug**
执行到最后一步查询的时候出现错误

**To Reproduce**
按照官方文档一步步实现，输出基本一致

**Expected behavior**
查询结果出现

**Screenshots**
![image](https://github.com/secretflow/scql/assets/20579710/e44bdd85-60b8-42e1-a545-2c3ecccd24d0)

**Environments (please complete the following information):**
 - OS: CentOS7
 - SCQL Version：2023/09/12

**Additional context**

**Comment by jingshi-ant** [comment]
从报错上看是engine的配置文件异常（公钥不匹配）：examples/docker-compose/engine/alice/conf/authorized_profile.json
可能的原因： 使用sqltool生成create user alice语句的时候，使用的pem文件不是alice的。
建议：关注下scqltool的使用，新建目录，并git clone代码后重新run一下。

**Comment by mtl802** [comment]
我重新clone了一下代码，也重新运行了bash examples/docker-compose/setup.sh
examples/docker-compose/engine/alice/conf和bob的conf都多了ed25519key.pem文件，authorized_profile.json文件中也都有对方的公钥信息。运行查询后结果如下：
![image](https://github.com/secretflow/scql/assets/20579710/eb300429-d228-4b97-ac10-b7eb6449218e)

**Comment by jingshi-ant** [comment]
看报错还是公钥验证的问题，重新run的时候可能因为最开始的docker container没有被清理，导致遗留了过时的公钥信息。
重试的时候，可以使用如下指令清理对应的环境：
(cd examples/docker-compose && docker compose down)
另：可以登录mysql对应的container，看公钥信息来简单验证是否scdb存储的公钥信息（在mysql中）和engine alice/bob配置文件中的不匹配：
----------查看配置文件的公钥
cat examples/docker-compose/engine/*/conf/authorized_profile.json 
----------查看mysql的公钥
docker exec -it mysql-1 bash
mysql -u root -ptestpass
select * from mysql.user;

**Comment by Handikang** [comment]
@jingshi-ant  
![微信图片_20230915092514](https://github.com/secretflow/scql/assets/42713276/28db25bd-a761-4c36-976a-ae5668b5f6c0)创建用户的语句应该是在命令行生成的吧，为什么到最后还是报错
![image](https://github.com/secretflow/scql/assets/42713276/98eae93e-ca6d-42cd-8690-4e574df82bce)

我也进去你说的mysql容器中去了，但没有找到公钥在哪里，还有我也使用你给的命令清理环境了，也是不行

**Comment by jingshi-ant** [comment]
@Handikang 
1.创建用户的语句是命令行生成的，在scdbclient的交互界面中输入就可以创建用户了。
2.报错是SCQLEngine认为SCDB下发的任务中bob的公钥和本地配置的不匹配（或者不存在），从你说的mysql容器中没有找到公钥看，感觉是注册用户的信息没有正确写入到mysql。能贴一下mysql里的表信息吗：show databases;  并查看各个database的tables: show tables from xxx; 以及看看对应user表的内容。

**Comment by Handikang** [comment]
@jingshi-ant  
![image](https://github.com/secretflow/scql/assets/42713276/b991bc4a-8033-4f1f-83a7-b73f8dfc73b0)

显示数据库表，没有demo
![image](https://github.com/secretflow/scql/assets/42713276/7fc9b4e4-5a00-4263-af0c-3ebdb1c197af)

显示alice的表
![image](https://github.com/secretflow/scql/assets/42713276/fdfdb36c-f7c6-4bbc-9255-aefc3dd852d8)

**Comment by jingshi-ant** [comment]
信息应该在database scdb的users表中：
select * from scdb.users；
![image](https://github.com/secretflow/scql/assets/124752045/7cc0f24a-301e-4357-b472-8b37ff1a47c6)
关注下箭头指的user，和公钥信息，时候和执行创建用户的语句match。

**Comment by Handikang** [comment]
> 信息应该在database scdb的users表中： select * from scdb.users； ![image](https://user-images.githubusercontent.com/124752045/268157364-7cc0f24a-301e-4357-b472-8b37ff1a47c6.png) 关注下箭头指的user，和公钥信息，是否和执行创建用户的语句match。

![image](https://github.com/secretflow/scql/assets/42713276/8f76d72b-b108-484b-b2f3-7b13f89e9e0f)
目测是一样的，但是还是报错了

**Comment by Handikang** [comment]
@jingshi-ant  
![image](https://github.com/secretflow/scql/assets/42713276/ccbd732b-24d6-4fc7-ae73-60eafb67808d)

我对比了容器内的密钥和创建用户的密钥，详情看上面我在你下面的评论，但还是没能解决错误

**Comment by jingshi-ant** [comment]
> 看报错还是公钥验证的问题，重新run的时候可能因为最开始的docker container没有被清理，导致遗留了过时的公钥信息。 重试的时候，可以使用如下指令清理对应的环境： (cd examples/docker-compose && docker compose down) 另：可以登录mysql对应的container，看公钥信息来简单验证是否scdb存储的公钥信息（在mysql中）和engine alice/bob配置文件中的不匹配： ----------查看配置文件的公钥 cat examples/docker-compose/engine/*/conf/authorized_profile.json ----------查看mysql的公钥 docker exec -it mysql-1 bash mysql -u root -ptestpass select * from mysql.user;

看起来mysql里面的是正常的，配置文件里面的公钥信息能贴下看看吗
----------查看配置文件的公钥
cat examples/docker-compose/engine/*/conf/authorized_profile.json

**Comment by Handikang** [comment]
> > 看报错还是公钥验证的问题，重新run的时候可能因为最开始的docker container没有被清理，导致遗留了过时的公钥信息。重试的时候，可以使用如下指令清理对应的环境： （CD examples/docker-compose && docker compose down） 另：可以登录mysql对应的container，看公钥信息来简单验证是否scdb存储的公钥信息（在mysql中）和engine alice/bob配置文件中的不匹配： ----------查看配置文件的公钥 cat examples/docker-compose/engine/*/conf/authorized_profile.json ----------查看MySQL的公钥 docker exec -it mysql-1 bash mysql -u root -ptestpass select * from mysql.user;
> 
> 看起来mysql里面的是正常的，配置文件里面的公钥信息能贴下看看吗 ----------查看配置文件的公钥 cat examples/docker-compose/engine/*/conf/authorized_profile.json

@jingshi-ant 
![image](https://github.com/secretflow/scql/assets/42713276/0e370d85-ddf9-4c66-9eea-f3ede5a6353e)
看起来和创建用户的语句不一致

**Comment by Handikang** [comment]
@jingshi-ant 这是哪里出现了问题

**Comment by jingshi-ant** [comment]
> > > 看报错还是公钥验证的问题，重新run的时候可能因为最开始的docker container没有被清理，导致遗留了过时的公钥信息。重试的时候，可以使用如下指令清理对应的环境： （CD examples/docker-compose && docker compose down） 另：可以登录mysql对应的container，看公钥信息来简单验证是否scdb存储的公钥信息（在mysql中）和engine alice/bob配置文件中的不匹配： ----------查看配置文件的公钥 cat examples/docker-compose/engine/*/conf/authorized_profile.json ----------查看MySQL的公钥 docker exec -it mysql-1 bash mysql -u root -ptestpass select * from mysql.user;
> > 
> > 
> > 看起来mysql里面的是正常的，配置文件里面的公钥信息能贴下看看吗 ----------查看配置文件的公钥 cat examples/docker-compose/engine/*/conf/authorized_profile.json
> 
> @jingshi-ant ![image](https://user-images.githubusercontent.com/42713276/268198052-0e370d85-ddf9-4c66-9eea-f3ede5a6353e.png) 看起来和创建用户的语句不一致

可能原因：确实很诡异。。因为配置文件是setup.sh自动获取填写的。。不应该不一致。
解决方案：可以修改下这两个json中的公钥内容，保持和mysql里的一致，然后docker restart 下 engine alice、bob对应的container 使得配置重新加载生效。

**Comment by Handikang** [comment]
@jingshi-ant 
嗯嗯可以了，把这个换成mysql里的密钥总算是查出来了，感谢你
![image](https://github.com/secretflow/scql/assets/42713276/885be81c-2f88-4dd8-a842-20034eb6e827)
