### ISSUE TITLE
SCQL会集成在SecretFlow上吗？

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#148]
1.可以说SCQL就是隐语的联邦查询解决方案吗？
2.SCQL会有可视化的界面吗，还是以后会集成到SecretFlow上？
3.SCQL的api如何使用，如何使用这些开源能力？

**Comment by jingshi-ant** [comment]
1. SCQL可以说是隐语 针对 联合数据分析场景（BI，联邦查询）的解决方案。
2. SCQL本身没有可视化界面，只提供了scqlclient，但是通过api可以方便集成到对应平台上（隐语平台 or 业务方自己的平台）。
3. SCQL本身的定位，类似于隐私计算场景的MYSQL，目标也是给用户提供SQL查询的类似体感。 当前对外的api主要是用于配置项目、发起请求的接口，方便上层平台集成：https://github.com/secretflow/scql/blob/main/api/scdb_api.proto

**Comment by Handikang** [comment]
@jingshi-ant 这个scqlclient就是所谓的命令行工具吗

**Comment by Handikang** [comment]
@jingshi-ant 
![84ae353b77ac233fd77a7edf2738e69](https://github.com/secretflow/scql/assets/42713276/5c495105-ec88-46eb-8359-51909fd5dd48)
这个是scql目前已经开源的支持查询的最新情况吗，现在是只支持mysql,csv，postgres,这三个数据源的是吗，hive的支持在年底吗？

**Comment by jingshi-ant** [comment]
1.scdbclient是cli工具，命令行工具。
2.这个图不是开源的能力图哈，开源的现状可以参考文档：https://www.secretflow.org.cn/docs/scql/latest/en-US/reference/scql_status 。目前已经支持了mysql/csv/postgres，hive的话，我们计划提供数据源的接入api，和开源共建，具体年底能否ready待定。

**Comment by Handikang** [comment]
@jingshi-ant 
1.我想问一下在具体的查询流程中得到的查询结果最后是多个参与方一起发给SCDB了吗？
2.这个查询是一次性的吗，SCQL有提供查询出结果后需要参与方确认的机制吗？
3.要是部署的话，可以将SCQB部署到隐语上的中心节点吗？SCDB能感知到SCQL Engine的状态吗？
4.这些异步接口和同步接口的源代码也是在api/scdb_api.proto中吗？还是在其他文件里
![image](https://github.com/secretflow/scql/assets/42713276/d206c212-013b-416d-9184-26c3c3859715)

**Comment by jingshi-ant** [comment]
@Handikang
1. 查询结果一般会汇聚到某个参与方，然后这个参与方返回到scdb，scdb再返回给客户端。
2. 只要符合设置的CCL，查询可以执行多次。目前没有提供审批确认机制，但是日志会记录查询信息供后续审查
3. 隐语本身暂时没有对外提供部署中心节点的服务，一般是自行选择合适的可信方部署。另外近期我们会提供p2p模式（开发中），不需要依赖独立第三方
4. 同步异步接口都在。
