### ISSUE TITLE
GRM相关问题

### ISSUE THREAD

**Issue by DINOREXNB** [secretflow/scql#151]
- 按照部署文档在docker部署好scdb与engine后，想在自己搭建的网页端进行数据查询，按照“快速开始”，执行至`CREATE TABLE demo.ta (ID string, credit_rank int, income int, age int) REF_TABLE=alice.user_credit DB_TYPE='mysql';`
- 回复消息如下：
```
{
  status: {
    code: 102,
    message: `line 1 column 31 near "string, credit_rank int, income int, age int) REF_TABLE=alice.user_credit DB_TYPE='mysql';" `,
    details: []
  },
  out_columns: [],
  scdb_session_id: '',
  affected_rows: '0'
}
```
- 发送的请求如下：
```
{
  user: {
    user: {
      account_system_type: 'NATIVE_USER',
      native_user: { name: 'alice', password: 'some_password' }
    }
  },
  query: "CREATE TABLE demo.ta (ID string, credit_rank int, income int, age int) REF_TABLE=alice.user_credit DB_TYPE='mysql';",
  biz_request_id: '',
  db_name: 'scdb'
}
```
- 似乎是string类型处出现语法错误，改成varchar后回复显示`REF_TABLE=alice.user_credit DB_TYPE='mysql';`这一处有语法错误，仍然无法创建ta表
- 在官方的部署文档中我似乎没有看见关于SCDB与engine通信的配置信息，之前我印象中应该是有一个关于grm的文档，但是在之后的文档中似乎找不到了，请问在哪里能够查阅？

**Comment by jingshi-ant** [comment]
1. 我们重构后，已经不需要用户感知GRM了。
2. 建议走一遍 快速开始 的文档，预计10min+，可以熟悉下现在的整体流程。（注意更新对应的镜像）
3. 多机部署的文档还没有更新，需要按照 快速开始 里的流程，增加scdb/engine的配置文件才能work。

**Comment by DINOREXNB** [comment]
按照快速开始进行部署docker报错如下:
```
2023-09-21 19:24:00.9217 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-09-21 19:24:00.9217 FATAL main.go:88 Failed to create config from /home/admin/configs/config.yml: yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `{
    "...` into server.RuntimeCfg
```

**Comment by tongke6** [comment]
@DINOREXNB 请拉一下最新的镜像（如果本地有缓存，先清理一下），代码有更新，spu 的配置格式变了

**Comment by DINOREXNB** [comment]
更新镜像后配置问题得到解决
