### ISSUE TITLE
请教：新增的left join功能如何保证后续数据对齐的呢

### ISSUE THREAD

**Issue by 982945902** [secretflow/scql#155]
如果存在类似如下语句： select alice.a < bob.b from bob left join  alice on bob.id = alice.id
那么left join之后，假设alice.a 列存在null值，如果后续要对alice.a做share，再将share值与bob.b列做mpc 比较，那么这个过程中null如何参与op计算呢。

**Comment by tongke6** [comment]
当前 left join 的实现会产生 null，但是对 null 的处理还不支持，后续会完善这块的逻辑，尽请期待。

按照 null 的处理逻辑，null 与 非 null 值进行比较，结果也为 null。

后续支持 null 会按照如下的逻辑进行处理，有一个 bool 的标记，用来标记某个值是否为 null，这个标记也会随着值进入到密态，进行计算和传播。最终结果 publish 的时候，会先 open null 标记，看值是否有意义。
