### ISSUE TITLE
scql支持kuscia吗

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/scql#160]
什么时候能支持kuscia

**Comment by longshan-ant** [comment]
目前scql和kuscia的初步设计已经对齐，正在进行细节的设计和开发， 预计11中下旬可以开发完成，敬请关注

**Comment by daydayuphere** [comment]
目前scql不支持分布式的控制，实际场景不太能用，建议一起考虑 @longshan-ant 
https://github.com/secretflow/scql/issues/165

**Comment by tongke6** [comment]
Hi @daydayuphere 0.6.0 版本已支持在 kuscia 里运行 SCQL
