### ISSUE TITLE
SCQL API接口调用报错

### ISSUE THREAD

**Issue by sqh539** [secretflow/scql#161]
我调用 /public/submit_and_get 接口报错
{"status":{"code":101,"message":"user root authentication failed","details":[]},"out_columns":[],"scdb_session_id":"","affected_rows":"0","warnings":[]}

我的入参是这样的：
{
    "user": {
        "user": {
            "account_system_type": "NATIVE_USER",
            "native_user": { "name": "root", "password": "testpass" }
        }
    },
    "query": "show databases;",
    "biz_request_id": "123455",
    "db_name": "scdb"
}

**Comment by sqh539** [comment]
另外，我用客户端工具是可以连接并查询的
![image](https://github.com/secretflow/scql/assets/49509903/b650af4d-8d76-4916-9bc1-1a6e6645a2e9)

**Comment by sqh539** [comment]
这是postman调用：
![image](https://github.com/secretflow/scql/assets/49509903/3b067b64-dcdf-43d5-91ab-f897cf330000)

**Comment by jingshi-ant** [comment]
scdbclient暂时不支持--user --passwd的flags，用户名密码在对应的配置文件里，用里面的账密试试：cmd/scdbclient/users.json

**Comment by jingshi-ant** [comment]
scdbclient默认的用户名密码在对应的配置文件里，用里面的账密试试：cmd/scdbclient/users.json

**Comment by jingshi-ant** [comment]
另外补充问下：你们是修改了系统的默认密码吗？所以手动指定了root的账密

**Comment by sqh539** [comment]
> 另外补充问下：你们是修改了系统的默认密码吗？所以手动指定了root的账密

没改，用root账号测试了下，命令行用alice账号也是会报错:

**Comment by jingshi-ant** [comment]
可能是因为alice用户还没有创建？ 用户需要创建后才能提交任务，系统默认刚刚启动的时候只有root用户，root可以用于创建其它user。

另外，启动scdbclient的时候，无需指定userName、passwd，可以通过switch root; switch alice; 来使用配置文件cmd/scdbclient/users.json里记录的账密

**Comment by sqh539** [comment]
> 可能是因为alice用户还没有创建？ 用户需要创建后才能提交任务，系统默认刚刚启动的时候只有root用户，root可以用于创建其它user。
> 
> 另外，启动scdbclient的时候，无需指定userName、passwd，可以通过switch root; switch alice; 来使用配置文件cmd/scdbclient/users.json里记录的账密

用户按快速开始上的sql 创建了，不创建用户是没办法切换用户的。
现在最后一步的联合查询报错了，好像是alice和bob之间调用公钥不对。

**Comment by jingshi-ant** [comment]
有报错信息吗，如果是公钥不匹配，可以参考这里：https://github.com/secretflow/scql/issues/157#issuecomment-1766284708

**Comment by jingshi-ant** [comment]
> > 另外补充问下：你们是修改了系统的默认密码吗？所以手动指定了root的账密
> 
> 没改，用root账号测试了下，命令行用alice账号也是会报错: ![image](https://user-images.githubusercontent.com/49509903/275719379-c6657093-2896-446d-a28b-3bc093e4be05.png) 容器内日志是这样的： ![image](https://user-images.githubusercontent.com/49509903/275719791-36cc41d2-9b3a-405e-8a6f-bf96eb9a9c96.png) 2023-10-17 13:21:20.10171 ERROR privileges.go:70 get user privilege record fail: user alice, host % 2023-10-17 13:21:20.10171 ERROR submit_handler.go:90 |RequestID:|SessionID:|ActionName:SCDBQueryHandler@/public/submit_query|CostTime:949.054?s|Reason:InvalidRequest|ErrorMsg:user alice authentication failed|Request:user:{user:{account_system_type:NATIVE_USER native_user:{name:"alice"}}} query:"asdfsd"|ClientIP:192.168.0.163 2023-10-17 13:21:20.10171 INFO server.go:162 |GIN|status=200|method=POST|path=/public/submit_query|ip=192.168.0.163|latency=1.397226ms|

另外，这里的问题是怎么解决的呀~

**Comment by sqh539** [comment]
> 有报错信息吗，如果是公钥不匹配，可以参考这里：[#157 (comment)](https://github.com/secretflow/scql/issues/157#issuecomment-1766284708)

好的，谢谢

**Comment by sqh539** [comment]
> > > 另外补充问下：你们是修改了系统的默认密码吗？所以手动指定了root的账密
> > 
> > 
> > 没改，用root账号测试了下，命令行用alice账号也是会报错: ![image](https://user-images.githubusercontent.com/49509903/275719379-c6657093-2896-446d-a28b-3bc093e4be05.png) 容器内日志是这样的： ![image](https://user-images.githubusercontent.com/49509903/275719791-36cc41d2-9b3a-405e-8a6f-bf96eb9a9c96.png) 2023-10-17 13:21:20.10171 ERROR privileges.go:70 get user privilege record fail: user alice, host % 2023-10-17 13:21:20.10171 ERROR submit_handler.go:90 |RequestID:|SessionID:|ActionName:SCDBQueryHandler@/public/submit_query|CostTime:949.054?s|Reason:InvalidRequest|ErrorMsg:user alice authentication failed|Request:user:{user:{account_system_type:NATIVE_USER native_user:{name:"alice"}}} query:"asdfsd"|ClientIP:192.168.0.163 2023-10-17 13:21:20.10171 INFO server.go:162 |GIN|status=200|method=POST|path=/public/submit_query|ip=192.168.0.163|latency=1.397226ms|
> 
> 另外，这里的问题是怎么解决的呀~

没有解决，之前是单独部署

> > > 另外补充问下：你们是修改了系统的默认密码吗？所以手动指定了root的账密
> > 
> > 
> > 没改，用root账号测试了下，命令行用alice账号也是会报错: ![image](https://user-images.githubusercontent.com/49509903/275719379-c6657093-2896-446d-a28b-3bc093e4be05.png) 容器内日志是这样的： ![image](https://user-images.githubusercontent.com/49509903/275719791-36cc41d2-9b3a-405e-8a6f-bf96eb9a9c96.png) 2023-10-17 13:21:20.10171 ERROR privileges.go:70 get user privilege record fail: user alice, host % 2023-10-17 13:21:20.10171 ERROR submit_handler.go:90 |RequestID:|SessionID:|ActionName:SCDBQueryHandler@/public/submit_query|CostTime:949.054?s|Reason:InvalidRequest|ErrorMsg:user alice authentication failed|Request:user:{user:{account_system_type:NATIVE_USER native_user:{name:"alice"}}} query:"asdfsd"|ClientIP:192.168.0.163 2023-10-17 13:21:20.10171 INFO server.go:162 |GIN|status=200|method=POST|path=/public/submit_query|ip=192.168.0.163|latency=1.397226ms|
> 
> 另外，这里的问题是怎么解决的呀~

没解决，这个是我参考 https://github.com/secretflow/scql/issues/157#issuecomment-1761112786

**Comment by jingshi-ant** [comment]
重构去除grm后，多机部署的文档还没及时更新（之前的 部署 文档），需要参考单机的配置文件，对engine增加公私钥对应的额外配置才能拉起来。 ip配置没有特殊邀请。

**Comment by sqh539** [comment]
> 重构去除grm后，多机部署的文档还没及时更新（之前的 部署 文档），需要参考单机的配置文件，对engine增加公私钥对应的额外配置才能拉起来。 ip配置没有特殊邀请。

没能理解，如果我在多个物理机器上部署，scdb、alice-engine、bob-engine容器安装在三台机器上，scdb是如何跟两台engine通信的呢？是在创建用户时写ip端口吗？
是类似这样吗:alter user alice with ENDPOINT '__ALICE_ENGINE_IP__:__ALICE_PORT__' 
__ALICE_ENGINE_IP__ 是alice-engine的物理机ip，__ALICE_PORT__是容器部署时alice-engine暴漏的服务端口。

**Comment by jingshi-ant** [comment]
不好意思，有错字： ip配置没有特殊要求。
您理解是对的，通过alter可以指定不同参与方的engine的ip。

**Comment by sqh539** [comment]
> 不好意思，有错字： ip配置没有特殊要求。 您理解是对的，通过alter可以指定不同参与方的engine的ip。

好的，谢谢
