### ISSUE TITLE
关于CCL的一些问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#163]
1.我看在体验平台上面没有配置CCL的界面，这个是已经在查询之前配置过了吗，我换了一条查询语句，之后报错显示CCL未通过授权，所以在体验平台上是不能查询其他语句的对吗？
2.现在我们是基于docker-compose部署的scql,如果说把engine端的mysql服务独立出来之后（专门的一个mysql容器或者另一台服务器），我们在scdb上创建表的时候，语句需要修改吗，如何把engine中的表链接到scdb上，是相同的创建语句吗？
![image](https://github.com/secretflow/scql/assets/42713276/32098cad-1493-4fc8-860f-58238288a09f)
3.CCL有默认放开的选项吗，就是可以不配置CCL就能查到数据吗？
4.CCl授权完毕之后，如何取消授权？

**Comment by jingshi-ant** [comment]
1.体验平台不属本repo覆盖范围，相关问题辛苦咨询平台负责同学。
2.scdb不需要感知engine访问表的位置，只需要ref_table是engine能访问的真实表即可，因此创建语句不需要更改。 engine本身则通过gflags配置具体表的位置。
3.ccl没有默认放开选项，如果授权比较麻烦，建议使用 scdbclient source， 可以批量执行文件里的授权等命令。
4.revoke可以撤销对应权限， 参见ccl授权文档：https://www.secretflow.org.cn/docs/scql/latest/en-US/reference/lang/manual#grant-revoke-statement

**Comment by Handikang** [comment]
1.我之前是把example用docker-compose部署好了，现在想部署在三台服务器上，是不是参考官方文档的部署就可以了
![image](https://github.com/secretflow/scql/assets/42713276/d11c4f97-4929-4fe4-b6c4-0afa62c73ba9)
2.现在我有个问题就是说：部署到多台机器上，是需要分别在各自的机器上启动一个docker-compose的对吧，要是这样部署的话，scdb和engine的两个节点是如何通信的？下面的docker-compose配置文件中__ALICE_PORT__我该如何修改？
![image](https://github.com/secretflow/scql/assets/42713276/0ff00fea-c6ac-48f5-9119-2f1a02a5ac6b)
3.假如在一台服务器上利用docker容器作为伪节点，是否可以实现在多台服务器上部署的效果吗[可以部署成功吗？]

**Comment by jingshi-ant** [comment]
1. 部署 文档 目前还没有更新，只是针对 0.2.0b1的版本， 0.3.0b1往后的版本去除了grm，该文档无法work（缺乏配置文件无法拉起） 老版本按照部署文档可以部署到多机器上。 新版本建议参考 快速开始文档 里描述的流程补齐相关engine的配置文件。
2. 多机器engine互相通信，__ALICE_PORT_直接填写真实机器ip即可。
3. 快速开始里就是用doker容器作为伪节点模拟的多台机器通信

**Comment by Handikang** [comment]
1.之前我的部署方式在一个docker-compose下面，然后alice和bob和scdb都在一个mysql容器（服务）下面，现在我想让alice单独在一个mysql容器中，bob在另外一个mysql容器中，scdb不动，这样他们三个人就都有各自的mysql服务，这样的话是不是需要修改docker-compose.yml的内容和gflags的内容，再多添加两个mysql容器，如果这样可以实现的话，我该怎么做？
![image](https://github.com/secretflow/scql/assets/42713276/7c3eac64-54a9-4a02-85a7-a7267593e02d)
2.在scdb中创建的demo数据库存放在哪里，是一个虚拟的数据库吗？在将alice数据库的表拉过去scdb的过程中，REF-TABLE是不是只把alice数据库的表user_credit的字段拉过去了，数据是不是还是在alice的数据库中的？

**Comment by jingshi-ant** [comment]
1.可以多添加两个mysql，添加的内容和yml里面原有的mysql部分类似，就和里面有engine_alice/engine_bob一样。 另外，需要配置engine 的gflags，连接到新部署的mysql。
2.创建的demo数据库实际对应的是mysql的scdb.databases表里的一行记录，是虚拟的；scdb上创建的table的映射，只有schema信息，数据还是在zlice里。

**Comment by Handikang** [comment]
我想问一下我这样部署可以吗，就是我把alice和bob的数据库分开了，一个外部容器放了alice的数据库，另外一个外部容器放了bob的数据库![image](https://github.com/secretflow/scql/assets/42713276/6b64aeb0-4b4f-4419-a499-44efd69904f4)
下面是我的alice的gflags,bob与之类似，最下面那个图是我最后查询失败的报错，我感觉是数据库的连接问题导致的，但是为什么创建表的时候可以引用字段成功呢，帮忙解答一下
![image](https://github.com/secretflow/scql/assets/42713276/678a23fe-738c-4728-bc78-459af621eeb3)
![image](https://github.com/secretflow/scql/assets/42713276/9116f97c-e704-4980-8394-b62a36877287)

**Comment by Handikang** [comment]
![image](https://github.com/secretflow/scql/assets/42713276/9b82451d-a041-4aee-9942-f0dd43ae0a4b)
这个是报错的图

**Comment by Handikang** [comment]
@jingshi-ant

**Comment by jingshi-ant** [comment]
可以把mysql独立部署的。
1.在scdb中创建table，只是创建了一个映射，此时不会去连接mysql（scdb也没有信息去访问参与方的实际数据）
2.看报错是没正常建立mysql连接，辛苦在对应engine的环境里，看看mysql有没有在正常监听对应的ip+port。

**Comment by Handikang** [comment]
下面两张图片我的gflags配置项，和我的mysql容器的端口映射情况，我使用docker创建了一个network，他们都在一个网络里，但是最后查询还是没能成功，还是报上面的错误
![image](https://github.com/secretflow/scql/assets/42713276/0528f3b5-2871-46b2-ab27-d0e4c1a5fdc3)
![image](https://github.com/secretflow/scql/assets/42713276/4d415228-50f0-43d1-9bff-02c77f5cc0cc)

**Comment by Handikang** [comment]
@jingshi-ant 可以了，感谢你不厌其烦的回复，分离了数据库之后可以查询到了
![image](https://github.com/secretflow/scql/assets/42713276/c5b88c95-cd38-435b-bfa4-0e6a964686dd)

**Comment by jingshi-ant** [comment]
赞~ 是因为host的问题吗？
因为我们验证的环境可能没有覆盖到很多场景，因此也感谢你们配合提供信息分析问题~

**Comment by Handikang** [comment]
是的，gflags文件host里面放对应的容器名称就可以了，我试过ip那些都不行
![image](https://github.com/secretflow/scql/assets/42713276/0cca2f1b-923c-4d25-bbca-a50ed14b1dc2)

**Comment by Handikang** [comment]
使用docker模拟多台机器部署的情况出现了问题，网络拒绝，我使用了alter设置了engine的ip和端口号，这里面用的ip是容器的ip,端口号用的是engine容器中暴露给宿主机的端口号,想问一下这样能部署成功吗，是不是在docker中先自定义一个网络，然后再创建三个容器的时候就分配网络，固定ip,然后暴露端口，这样是不是才行。【第一张图片是我的目前的docker部署的情况，分为了三个容器，第二张图片是查询报错的信息，显示连接失败，应该是网络的问题】
![image](https://github.com/secretflow/scql/assets/42713276/792df7b4-cf3c-43c1-9f7a-602ea33aac3e)
![image](https://github.com/secretflow/scql/assets/42713276/28d1146f-0ed5-48d9-8c26-9eb91e021fb6)
@jingshi-ant

**Comment by jingshi-ant** [comment]
container之间能否访问，可以直接docker exec -it {container name} bash 进去之后尝试curl ip+host。 
docker部署的时候建议暴露全局端口，不然监听端口直接从docker project外无法访问。

**Comment by Handikang** [comment]
@jingshi-ant 我暴露了全局端口，然后使用了alter替换了ip和端口，现在是报错EOF,这是什么原因导致的，我是三方分开部署的
，依然使用的是docke容器的方法
![image](https://github.com/secretflow/scql/assets/42713276/ea7e9462-9792-4a21-a9ad-62e4078a8e32)
![image](https://github.com/secretflow/scql/assets/42713276/dad9eda0-e505-4538-a274-48c59b609337)

**Comment by jingshi-ant** [comment]
报错上看是scdb向engine发起RunExecutionPlan请求的时候就报错了。
EOF有可能是engine不可达或者服务挂了，可以登录engine看看服务是否正常，scdb/engine之间能否ping通，以及日志中是否有请求相关信息
