### ISSUE TITLE
scql连接数据库问题

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/scql#164]
我有一个数据库，要测试的数据都在这个库里，需要用scql engine连接这个库，scql engine默认都是用自带的mysql。
请问如何配置呢

**Comment by jingshi-ant** [comment]
可以修改engine的配置：gflags中，connection_str对应了数据源的连接信息，修改到实际的mysql即可。（可能需要修改host、user、passwd等信息）
补充：也辛苦知晓连接数据库的风险，测试环境不建议直接访问，建议手动导测试数据。
具体说明参考：https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/reference/engine-config#embed-router

**Comment by daydayuphere** [comment]
谢谢
