### ISSUE TITLE
SCDB统一控制的问题

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/scql#165]
在第三方部署scdb，统一控制入口这样的方式存在的问题：
1、通过switch alice和bob，两方的数据都暴露给第三方了。
2、ccl的控制在scdb，alice和bob失去了对自己数据的控制权。

建议：有scdb分布式的版本，给alice和bob分别控制自己数据的入口，不要统一入口。现实大多数场景中alice和bob是两个独立的组织，不存在可信第三方。

**Comment by tongke6** [comment]
@daydayuphere 
这里可能存在误解。
1. quickstart 中的示例，只是一方模拟所有参与方。真实场景中，不存在这个情形的。第三方不应该知道 alice 和 bob 的账户密码的，也不可能 switch alice 和 bob。
2. CCL 是存储在 SCDB 的 存储里。目前要求 SCDB 部署在可信第三方。


对于找不到可信第三方去部署 SCDB 的场景，我们目前正在开发 SCQL 的 p2p 架构方案，是一个很大的架构调整。敬请期待~

**Comment by daydayuphere** [comment]
> @daydayuphere 这里可能存在误解。
> 
> 1. quickstart 中的示例，只是一方模拟所有参与方。真实场景中，不存在这个情形的。第三方不应该知道 alice 和 bob 的账户密码的，也不可能 switch alice 和 bob。
> 2. CCL 是存储在 SCDB 的 存储里。目前要求 SCDB 部署在可信第三方。
> 
> 对于找不到可信第三方去部署 SCDB 的场景，我们目前正在开发 SCQL 的 p2p 架构方案，是一个很大的架构调整。敬请期待~

  对于您提到的1，我参考的是多机部署链接。https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/topics/deployment/how-to-deploy-a-cluster，这个链接里面配置用户是一个统一的配置文件，所有用户名和密码，仍然是一个超级用户创建所有用户。
如下所示：
创建一个名为 users.json 的 JSON 文件，内容如下：
{
  "alice": {
    "UserName": "alice",
    "Password": "some_password"
  },
  "bob": {
    "UserName": "bob",
    "Password": "another_password"
  },
  "root": {
    "UserName": "root",
    "Password": "root"
  }
}

在没有分布式scql的情况下，当前如何部署多机，并且安全的使用呢

**Comment by jingshi-ant** [comment]
部署文档中的users.json只是为了简化scdbclient使用，因此包含所有用户信息。
实际场景中， 参与方alice只能获取到root账密（root只用于创建用户，没有其它权限），然后创建自己的user alice。 在user.json中填入自己的密码。alice的scdbclient只能在root/alice之间切换
对于bob也一样，两者的密码是不会被对方知晓的。

**Comment by daydayuphere** [comment]
收到。

另，很期待p2p的SCQL，什么时间能有

**Comment by jingshi-ant** [comment]
预计年前会发版，顺利的话11月底就绪。
