### ISSUE TITLE
关于alice公钥的问题

### ISSUE THREAD

**Issue by sqh539** [secretflow/scql#166]
在部署使用的过程中，我发现 setup.sh 脚本生成的 ./engine/bob/conf/authorized_profile.json 中alice的公钥 
与 命令行 ./scqltool genCreateUserStmt --user alice --passwd some_password --party alice --pem engine/alice/conf/ed25519key.pem
生成的公钥并不一样，请说明一下这两个公钥不一样的原因，与用途。谢谢！

**Comment by jingshi-ant** [comment]
公钥就是使用私钥生成的，是否生成公钥的指令不同？可以直接运行脚本里的指令试试看结果:
openssl pkey -in "$SCRIPT_DIR/engine/alice/conf/ed25519key.pem" -pubout -outform DER | base64

公私钥的用途是为了自证身份：1.用户在创建的时候，需要使用私钥加签，scdb会用公钥验签确认身份。2.engine只和公钥对应的参与方交互数据。

**Comment by sqh539** [comment]
> 公钥就是使用私钥生成的，是否生成公钥的指令不同？可以直接运行脚本里的指令试试看结果: openssl pkey -in "$SCRIPT_DIR/engine/alice/conf/ed25519key.pem" -pubout -outform DER | base64
> 
> 公私钥的用途是为了自证身份：1.用户在创建的时候，需要使用私钥加签，scdb会用公钥验签确认身份。2.engine只和公钥对应的参与方交互数据。

希望您能详细解释一下，这三个公钥的作用：
引擎配置文件（conf/authorized_profile.json）中，合作方的公钥：
      "public_key": **"MCowBQYDK2VwAyEAiw33gvs+tUB6Q/f5m9kVOM9z3XTcohRZJYdDYKQGN3k="**
建表语句中：
    CREATE USER `alice` PARTY_CODE 'alice' IDENTIFIED BY 'some_password' WITH '2023-08-23T20:03:34.268353853+08:00' '/oWeDbslKFQaqM6aOumnQY56i6MQKNNz84v0nkdhniXS0eBNX/q3n4IYz2EkABgKD+nkIVFtBokQqx5fr29CBw==' **'MCowBQYDK2VwAyEAzvfiNl1c1TjcvaTQBAxpG93MzHRGwuUBrPI3qf5N2XQ='**
scdb库user表中：
    users.`eng_pubkey`：MCowBQYDK2VwAyEAfT59cUuvuTUYxN5iM1UXq6VG4V1toIe2mchOhD0eJmI=

**Comment by sqh539** [comment]
> 引擎配置文件（conf/authorized_profile.json）用于引擎之间互相识别，在执行任务，引擎会校验任务参与方的公钥是不是在这个文件里，以确认参与方引擎是安全的。 建立user语句中的pubkey，是为了自证身份，比如在创建alice的时候，alice 会 告诉scdb公钥，并使用私钥对 时间戳加签， 这样 scdb 通过pubkey去验签就可以确认是alice所属参与方自己（有公钥对应的私钥）在创建user。 scdb库表里的公钥也和user一一对应，是在创建user的时候保存到表里的。

也就是说在验签通过后，认为alice身份可信，会将alice创建语句的公钥一起保存到用户表里对吗？

**Comment by jingshi-ant** [comment]
对的
