### ISSUE TITLE
算法来源。

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/scql#168]
您好！请问一些关键算法如shuffle、sort分别在两方和三方下如何实现的有没有论文描述呢？

感谢帮助！

**Comment by jingshi-ant** [comment]
您好，暂时还没有整理相关论文等公开资料，短期建议结合文档、代码、scdb日志（搜digraph，使用webgraph工具可视化）来了解算法流程。

**Comment by zzx-QDU** [comment]
能否简单透露一下2PCshuffle和sort采用的算法？

**Comment by rivertalk** [comment]
感谢提问~

目前 Sort 是用的 BitonicSort，具体的实现在这里
https://github.com/secretflow/spu/blob/9f60e68ae73cfbcb401ec669e868a4e18b875a64/libspu/kernel/hal/sort.cc#L56

之后我们计划针对 2PC/3PC 场景基于RadixSort进行优化
https://eprint.iacr.org/2019/695.pdf

**Comment by zzx-QDU** [comment]
非常感谢！
