### ISSUE TITLE
SCQL 公私钥算法支持 RSA

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#169]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- **任务名称**：SCQL 公私钥算法支持 RSA
- **技术方向**：SCQL
- **任务难度**：进阶🌟🌟
- **任务期望时间**：4-5 周

## 详细要求
当前 create user 语句里面的公钥和签名算法只支持 ed25519 算法。请扩展支持 RSA 公私钥算法。

## 能力要求

- 了解基本 git 操作
- 熟悉 Go, shell 和 openssl 
- 对 SCQL 有一定的了解，上手体验过 SCQL，了解 SCQL 的代码结构
## 操作说明

- 增强 scqltool 工具，可以支持 RSA 私钥文件，生成对应的 create user 语句
- 修改 SCDB 代码，使之可以校验 RSA 签名
- 请添加相关测试

**Comment by kinoko-shelter** [comment]
kinoko-shelter Give it to me

**Comment by Candicepan** [comment]
> kinoko-shelter Give it to me

因该任务一直没有提交，超过任务要求的时间期限，故任务暂时进行回收操作。感谢您的支持～也欢迎下次有意愿时可以继续参与隐语社区的贡献～
该任务目前为可继续认领状态，欢迎社区小伙伴感兴趣的进行认领哈～

**Comment by Candicepan** [comment]
以内部实现，后期也将同步时间代码在此～
