### ISSUE TITLE
关于SCQL的一些问题

### ISSUE THREAD

**Issue by TY-cc** [secretflow/scql#17]
1、比较好奇你们对SCQL的定位是什么？单独作为多方分析的一个独立平台？还是将其作为供别人依赖与调用的算法库？
2、在[这里](https://www.secretflow.org.cn/docs/scql/en/index.html)这里看了官方手册，但是对于SCQL的使用还是存在较多疑问，汇总如下
(1)：如何正式启用SCQL功能？
对SCQL的quickstart进行了试运行，但是对于如何正式启用SCQL功能还是摸不着头脑。
(2)：我个人将quickstart中运行的demo看作为”某个虚拟环境下”的test，我好奇的是，在正式启用SCQL功能时，是否也需要进入到这样的虚拟环境中。
(3)：手册中SELECT Statement与[SCQL Operators Specification](https://www.secretflow.org.cn/docs/scql/en/reference/scql_operators_doc.html)部分可以给一些实际example么？

**Comment by taochen-ant** [comment]
1、SCQL目前的定位是一个多方分析的后端引擎，用户可以通过调用我们的API来实现多方计算。
2、demo中我们通过docker-compose启动了模拟了三台机器，主要是演示SCQL可以用来对多方数据进行联合分析。对于SCQL而言，我们并不限定部署方式，用户可以在镜像中运行，也可以直接编译得到 exe 文件在物理机上运行，取决于用户的实际需求，我们更加推荐在镜像中运行，因为隔离环境会更加稳定。
3、我们的 select 语法当前基本与 MySQL 兼容，区别部分在 [mysql_compatibility](https://www.secretflow.org.cn/docs/scql/en/reference/mysql_compatibility.html)文档中列出，后续算子丰富后，会逐步添加一下新的 select 语法示例，如果您后续对某些语法有疑问的，欢迎继续询问

**Comment by TY-cc** [comment]
感谢回答，虽然还不是很理解。。我再去学习学习文档

**Comment by TY-cc** [comment]
看了SCQL文档，也对Quickstart进行了测试。对于SCQL的使用还是一头雾水。另外个人感觉SCQL的手册，关于SCQL的使用过程的教程也不是很清晰。
从准备开启一个多方分析任务为起始点，到获得结果为终点，就我个人来说，我希望demo包含以下过程(或者说内容)的教程
初始状态：存在三方A，B，C，各自持有数据数据库DB_A，DB_B，DB_C，SCQL源码在各自本地已经编译成功。
1：账号(用户)注册、登录问题
A，B，C如何注册自身账号，设置自身账号密码，并登录账号
2：数据库链接问题
对数据库方来说，在将账号注册成功后，A，B，C三方如何使得本地SCQL链接自身数据库
3：多方分析任务的编写执行问题
对结果请求方来说，在哪个模块下编写任务，是否需要在特殊环境下编写，如果是，怎么进入到该特殊环境。还是编写到一个某个文件下，那么该文件如何执行？
4：结果导出问题
对结果请求方来说，结果导出到了哪里？对请求方来说，结果输出位置与形式是如何控制的

**Comment by tongke6** [comment]
@TY-cc 感谢您对文档的反馈和建议。

初始状态下，需要提前部署好 SCQL 系统。我继续您的假设，有 A, B, C 三个数据参与方，它们域内已经部署好了 SCQLEngine 节点。SCDB 部署在可信第三方。
1. 账号注册的问题。SCDB 内置了一个 root 账户，即 admin 用户，它可以用来注册账号，使用 create user statement 来创建。
2. 问题2属于数据源接入 SCQL 系统。需要在 SCQLEngine 的配置文件或环境变量里配置相应数据库的链接串，配置详见：https://github.com/secretflow/scql/blob/main/docs/development/scql_config_manual.rst#config-for-datasource。同时，需要将表的 schema 信息注册到 GRM 里。
3. 可通过 SCQL 的 HTTP API 接口提交多方分析任务，使用 SQL 描述。
4. 对于`SELECT` statement，结果会通过 HTTP 接口返回。用户也可以通过 `SELECT ... INTO OUTFILE ...` statement 将结果写到指定参与方的 SCQLEngine 引擎侧。

**Comment by TY-cc** [comment]
好的，感谢。这两天会按照您说的操作试验一下，如果有问题再向您请教
再次感谢！

**Comment by TY-cc** [comment]
额，很不好意思，又是我，我又产生了一些问题，麻烦了。
我按照该[deployment](https://github.com/secretflow/scql/blob/main/docs/getting_started/deployment.rst)模拟布置了多机器节点。按照其描述，严格上需要安装的只有SCDBengine(我理解负责执行功能)以及SCDB(我理解该部分负责语句分析功能)，而SCDBclient可有可无。
关于该[deployment](https://github.com/secretflow/scql/blob/main/docs/getting_started/deployment.rst)我产生了一些问题
1、按照安装过程的描述，SCDB与SCDBengine的安装，并不依赖SCQL的源码。好像只有SCEBclient的安装需要源码支持，如果是这样的话，SCDB是如何具备语句分析功能的？(我觉得SCDB与SCDBengine应该也都是依赖于源码的，但是在deployment过程中未发现其依赖性)
2、SCDB在deploy中依赖user.json文件创建root用户与普通用户，我的疑问是，在一般场景中，SCDB功能应该会有某个SCDBengine方合并(因为个人觉得实际场景中很少依赖可信第三方)，那么在SCDB与SCDBengine合并的情况下，账号的创建会依赖于一方，他掌握着所有账户及其密码，这不会造成安全隐患么？

关于SCQL的使用问题
您说SCDB内置了一个root用户，使用怎样的指令进入该root用户呢？另外我在SCDBclient下的root账户下，尝试使用create创建普通账户(使用指令create user statement)，报错`err: Code: 300, message:no password for user statement`

**Comment by tongke6** [comment]
1. SCDB 和 SCQLEngine 都是从 scql 源码构建出来的，在部署过程中没有感觉到从源码构建是因为使用了我们提前打包好的 docker image。SCDBClient 也在 `secretflow/scql` 镜像里里(路径为 `/home/admin/bin/scdbclient` )，用户使用的时候也可以无需从源码构建。
2. 确认一下，问题 2 是问 scdbclient 的 user.json 文件吗？如果是两方 Alice 和 Bob，且 Bob 接受 SCDB 部署在 Alice 这一方。Alice 和 Bob 的账号创建可以委托给 root 账户来做。root 账号可以分别给到 Alice 和 Bob，也可以在 SCDB 上封一个业务平台，由业务平台持有 root 账号。Alice 和 Bob 自己的账密不应该被另一方知晓，需要保密。

关于 SCQL 使用问题，看报错是没有在 create user statement 里指定密码吗？

**Comment by TY-cc** [comment]
感谢回答
关于问题2，是指的scdbclient的user.json。大概懂了，就是说如果SCDB与Alice合并时，root账号可以与Bob共享，分别利用root账号权限构建自己的账户。是这样么？

按照其报错提示是说没有指定密码，所以我尝试在指令"create user statement"进行修改从而达到添加密码的目的。例如
```
create user statement somesome 
create user statement "somesome"
create user statement password somesome
create user statement password "somesome"
```
等等，都报错提示类似如下：
`err: Code: 102, message:line 1 column 39 near "somesome"`

**Comment by tongke6** [comment]
对的
> 关于问题2，是指的scdbclient的user.json。大概懂了，就是说如果SCDB与Alice合并时，root账号可以与Bob共享，分别利用root账号权限构建自己的账户。是这样么？

create user statement 的语法见：https://www.secretflow.org.cn/docs/scql/en/reference/scql_manual.html#create-drop-user-statement，请仔细阅读文档哦

**Comment by TY-cc** [comment]
您说的链接里create的用法我尝试过，还是需要首先在user.json里写好账户与密码的信息才可以创建吧？所以是不能即时创建么？

**Comment by TY-cc** [comment]
哦哦哦，知道了。感谢感谢
