### ISSUE TITLE
一个字段不能有多个CCL导致场景受限以及目前业务方希望做自动授权，SCQL这边是否有提供对应的API

### ISSUE THREAD

**Issue by YuChangF** [secretflow/scql#184]
1. 一个字段不能有多个CCL规则的目的是？目前这个SQL提交会失败，这个SQL里面age需要过滤，以及过滤完后分组
SELECT 
       chongqing.age,
       chongqing.target,
       shanghai.thal,
       COUNT(DISTINCT chongqing.id) as total_records,
       SUM(CASE WHEN shanghai.trestbps <= 140 THEN 1 ELSE 0 END) as trestbps_140_or_less,
       SUM(CASE WHEN shanghai.trestbps > 140 THEN 1 ELSE 0 END) as trestbps_greater_than_140,
       SUM(CASE WHEN chongqing.cpt IN (0,1) THEN 1 ELSE 0 END) as cpt_in_01,
       SUM(CASE WHEN chongqing.cpt NOT IN (0,1) THEN 1 ELSE 0 END) as cpt_not_in_01,
       SUM(shanghai.exang) as ex_angina
   FROM feddb.heart_chongqing chongqing
   JOIN feddb.heart_shanghai shanghai
   ON chongqing.id = shanghai.id
   WHERE shanghai.thalach > 150 AND chongqing.age DIV 10 >= 2
   GROUP BY chongqing.age,chongqing.target,shanghai.thal;
两张表元数据如下：
heart_shanghai    id,trestbps,chol,fbs,restecg,thalach,oldpeak,exang,slope,ca,thal
heart_chongqing    id,age,sex,cpt,target
错误信息如下：
 joinNode.buildCCL: failed to check condition (eq(feddb.heart_chongqing.id, feddb.heart_shanghai.id)) left party(2) ccl(UNKNOWN)

2. 以及目前业务方觉得授权麻烦，想做自动授权。SCQL能否根据提供API，根据提交的SQL来解析出CCL，然后由业务系统自动授权

**Comment by YuChangF** [comment]
目前我看了下，这个貌似是可以解析出CCL的，但是还没试过，is这个元数据参数还在看怎么构造	
// Parsing
	p := parser.New()
	ast, err := p.ParseOneStmt(stmt, "", "")
	if err != nil {
		return nil, err
	}

	// Planning
	sctx := sessionctx.NewContext()
	sctx.GetSessionVars().StmtCtx = &stmtctx.StatementContext{}
	sctx.GetSessionVars().PlanID = 0
	sctx.GetSessionVars().PlanColumnID = 0
	sctx.GetSessionVars().CurrentDB = db

	builder := core.NewPlanBuilder(sctx, is)
	plan, err := builder.Build(context.Background(), ast)
	if err != nil {
		return nil, err
	}
	builder.GetVisitInfo()

**Comment by jingshi-ant** [comment]
1.一个字段目前的实现是只支持配置一个ccl。报错看应该是id列没有配置PLAINTEXT_AFTER_JOIN，为什么是age配置多个ccl呢，这里能否辛苦补充下细节？
2.目前还没有相关工具来解析需要的ccl，建议：自动授权安全性不高，是否可以考虑只对需要保护的字段进行ccl限制，其它低敏感的字段设置为PLAINTEXT

**Comment by YuChangF** [comment]
> 1.一个字段目前的实现是只支持配置一个ccl。报错看应该是id列没有配置PLAINTEXT_AFTER_JOIN，为什么是age配置多个ccl呢，这里能否辛苦补充下细节？ 2.目前还没有相关工具来解析需要的ccl，建议：自动授权安全性不高，是否可以考虑只对需要保护的字段进行ccl限制，其它低敏感的字段设置为PLAINTEXT

1. 这个是授权的SQL：grant select PLAINTEXT_AFTER_GROUP_BY(target), select PLAINTEXT_AFTER_GROUP_BY(sex), select PLAINTEXT_AFTER_JOIN(id), select PLAINTEXT_AFTER_AGGREGATE(cpt), select PLAINTEXT_AFTER_GROUP_BY(age) on feddb.heart_chongqing TO 2;
这个是授权完后SCQL数据库的权限数据
![20231206-095324](https://github.com/secretflow/scql/assets/14515385/97dfbef4-3340-4b33-9eba-8ce346e7e3cf)
id列是有配置PLAINTEXT_AFTER_JOIN的
因为要对age做age DIV 10 >= 2过滤后，在进行group by ，所以age又要有compare和group by 的PLAINTEXT权限

2. 因为目前我们的工程也是用go，有scql go的sdk可以把sql解析出ccl吗，我们import到我们的工程里进行调用。

**Comment by jingshi-ant** [comment]
感谢补充~ 针对补充有两个点解释下：
1.因为join的特殊要求，两张表的id需要对两方都做授权，因此应该有四个id相关的授权，可以参考我们的快速开始文档。 
2.age做age DIV 10 >= 2过滤后，在进行group by。 因为最终只看了group by的结果，而没有看compare的中间结果，因此可以只设置compare或者group by的PLAINTEXT试试。 （设置compare则过滤后可见性已经是明文了，不影响后续其它计算；设置group by则过滤在密态下也可以完成计算）

**Comment by YuChangF** [comment]
> 感谢补充~ 针对补充有两个点解释下： 1.因为join的特殊要求，两张表的id需要对两方都做授权，因此应该有四个id相关的授权，可以参考我们的快速开始文档。 2.age做age DIV 10 >= 2过滤后，在进行group by。 因为最终只看了group by的结果，而没有看compare的中间结果，因此可以只设置compare或者group by的PLAINTEXT试试。 （设置compare则过滤后可见性已经是明文了，不影响后续其它计算；设置group by则过滤在密态下也可以完成计算）
1. 这点知道的，所以也设置了，双方都对id做了Join设置，所以一共是有4个id设置的
![20231206-102445](https://github.com/secretflow/scql/assets/14515385/2f0f5481-e7ba-468a-b624-6ab086c64fdc)
2. 我改成compare试了，不行。报ccl check failed: the 1th column feddb.heart_chongqing.age in the result is not visibile (PLAINTEXT_AFTER_COMPARE) to party 2
![20231206-103823](https://github.com/secretflow/scql/assets/14515385/2ec625c2-348a-4b97-b2df-1ddf8cf3aac1)

**Comment by YuChangF** [comment]
> 感谢补充~ 针对补充有两个点解释下： 1.因为join的特殊要求，两张表的id需要对两方都做授权，因此应该有四个id相关的授权，可以参考我们的快速开始文档。 2.age做age DIV 10 >= 2过滤后，在进行group by。 因为最终只看了group by的结果，而没有看compare的中间结果，因此可以只设置compare或者group by的PLAINTEXT试试。 （设置compare则过滤后可见性已经是明文了，不影响后续其它计算；设置group by则过滤在密态下也可以完成计算）

1. 这点知道的，所以也设置了，双方都对id做了Join设置，所以一共是有4个id设置的
![20231206-102445](https://github.com/secretflow/scql/assets/14515385/35bb607f-2d4b-4828-a558-f42b0a1a2d18)

2. 我改成compare试了，不行。报ccl check failed: the 1th column feddb.heart_chongqing.age in the result is not visibile (PLAINTEXT_AFTER_COMPARE) to party 2
![20231206-104031](https://github.com/secretflow/scql/assets/14515385/f0e122ff-bb3a-49f8-a4cc-fcf7cdf193ac)

**Comment by jingshi-ant** [comment]
看起来报错从之前的id列变为了age列。报错原因可能和生成的图有关，只设置为group by是否work？另外这里：chongqing.age DIV 10 >= 2 能否改为chongqing.age >= 20 ？

补充：为了方便后续具体问题定位，可以先建议清理掉其它无关字段试试。

**Comment by YuChangF** [comment]
> 看起来报错从之前的id列变为了age列。报错原因可能和生成的图有关，只设置为group by是否work？另外这里：chongqing.age DIV 10 >= 2 能否改为chongqing.age >= 20 ？
> 
> 补充：为了方便后续具体问题定位，可以先建议清理掉其它无关字段试试。

改了SQL（如下），并且授权成PLAINTEXT_AFTER_GROUP_BY(age)，还是不行。 把age >= 20去掉肯定是可以的，试了也是可以的，但是加上了还是报和上面一样的 joinNode.buildCCL: failed to check condition (eq(feddb.heart_chongqing.id, feddb.heart_shanghai.id)) left party(2) ccl(UNKNOWN)错误。

SELECT 
       chongqing.age,
       chongqing.target,
       shanghai.thal,
       COUNT(DISTINCT chongqing.id) as total_records
   FROM feddb.heart_chongqing chongqing
   JOIN feddb.heart_shanghai shanghai
   ON chongqing.id = shanghai.id
   WHERE chongqing.age >= 20
   GROUP BY chongqing.age,chongqing.target,shanghai.thal;

![20231206-111718](https://github.com/secretflow/scql/assets/14515385/fc1a4062-0d98-4984-a0fd-01ba9f297d96)

**Comment by jingshi-ant** [comment]
感谢反馈，看起来和我们graph生成和CCL推导的逻辑异常有关，这个场景我们内部会记录跟进，后续有结论后会及时同步~
另外也建议您尝试改写query语句，使用嵌套来达到目的（当然对于大的数据量，相较于过滤前置，整体会消耗更多资源）：select * from (select xxx group by xxx) where chongqing.age > 20；

**Comment by YuChangF** [comment]
> 1.一个字段目前的实现是只支持配置一个ccl。报错看应该是id列没有配置PLAINTEXT_AFTER_JOIN，为什么是age配置多个ccl呢，这里能否辛苦补充下细节？ 2.目前还没有相关工具来解析需要的ccl，建议：自动授权安全性不高，是否可以考虑只对需要保护的字段进行ccl限制，其它低敏感的字段设置为PLAINTEXT

觉得一个字段支持多个CCL应该也是合理的，而且给业务上的灵活性也高，比如字段先比较过滤完在sum或者group by，如果安全性有问题，可以通过审批等人工操作来进行，审批同意了都好说。 所以问下当时SCQL一个字段只支持一个CCL约束是有哪方面的考量

**Comment by jingshi-ant** [comment]
一个字段只支持一个CCL约束只是当前实现上的问题哈，如果配置多个CCL是普遍合理的需求，我们也可以考虑支持的~不过具体去定需求、方案到落地是长期的事情了。短期我们也会积极配合解决您场景上遇到的问题。

**Comment by YuChangF** [comment]
> 一个字段只支持一个CCL约束只是当前实现上的问题哈，如果配置多个CCL是普遍合理的需求，我们也可以考虑支持的~不过具体去定需求、方案到落地是长期的事情了。短期我们也会积极配合解决您场景上遇到的问题。

因为目前我们的工程也是用go，有scql go的sdk可以把sql解析出ccl吗，我们import到我们的工程里进行调用。先实现自动授权的功能

**Comment by jingshi-ant** [comment]
> > 一个字段只支持一个CCL约束只是当前实现上的问题哈，如果配置多个CCL是普遍合理的需求，我们也可以考虑支持的~不过具体去定需求、方案到落地是长期的事情了。短期我们也会积极配合解决您场景上遇到的问题。
> 
> 因为目前我们的工程也是用go，有scql go的sdk可以把sql解析出ccl吗，我们import到我们的工程里进行调用。先实现自动授权的功能

目前我们没有 解析sql得到ccl的限制 这个逻辑，因此没法根据query自动授权。  SCQL代码只是校验操作是否match ccl限制，以及根据ccl限制选择更快的计算。

**Comment by jingshi-ant** [comment]
> 一个字段只支持一个CCL约束只是当前实现上的问题哈，如果配置多个CCL是普遍合理的需求，我们也可以考虑支持的~不过具体去定需求、方案到落地是长期的事情了。短期我们也会积极配合解决您场景上遇到的问题。

我们的ccl逻辑会在近期高优投入进行升级，后续是可以支持配置多个ccl的，但解析sql获得ccl还需进一步考虑可行性.

**Comment by YuChangF** [comment]
> > 一个字段只支持一个CCL约束只是当前实现上的问题哈，如果配置多个CCL是普遍合理的需求，我们也可以考虑支持的~不过具体去定需求、方案到落地是长期的事情了。短期我们也会积极配合解决您场景上遇到的问题。
> 
> 我们的ccl逻辑会在近期高优投入进行升级，后续是可以支持配置多个ccl的，但解析sql获得ccl还需进一步考虑可行性.

我看源码，这部分是生成逻辑执行计划，并且拿到VisitInfo，我们是不是可以尝试import后进行调用使用拿到visitinfo，然后反生成grant和revoke CCL的SQL？
![ec089b0bd486660c744b40672282b34](https://github.com/secretflow/scql/assets/14515385/bda79be7-d3e3-4bfc-b3a3-34ea3edb8753)

**Comment by jingshi-ant** [comment]
这里的privilege是 db、table的 select、create、drop等权限， 并非CCL的校验信息；vistinfo里面也不包含CCL。
CCL校验的逻辑可以参考build_ccl.go以及buildLogicalNode等逻辑。（分的比较散）

**Comment by YuChangF** [comment]
> > 一个字段只支持一个CCL约束只是当前实现上的问题哈，如果配置多个CCL是普遍合理的需求，我们也可以考虑支持的~不过具体去定需求、方案到落地是长期的事情了。短期我们也会积极配合解决您场景上遇到的问题。
> 
> 我们的ccl逻辑会在近期高优投入进行升级，后续是可以支持配置多个ccl的，但解析sql获得ccl还需进一步考虑可行性.

请问就是升级的版本具体是在几号发布？升级内容有哪些？是否就可以支持一个字段配置多个CCL？

**Comment by tongke6** [comment]
@YuChangF CCL 升级的方案还在设计讨论中，目前无法给出具体的发布时间，抱歉～ 

新的方案会考虑支持多约束配置，如果你还有其他需求，也欢迎提出来，帮助我们把方案考虑得更完善点
