### ISSUE TITLE
SCQL接入SecretFlow框架

### ISSUE THREAD

**Issue by banlandadi** [secretflow/scql#185]
SCQL接入SecretFlow框架预计什么时间能够完成？
SCQL接入SecretFlow框架会不会更改现有的SCDB和clients的部署模式？
如果不变的话，SCDB会在kuscia调度层之前还是之后呢？
感谢~

**Comment by tongke6** [comment]
@banlandadi 方便贴一下你看到的架构图吗？感觉上有点误解，或者是图的表达有点歧义，我好解释说明一下

**Comment by banlandadi** [comment]
@tongke6 https://github.com/secretflow/secretflow 就是Readme第一个图，第一层最右边是SCQL，第二层最右边是SCQL Translator那张，感谢~

**Comment by tongke6** [comment]
Ok 了解，抱歉造成这样的误解。

我们整个 group 是 secretflow，secretflow group 下面也有个 secretflow 的 repo。这个架构图是针对 secretflow group 的，也就是所有隐语的产品的架构图。

SCQL 是 secretflow group 下的一个 repo，它的部署架构不会改变。

后面 SCQL 也会和 kusica 配合，支持被 kuscia 拉起，算是进程或者 pod 层面的调度。SCQL 自己 op 的调度，还是由 SCQL 自己完成。

**Comment by banlandadi** [comment]
好的谢谢您
