### ISSUE TITLE
SCQL中执行groupby以及max的具体过程

### ISSUE THREAD

**Issue by lengsen** [secretflow/scql#188]
您好，想要询问一下隐语的scql中union all 以及 group by具体算法的过程：

如存在两个表
tableA

id | sex | age
-- | -- | --
1 | 男 | 30
2 | 女 | 20
3 | 男 | 25

tableB

id | sex | age
-- | -- | --
1 | 男 | 20
2 | 男 | 15
3 | 女 | 40

执行代码：
`SELECT sex, MAX(age) AS max_age
FROM (
    SELECT sex, age FROM tableA
    UNION ALL
    SELECT sex, age FROM tableB
) AS C
GROUP BY sex;`

根据sex进行分组，得到年龄的最大值
sex | max(age)
-- | --
女 | 40
男 | 30

在上述过程中，是怎么进行密态计算的？使用了什么算法？两方分别都进行了哪些操作，都需要进行哪些交互，具体过程是什么样的？

**Comment by tongke6** [comment]
您好 @lengsen 

group by 算法过程讲解可以看看 隐语出品的 MOOC  课程 [【MOOC2 第11讲 应用实践丨隐语SCQL应用实践】](https://www.bilibili.com/video/BV1KG411Q72P/?share_source=copy_web&vd_source=e8fe20576e94c05ce6c0fbc871662b3d )，从 13 分10 秒左右开始。

union all 的实现思路比较简单，各方把自己的数据 secret sharing 给其他方，然后 concat 在一起

**Comment by lengsen** [comment]
好的，谢谢
