### ISSUE TITLE
关于scql执行表连接（join）的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#189]
scql执行表连接的时候，底层使用的是什么算法实现的，是secure yannakakis吗，这一块具体在代码的哪个位置，还有想问一下scql的join操作目前包括哪几种。

**Comment by jingshi-ant** [comment]
底层是psi（默认可能触发：ecdh psi/ecdh oprf psi）。 代码逻辑可以参考engin/operator/join.cc
