### ISSUE TITLE
关于自行修改代码后进行编译的问题

### ISSUE THREAD

**Issue by shenpeilin** [secretflow/scql#236]
我这边基于内部的一些需求考虑，对scql的代码进行修改，并通过secretflow/scql-ci这个容器编译出了可执行文件，替换掉了secretflow/scql:0.4.0b1中对应的文件，重新启动容器时报错如下：
<img width="809" alt="image" src="https://github.com/secretflow/scql/assets/9464930/dd25bf6a-9f4c-440d-b119-bfd6badc416c">
请问这是可以解决的吗？或者如果我想要达到上面的这个目的有什么其它标准的方式吗？

**Comment by tongke6** [comment]
secretflow/scql-ci 是基于 ubuntu 22.04 的镜像，secretflow/scql:0.4.0b1 好像是基于 openanolis/anolisos:8.6 的镜像，他们的 glibc 的版本不一样导致的。

可以考虑使用 secretflow/release-ci:latest 镜像构建再替换 secretflow/scql:0.4.0b1中对应的文件。

**Comment by shenpeilin** [comment]
@tongke6 
目前用secretflow/scql-ci编译最新的scql代码，make pb命令会报下面这个错：
![image](https://github.com/secretflow/scql/assets/9464930/c1c99ff5-543a-461b-9650-67327eaf43f6)
有影响吗？

**Comment by Chrisdehe** [comment]
辛苦查看下这个exited容器的日志，贴一下信息

**Comment by tongke6** [comment]
@shenpeilin 可能是因为最新的代码升级到了 bazel 6.5.0 导致的

可以先切到这个 commit 试下： aa66beff47534900421dae07767205c79e4b310b

**Comment by tongke6** [comment]
没有影响，pb 相关代码已经生成好了。不需要重新 make pb

这个问题 @jingshi-ant 帮忙看下

**Comment by jingshi-ant** [comment]
疑似脚本使用了相对路径导致的报错。可以尝试在容器外make pb试试。
