### ISSUE TITLE
关于scqlEngine使用postgreSql连接出现的问题

### ISSUE THREAD

**Issue by coffee1110** [secretflow/scql#238]
### 1. 当前的gflags.conf的配置如下
`{"datasources":[{"id":"ds001","name":"postgresql db","kind":"POSTGRESQL","connection_str":"dbname=postgres;user=postgres;password=fuchain@2020;host=192.168.209.130;port=5432"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
`
执行查询语句是出现如下异常
`2024-01-25 06:25:57.650 [error] [engine_service_impl.cc:RunPlanSync:364] [scqlengine] RunExecutionPlan run jobs(99b3ee8e-bb4a-11ee-bb39-0242ac1a0002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Connection Error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
`
请问下是哪里配置有问题吗

**Comment by coffee1110** [comment]
psql服务的listen_address配置为*，端口也是正常联通的

**Comment by coffee1110** [comment]
psql的配置写错了，应该用空格而不是;分割

**Comment by jingshi-ant** [comment]
感谢反馈，check了下文档，psql示例错误使用了'；'分割，我们会高优修改下~
