### ISSUE TITLE
arm compilation error

### ISSUE THREAD

**Issue by ztreble** [secretflow/scql#24]
`/private/var/tmp/_bazel_treblez/71836fdab57b2df943c63e6dd024e4fc/sandbox/darwin-sandbox/952/execroot/scql/external/local_config_cc/wrapped_clang -O3    -I../lib -DXXH_NAMESPACE=LZ4_ -lc++ -fobjc-link-runtime -headerpad_max_install_names -no-canonical-prefixes -target arm64-apple-macosx11.0 -lc++ -target arm64-apple-macosx11.0 -fvisibility=hidden ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4 
ld: warning: ignoring file ../lib/lz4.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file ../lib/lz4frame.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file ../lib/lz4hc.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file ../lib/xxhash.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file bench.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file datagen.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file lz4cli.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file lz4io.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
make[1]: *** [lz4] Abort trap: 6
make: *** [lz4-release] Error 2
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/darwin_arm64-opt/bin/external/com_github_lz4_lz4/lz4_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/darwin_arm64-opt/bin/external/com_github_lz4_lz4/lz4_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin_arm64-opt/bin/external/com_github_lz4_lz4/lz4_foreign_cc/Make.log

Target //engine/exe:scqlengine failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 645.242s, Critical Path: 642.62s
INFO: 264 processes: 26 internal, 238 darwin-sandbox.
FAILED: Build did NOT complete successfully`

**Comment by anakinxc** [comment]
> > Hi @ztreble
> > Can you provide your macOS and Xcode version?
> > Thanks
> 
> MacBook Pro (13-inch, M1, 2020) Xcode Version 13.4.1 (13F100)

好的，我们看一下

**Comment by anakinxc** [comment]
Hi @ztreble 

请问可以提供一下
`arch`, `clang -v`, `ld -v` 的输出吗

**Comment by ztreble** [comment]
> Hi @ztreble
> 
> 请问可以提供一下 `arch`, `clang -v`, `ld -v` 的输出吗

分别是 
`arm64` 
`Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`
`@(#)PROGRAM:ld  PROJECT:ld64-764
BUILD 11:22:55 Apr 28 2022
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 13.1.6, (clang-1316.0.21.2.5) (static support for 28, runtime is 28)
TAPI support using: Apple TAPI version 13.1.6 (tapi-1316.0.7.3)`

**Comment by anakinxc** [comment]
Hi @ztreble 

`ld: warning: ignoring file lz4io.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64`

It looks like somehow some of the object files were built for x86_64. `arch`, `clang` and `ld` looks fine.

Can you try `bazel clean --expunge` and rebuild?

**Comment by xfap** [comment]
Maybe could check if `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/` is empty. If it's so, then below may resolove this question. 
- `xcode-select --install` 
- then, `sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/* /usr/local/include/`

More info, see https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15/58349403#58349403

**Comment by ztreble** [comment]
> Hi @ztreble
> 
> `ld: warning: ignoring file lz4io.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64`
> 
> It looks like somehow some of the object files were built for x86_64. `arch`, `clang` and `ld` looks fine.
> 
> Can you try `bazel clean --expunge` and rebuild?

可以了，感谢
