### ISSUE TITLE
执行 bazel build //engine/exe:scqlengine -c opt，提示没有办法下载latest 版本

### ISSUE THREAD

**Issue by friendsAI** [secretflow/scql#242]
**Describe the bug**
在build SCQL engine的时候，执行 bazel build //engine/exe:scqlengine -c opt，提示没有办法下载latest 版本。

**To Reproduce**
1. start dev container
2. attach to dev container
3. bazel build //engine/exe:scqlengine -c opt

软件版本信息
ubuntu22.04
docker 24.0.5

**Comment by jingshi-ant** [comment]
具体报错信息贴一下？因为依赖很多github库，需要能访问github网络环境。

**Comment by anakinxc** [comment]
> dial tcp 142.251.42.234:443: i/o timeout

看起来是网络问题

**Comment by friendsAI** [comment]
> > dial tcp 142.251.42.234:443: i/o timeout
> 
> 看起来是网络问题

应该不是网络问题。我在web页面可以打开https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/，我在该页面插了，没有一个版本号 对应latest。给出的提示信息已经说了“  could not resolve the version 'latest' to an actual version number”

**Comment by zimu-yuxi** [comment]
@friendsAI 可以参考下这个[issue](https://github.com/bazelbuild/bazelisk/issues/220)，可以尝试下

**Comment by friendsAI** [comment]
谢谢。
