### ISSUE TITLE
执行 “make pb" 产生的错误

### ISSUE THREAD

**Issue by friendsAI** [secretflow/scql#243]
**Describe the bug**
错误信息如下：ERROR: An error occurred during the fetch of repository 'com_github_golang_protobuf':
Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_gazelle/internal/go_repository.bzl", line 149, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_golang_protobuf: fetch_repo: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info": dial tcp 172.217.163.49:443: i/o timeout

web浏览器可以访问https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info， ping不通172.217.163.49。
请问如何解决此问题？

**Comment by zimu-yuxi** [comment]
这是哪里的报错，请告知下场景

**Comment by friendsAI** [comment]
在容器里面。就是一步步按照官网的提示来操作的。

**Comment by anakinxc** [comment]
> **Describe the bug** 错误信息如下：ERROR: An error occurred during the fetch of repository 'com_github_golang_protobuf': Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_gazelle/internal/go_repository.bzl", line 149, column 17, in _go_repository_impl fail("failed to fetch %s: %s" % (ctx.name, result.stderr)) Error in fail: failed to fetch com_github_golang_protobuf: fetch_repo: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info": dial tcp 172.217.163.49:443: i/o timeout
> 
> web浏览器可以访问[https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info，](https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.info%EF%BC%8C) ping不通172.217.163.49。 请问如何解决此问题？

设置一下 bazel 的 proxy

**Comment by anakinxc** [comment]
参考一下[bazel文档](https://bazel.build/external/advanced#using_proxies)

**Comment by jingshi-ant** [comment]
看起来还是网络问题，设置下go的代理试试：go env -w GOPROXY=https://goproxy.cn,direct
另外补充下：make pb在容器内执行可能会报错，可以直接在容器外执行来更新pb（当然除非更改了proto文件，否则无需执行make pb来更新pb）

**Comment by friendsAI** [comment]
> 参考一下[bazel文档](https://bazel.build/external/advanced#using_proxies)

这个方法可以。
