### ISSUE TITLE
执行make时的错误

### ISSUE THREAD

**Issue by friendsAI** [secretflow/scql#245]
**Describe the bug**
错误信息如下：
pkg/audit/audit_log.go:29:2: no required module provides package github.com/secretflow/scql/pkg/proto-gen/audit; to add it:
go get github.com/secretflow/scql/pkg/proto-gen/audit
根据提示信息，执行 go get github.com/secretflow/scql/pkg/proto-gen/audit 命令，提示：go: github.com/secretflow/scql/pkg/proto-gen/audit: no matching versions for query "upgrade"。
请问如何解决此问题。

**Comment by Chrisdehe** [comment]
这个错误看起来是在github.com/secretflow/scql/pkg/proto-gen/audit中没有与“upgrade”匹配的版本
尝试下使用最新的版本：go get github.com/secretflow/scql/pkg/proto-gen/audit@latest
或者可以从库中手动克隆代码在本地进行操作。

**Comment by tongke6** [comment]
@friendsAI 请问是在物理机还是在容器里执行的 make 命令，对应环境里的 go 版本是多少？

**Comment by friendsAI** [comment]
> @friendsAI 请问是在物理机还是在容器里执行的 make 命令，对应环境里的 go 版本是多少？

在容器里执行的，go版本1.22.0

**Comment by tongke6** [comment]
@friendsAI 容器不是用的我们提供的开发镜像吗？`secretflow/scql-ci`
