### ISSUE TITLE
关于创建 ed25519key.pem 文件

### ISSUE THREAD

**Issue by songsong124** [secretflow/scql#250]
Centos7.9 
openssl  不支持ed25519，怎么处理。
[root@lyy scql-p2p]# openssl genpkey -algorithm ed25519 -out ed25519key.pem
Algorithm ed25519 not found
[root@lyy scql-p2p]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by jingshi-ant** [comment]
可能的方式：
1.考虑升级openssl。
2.可以找个openssl版本符合的机器，执行指令后把文件复制进去。
