### ISSUE TITLE
Error: CreateProject: status: 404 Not Found, body: 404 page not found

### ISSUE THREAD

**Issue by songsong124** [secretflow/scql#251]
报错日志：
[root@lii scql]# ./brokerctl create project --project-id "demo" --host http://192.168.118.207:8081
Error: CreateProject: status: 404 Not Found, body: 404 page not found
Usage:
  brokerctl create {project|table <name>|job} [flags]

Flags:
      --columns string        columns for table, format: 'column_name column_type [, name type]', e.g: 'ID string, age int'
      --db-type string        the database type to which the table belongs, e.g: 'mysql' (default "mysql")
  -h, --help                  help for create
      --project-conf string   spu conf for project in json format (default "{\"protocol\":\"SEMI2K\", \"field\": \"FM64\"}")
      --query string          the sql query for create job, e.g: 'select count(*) from ta'
      --ref-table string      the physical table name corresponding to the new table, e.g: 'test_table'

Global Flags:
      --host string         host to access broker, e.g: http://localhost:8080
      --project-id string   unique identifier for project
      --timeout int         timeout seconds for http requests to broker (default 1)

docker 8081 日志：
2024-02-26 10:01:15.22610 WARNING server.go:120 |GIN|status=404|method=POST|path=/intra/project/create|ip=192.168.118.207|latency=1.537µs|

**Comment by songsong124** [comment]
![image](https://github.com/secretflow/scql/assets/56468127/422d35f2-6f31-46f9-87fc-190d297bb4b4)

**Comment by Chrisdehe** [comment]
请问问题是否得到解决了？
