### ISSUE TITLE
数据源变更为csv

### ISSUE THREAD

**Issue by xiaohanxu11** [secretflow/scql#253]
请问是否支持csv作为数据源?如果可以对config.yaml、gflags.conf、docker-compose.yaml需要做出哪些修改？
感谢

**Comment by Chrisdehe** [comment]
@xiaohanxu11 hey，CSV数据源在0.5.0b1版本已支持，配置方式请参考：https://www.secretflow.org.cn/zh-CN/docs/scql/0.5.0b2/reference/p2p-deploy-config#config-for-datasource

**Comment by xiaohanxu11** [comment]
感谢回复，[{\"column_name\":\"id\",\"column_type\":\"1\"}]  是需要将所有的列名都写进来吗？有没有可以快速插入所有列名的方法呢？

**Comment by Chrisdehe** [comment]
没有那样的方法，您可以自行通过脚本完成。

**Comment by xiaohanxu11** [comment]
感谢，by the way sqcl有可以了解到benchmark的途径吗

**Comment by Chrisdehe** [comment]
目前scql暂时没有benchmark文档，敬请期待
如有需求请添加隐语技术支持来深入沟通（secretflow02）备注公司/姓名及issue链接
