### ISSUE TITLE
join 问题

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#255]
在测试过程中发现，join只能在一方进行过滤，正常的sql语句join两张表以后出来的虚表是一张整表，以致于不管两张表的先后顺序是啥样的，最终出来的join结果是一致的，应该是两边记录数最多的行
而scql在join操作时，是先求交集索引然后在对应人那边进行过滤，这样如果两张表的数据量不一致，join的期望结果是两张表总体的连接数量，而scql的结果是单方的表的数量，不知道这样做的考虑是什么

**Comment by tyrone-yu** [comment]
其实两边的 filterbyindex 实际上做的事情就是两张表的连接，在 join 的过程中，两方会各自得到交集是什么，然后根据交集得到应该在交集中的原始数据的 index，在生成这个 index 的过程中，会保证两边的 index 能够使最终 filterbyindex 后的数据是对齐的。
那么在 filterbyindex 之后两边的数据实际上就是对齐，也就是你说的连接。
后续再计算 COUNT(*) 其实只需要 tb.is_active 不在需要 ta 参与了，所以理论上没有问题。你可以执行一下和 mysql 对比结果。
NOTE：SCQL 中会对 GROUP BY  的结果进行过滤，删除分组中数据小于 4 的分组。

**Comment by jiushun** [comment]
感谢您的解释，我再细致看看

**Comment by tyrone-yu** [comment]
这个 issue 先关闭了，如果有问题可以另外提 issue，谢谢！
