### ISSUE TITLE
SCQL 开放端口

### ISSUE THREAD

**Issue by songsong124** [secretflow/scql#26]
您好！ SCQL 多节点间通信，采用的是什么方式？我有自己的防火墙iptables 规则，开放哪些端口，使SCQL 节点间能正常通信？

**Comment by tongke6** [comment]
@songsong124 SCQL 系统之间的通讯，走的是 HTTP/HTTPS 协议。关于开放端口，每个服务只需要暴露一个端口，Listen 的端口是可以通过配置文件自定义的。
