### ISSUE TITLE
关于Groupby的一点小疑问

### ISSUE THREAD

**Issue by 982945902** [secretflow/scql#260]
以goupby_sum 为例，在oblivious_group_agg 中通过Scan的方式完成计算。我印象里后续通过Filter过滤出结果行，我理解Filter过程也存在reveal，那么为什么不直接reveal mask，根据mask将数据分组，然后再进行计算，这样也可以减少mpc计算量。

**Comment by jingshi-ant** [comment]
1. 在filter之前会对所有数据进行shuffle以减少数据泄露。
2. 是的，如果先reveal mask可以减少mpc计算量。

**Comment by 982945902** [comment]
> 1. 在filter之前会对所有数据进行shuffle以减少数据泄露。
> 2. 是的，如果先reveal mask可以减少mpc计算量。

@jingshi-ant  soga，感谢解惑
