### ISSUE TITLE
数据的比特长度上限

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/scql#262]
您好，请问每一列数据所能允许的比特长度上限是多少？例如政务数据中有一些字符串类型的身份代码，其比特长度可能在200左右，这样的数据可以输入吗？

感谢帮助！

**Comment by jingshi-ant** [comment]
当前没有对字符串的长度做限制。 200个字符的长度可以支持的。 
不过长字符串的比较、计算均会耗费更多的cpu/memory，数据量大的话建议对长字符串做下处理（计算签名）

**Comment by zzx-QDU** [comment]
感谢！
