### ISSUE TITLE
最新版goland编译

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#266]
go list -m -json all : 运行失败
go: k8s.io/cloud-provider@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/csi-translation-lib@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-scheduler@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kubectl@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/mount-utils@v0.0.0: invalid version: unknown revision v0.0.0
出现这个版本问题

**Comment by jingshi-ant** [comment]
如果在docker外的物理机上编译，需要go 1.22版本。辛苦check下本机的go version

**Comment by jiushun** [comment]
已经将go 的版本升级到1.22.2版本了，该问题就是在go 1.22.2版本下 goland IDE依赖检查时出现的

**Comment by jingshi-ant** [comment]
okey，现在是编译的时候ide报依赖错误？试试直接make会报错吗？
另外k8s.io/cloud-provider这些依赖是环境额外引入的吗？

**Comment by jiushun** [comment]
克隆最新的项目以后，用goland打开，然后会进行依赖检查，出现的上述情况，不清楚是否是mod文件的依赖问题

**Comment by jingshi-ant** [comment]
您好，是否可以理解为只是goland IDE检查有问题，并不实际影响代码的跳转及编译等功能的使用？

**Comment by tyrone-yu** [comment]
> 克隆最新的项目以后，用goland打开，然后会进行依赖检查，出现的上述情况，不清楚是否是mod文件的依赖问题

你在 go.mod 文件中添加如下的代码

// the below fixes the "go list -m all" execution
replace (
	k8s.io/cloud-provider => k8s.io/cloud-provider v0.26.11
	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.26.11
	k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.26.11
	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.26.11
	k8s.io/kubectl => k8s.io/kubectl v0.26.11
	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.26.11
	k8s.io/mount-utils => k8s.io/mount-utils v0.26.11
	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.26.11
)

然后重新打开 goland 加载项目，应该可以暂时规避这个问题

**Comment by jiushun** [comment]
> > 克隆最新的项目以后，用goland打开，然后会进行依赖检查，出现的上述情况，不清楚是否是mod文件的依赖问题
> 
> 你在 go.mod 文件中添加如下的代码
> 
> // the below fixes the "go list -m all" execution replace ( k8s.io/cloud-provider => k8s.io/cloud-provider v0.26.11 k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.26.11 k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.26.11 k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.26.11 k8s.io/kubectl => k8s.io/kubectl v0.26.11 k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.26.11 k8s.io/mount-utils => k8s.io/mount-utils v0.26.11 k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.26.11 )
> 
> 然后重新打开 goland 加载项目，应该可以暂时规避这个问题

感谢，这个方法可以解决代码无法跳转以及代码标红问题

**Comment by tyrone-yu** [comment]
我们后续会想办法下个版本在代码里解决这个问题
