### ISSUE TITLE
关于CCL限制一列数据对于一个参与方当前只能设置一种CCL约束的疑问

### ISSUE THREAD

**Issue by oaHeZgnoS** [secretflow/scql#268]
注意到SCQL文档里对CCL的注意点的描述：一列数据对于一个参与方当前只能设置一种CCL约束。存在这一条限制。
同时发现broker.column_privs表约束是：PRIMARY KEY (`project_id`,`table_name`,`column_name`,`dest_party`)，
想请问，SCQL里只是通过这个约束来确保该限制的吗，如果我们放宽约束为：PRIMARY KEY (`project_id`,`table_name`,`column_name`,`dest_party`,`priv`)，会不会有什么问题？
谢谢，盼复。

**Comment by oaHeZgnoS** [comment]
经黑盒测试发现这样的规律：在执行查询时，逻辑里似乎对某一指定参与方在某一指定表中的某一指定字段，先查出所有的priv，然后要求每一条priv都要满足查询显示的要求，如果有一条不满足，那么会报错：`ERROR: Error: code=300, msg="SubmitQuery: runQuery Execute err: failed to compile query to plan: ccl check failed: the 1th column  in the result is not visibile (PLAINTEXT_AFTER_COMPARE) to party 9999"`。

具体的示例或步骤为：
首先，将表约束放开，即允许某参与方某表某字段有多个权限；
其次，提交单表查询，`select max(age) from alice`；
结果发现，当且仅当priv是唯一一行PLAINTEXT_AFTER_AGGREGATE或者PLAINTEXT，才能查询成功。

**Comment by tongke6** [comment]
目前整个系统的实现，都是基于一列数据对指定参与方只能设置一种 CCL 约束基础上的。只放宽数据库建表的约束无法绕过改限制。

**Comment by oaHeZgnoS** [comment]
> 目前整个系统的实现，都是基于一列数据对指定参与方只能设置一种 CCL 约束基础上的。只放宽数据库建表的约束无法绕过改限制。

好的了解。请问PLAINTEXT_AFTER_COMPARE、PLAINTEXT_AFTER_AGGREGATE、PLAINTEXT_AFTER_GROUP_BY和PLAINTEXT_AFTER_JOIN之间有没有权限的包含关系？

**Comment by tongke6** [comment]
没有包含关系

**Comment by oaHeZgnoS** [comment]
> 没有包含关系

thx。
