### ISSUE TITLE
关于分组查询后结果不全的问题

### ISSUE THREAD

**Issue by oaHeZgnoS** [secretflow/scql#269]
正常select age,count(age) from user_credit group by age，结果是：
20	1
19	1
32	1
30	2
25	4
28	4
50	2
18	1
26	1
27	1
16	1

但是在SCQL里返回：
25 | 4
28 | 4

**Comment by tongke6** [comment]
@oaHeZgnoS SCQL 返回的结果里有一个 warnings 的成员： https://github.com/secretflow/scql/blob/main/api/broker.proto#L228

它应该有个提示，类似这样：`for safety, we filter the results for groups which contain less than 4 items` 
SCQL 默认会把 group by  的结果里，记录条数小于4的分组给过滤掉，这是为了防止结果反推。

**Comment by oaHeZgnoS** [comment]
> @oaHeZgnoS SCQL 返回的结果里有一个 warnings 的成员： https://github.com/secretflow/scql/blob/main/api/broker.proto#L228
> 
> 它应该有个提示，类似这样：`for safety, we filter the results for groups which contain less than 4 items` SCQL 默认会把 group by 的结果里，记录条数小于4的分组给过滤掉，这是为了防止结果反推。

thx

**Comment by tongke6** [comment]
BTW，这个行为是可配置的，详见：https://www.secretflow.org.cn/zh-CN/docs/scql/0.6.0b1/reference/p2p-deploy-config 中的 `security_compromise.group_by_threshold` 配置项
