### ISSUE TITLE
实测发现PLAINTEXT_AFTER_AGGREGATE权限似乎包含PLAINTEXT_AFTER_COMPARE

### ISSUE THREAD

**Issue by oaHeZgnoS** [secretflow/scql#270]
实测发现PLAINTEXT_AFTER_AGGREGATE权限似乎包含PLAINTEXT_AFTER_COMPARE
请问二者的差异在sql中怎么体现？

**Comment by tyrone-yu** [comment]
能举个例子么？

**Comment by oaHeZgnoS** [comment]
> 能举个例子么？

在对某一字段分别设置四种ccl时，发现跟文档描述一致，4个各管各的没问题，测试脚本如下：
`-- 比较：被比较的结果可以披露（注意不是说where age>15后可以披露age）
-- select age>15 from alice

-- 聚合：被聚合的结果可以披露
-- select max(age) from alice

-- 分组：被分组的列可以披露
-- select age from alice group by age

-- 关联：被关联的列可以披露
-- select a1.age from alice a1 inner join alice a2 ON a1.age=a2.age`

只是聚合里好像有一个特殊的count，不论给设置上面4个哪种ccl，都可以使用：`select count(age) from alice`

**Comment by tyrone-yu** [comment]
目前 scql 的 count 没有支持 null 所以 count(age) 等同于 count(*)
可以看下 scql 的官方文档，里面有说明 https://www.secretflow.org.cn/zh-CN/docs/scql/0.6.0b1/topics/ccl/intro
![image](https://github.com/secretflow/scql/assets/26001894/b1fe9885-2729-45bc-8362-9ca366b19854)

**Comment by oaHeZgnoS** [comment]
> ount 没有支持 null 所以 count(age) 等同于 coun

thx.
