### ISSUE TITLE
SCQL的MPC算子测试

### ISSUE THREAD

**Issue by bobozi-cmd** [secretflow/scql#271]
我想以Query的粒度对SCQL的MPC算子进行性能测试，希望输入一个简单的Query，类似`select 1+1 from ta;`然后用这个query的执行时间来估算ADD算子的时间（明文计算应该不会调用到ADD算子，这里是举个例子），现在的问题是如何构造合适的Query来覆盖足够多的算子，想问一下社区有没有什么好的解决方法

**Comment by tongke6** [comment]
如果只是测试某个具体算子的时间，可以看 engine 的执行日志，算子开始执行和结束执行时都会打日志
