### ISSUE TITLE
编译SCQL遇到的问题

### ISSUE THREAD

**Issue by bobozi-cmd** [secretflow/scql#272]
我在docker外编译SCQL（为了生成compile_command来帮助代码跳转）时，会遇到poco的函数undefined的报错，猜测可能是poco库没有编译成功或者链接成功，我不是很懂bazel，想咨询一下社区怎么解决这个问题。
下面是报错的部分截图：
![1715071145376](https://github.com/secretflow/scql/assets/69450538/dcb75690-3f11-4e7f-a034-ab0d62c51dd3)
电脑的相关配置如下：
os: ubuntu 22.04, linux 6.5.0
go version: 1.22.2
bazel version: 6.5.0
gcc version: 11.4.0

**Comment by tongke6** [comment]
用的是什么 ld？

**Comment by tongke6** [comment]
编译的命令方便贴一下吗

**Comment by bobozi-cmd** [comment]
`bazel build //engine/exe:scqlengine -c opt`

**Comment by bobozi-cmd** [comment]
补充：之前按照https://github.com/secretflow/scql/issues/47#issuecomment-1559066691的issue提供的解决方法修改了bazel的build文件，现在还原修改以后会报下面的错误：
![1715079822338](https://github.com/secretflow/scql/assets/69450538/d84cb8ba-6548-476b-bdde-d64514e053e3)

**Comment by tongke6** [comment]
在还原更改，不打 patch 的情况下，试下安装 libstdc++6  `sudo apt-get install libstdc++6`  看看

**Comment by bobozi-cmd** [comment]
还是报错，附件是报错的全部log。
[log.txt](https://github.com/secretflow/scql/files/15234871/log.txt)

**Comment by tongke6** [comment]
`sudo apt-get install lld` 后再试一下

**Comment by bobozi-cmd** [comment]
安装lld之后报新的错误了，显示我不支持C++14，但是我的g++版本已经是11.4了，我看docker里面的c++版本好像也是11.4
![1715093004481](https://github.com/secretflow/scql/assets/69450538/b0fa61e6-385a-4c10-94f7-4a2d2f3fde80)

**Comment by anakinxc** [comment]
贴一下 g++ 的版本和 lld 的版本

**Comment by bobozi-cmd** [comment]
![1715093695910](https://github.com/secretflow/scql/assets/69450538/6e5027fc-5dca-423b-a9b4-c140dd68a532)

**Comment by anakinxc** [comment]
> ![1715093695910](https://private-user-images.githubusercontent.com/69450538/328571946-6e5027fc-5dca-423b-a9b4-c140dd68a532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTQwNzAsIm5iZiI6MTcxNTA5Mzc3MCwicGF0aCI6Ii82OTQ1MDUzOC8zMjg1NzE5NDYtNmU1MDI3ZmMtNWRjYS00MjNiLWE5YjQtYzE0MGRkNjhhNTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE0NTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNGFjOTY5Mzg4NGY0OGFmYzBlZmVlMTE2ZjUwZDkyZTIzZGYxYjQ1YjM0NmRkMThlMDZkMGY5Mjc2ZDY4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAj2SqvkSA41v68465RRlB2lm7nhaZqRdypdacVLsvc)

建议和 docker 一致，用 lld 15 先，19 都还是 unstable 的

还有换完 linker 建议 `bazel clean --expunge` 一下再重新 build

**Comment by bobozi-cmd** [comment]
执行`bazel clean --expunge` 之后就可以编译了，非常感谢
