### ISSUE TITLE
关于SCDB的query执行时间统计不一致的问题

### ISSUE THREAD

**Issue by bobozi-cmd** [secretflow/scql#273]
我在测试query的端到端时延的时候想直接使用scdbclient输出的执行时间，但是发现同一条query执行多次，输出的时间差别比较大，想问一下是不是scdbclient的执行时间统计不准确，是否有更准确的统计方式。
下面是我的测试信息：
使用的是scdb-tutorial提供的表，自己随机生成了5w条数据，执行同样一条query，执行时间相差了5倍左右
![8ef745d03e57e58dcd47fb934bf3abb1](https://github.com/secretflow/scql/assets/69450538/31491c9f-586f-4eaa-ac17-0018378b0e16)

**Comment by bobozi-cmd** [comment]
我通过查看engine侧的log，发现多次执行相同的query，log里面的running_cost的结果相差也很大，看上去是每次查询都会有一些性能上的随机性，不知道是MPC算法从理论上就带来了这种随机性，还是在实现的时候引入的随机性呢

**Comment by tyrone-yu** [comment]
> 我通过查看engine侧的log，发现多次执行相同的query，log里面的running_cost的结果相差也很大，看上去是每次查询都会有一些性能上的随机性，不知道是MPC算法从理论上就带来了这种随机性，还是在实现的时候引入的随机性呢

能把两次执行的 broker 的日志和 engine 的日志发出来看下么？理论上 scql 在执行同一个 query 的时候会生成相同的执行图，不会带有任何的随机性，执行时间的波动可能与网络波动或者 cpu 的线程调度。

**Comment by bobozi-cmd** [comment]
我重新执行了demo提供的命令，下面是产生的log：
scdbclient：
![image](https://github.com/secretflow/scql/assets/69450538/ad18bd52-c3fd-47e0-b8d2-aae896dc3cbc)
![image](https://github.com/secretflow/scql/assets/69450538/47a82d18-5787-4e55-8e48-8e2b437ca40d)
engine:
[sciengine-alice.log](https://github.com/secretflow/scql/files/15260327/sciengine-alice.log)
[sciengine-bob.log](https://github.com/secretflow/scql/files/15260329/sciengine-bob.log)
scdb:
[scdb.log](https://github.com/secretflow/scql/files/15260330/scdb.log)
网络的话，因为都是同一台机器，应该不会有什么波动；我在跑query的时候系统没有其他任务，cpu线程调度（测试的机器有24个核）可能也影响不大？辛苦您帮忙看一下原因

**Comment by tyrone-yu** [comment]
这里确实是网络本身导致的
![image](https://github.com/secretflow/scql/assets/26001894/dbe75363-b446-4e50-81f5-fe43fa26dd2d)
engine 在执行任务之前会先进入 create session 的过程，create session 的时候不同的 engine 会先建立连接。但是由于 scdb 下发请求给 engine 有一个先后的顺序，假设 alice engine 先接收到 scdb 的请求，就会请求和 bob engine 建立连接，如果 bob 这个时候尚未接收到 scdb 的请求，那么建立连接就会失败，我们为了保证建立连接成功的概率增加了重试，执行时间较长的请求，就是触发了重试流程。我们这里的重试间隔设置了一个固定的时间，这个时间就是你发现的执行时间波动的来源

**Comment by bobozi-cmd** [comment]
请问有什么办法可以消除这种波动呢

**Comment by tyrone-yu** [comment]
暂时的实现上没有办法消除，你这边是有特殊的需求么？可以把背景和需求说明一下

**Comment by bobozi-cmd** [comment]
我是在测试端到端时延的时候发现的这种波动，如果能消除肯定更准确，不能消除我可以测试多次取均值应该也影响不大

**Comment by tyrone-yu** [comment]
> 我是在测试端到端时延的时候发现的这种波动，如果能消除肯定更准确，不能消除我可以测试多次取均值应该也影响不大

我们后面会想办法减小这个影响的，但是一时半会不会做调整

**Comment by bobozi-cmd** [comment]
好的，谢谢
