### ISSUE TITLE
关于新版代码 engine 执行报错

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#275]
采用最新代码编译engine后，放入docker容器里面并重启，重新执行查询出现以下报错：
[demo]alice> SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;
[fetch]err: Code: 320, message:RunExecutionPlan run jobs(66219464-0e7f-11ef-b557-0242ac150005) failed, catch std::exception=[Enforce fail at engine/framework/exec.cc:66] node_.attributes().count(name) > 0. The attribute psi_algorithm of op Join does not exist
Stacktrace:
#0 scql::engine::ExecContext::GetAttribute()+0x55b6fd3c837d
#1 scql::engine::ExecContext::GetInt64ValueFromAttribute()+0x55b6fd3c8577
#2 scql::engine::op::Join::ValidateJoinTypeAndAlgo()+0x55b6fd24894a
#3 scql::engine::op::Join::Validate()+0x55b6fd248044
#4 scql::engine::Operator::Run()+0x55b6fce13618
#5 scql::engine::Executor::RunExecNode()+0x55b6fce13398
#6 scql::engine::EngineServiceImpl::RunPlanCore()+0x55b6fcde7ccf
#7 scql::engine::EngineServiceImpl::RunPlanSync()+0x55b6fcde85eb
#8 scql::engine::EngineServiceImpl::RunExecutionPlan()+0x55b6fcde6bae
#9 scql::pb::SCQLEngineService::CallMethod()+0x55b6fd3f92b6
#10 brpc::policy::ProcessHttpRequest()+0x55b70100cfc1
#11 brpc::ProcessInputMessage()+0x55b700f8cdce
#12 brpc::InputMessenger::InputMessageClosure::~InputMessageClosure()+0x55b700f8cecb
#13 brpc::InputMessenger::OnNewMessages()+0x55b700f8df35
#14 brpc::Socket::ProcessEvent()+0x55b70110c82d
#15 bthread::TaskGroup::task_runner()+0x55b7011c2153

1. bazel build //engine/exe:scqlengine -c opt
2.
#!/bin/bash

set -x

go build -o scqlserver cmd/scdbserver/main.go

docker cp bazel-bin/engine/exe/scqlengine scdb-tutorial-engine_alice-1:/home/admin/bin/
docker cp bazel-bin/engine/exe/scqlengine scdb-tutorial-engine_bob-1:/home/admin/bin/
docker cp scqlserver scdb-tutorial-scdb-1:/home/admin/bin/

docker restart scdb-tutorial-engine_alice-1 scdb-tutorial-engine_bob-1 scdb-tutorial-scdb-1
3. requery

**Comment by jingshi-ant** [comment]
从报错内容看，是broker的版本较久，导致执行图缺乏部分字段信息，engine执行报错。
建议：使用较新版本的broker，或者自行编译对应版本的broker

**Comment by jiushun** [comment]
已解决谢谢
