### ISSUE TITLE
scql支持哪些数据库

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/scql#279]
你好，请问目前scql除了mysql还支持哪些数据库，特别是有对国产数据库的支持吗，比如kingbase等，或者未来有这方面的支持计划吗

**Comment by tongke6** [comment]
@Repo-Zhuang 还支持 Oceanbase/PostgreSQL/SQLite 等。Oceanbase 也是国产数据库。

如果 kingbase 支持 mysql 协议的话（支持用 mysqlclient 链接使用），就可以支持。

对于数据源扩展方面，我们有一个可扩展的框架，让用户可以自定义实现对接的各种数据源。

**Comment by Repo-Zhuang** [comment]
好的，谢谢。另外我想问下如果我想使用Oceanbase 的话，应该怎么配置呢

**Comment by tongke6** [comment]
按 MySQL 数据源的形式配置，通过 OBProxy 连 Oceanbase

**Comment by JudySue** [comment]
请问这个扩展框架可以在哪里查看说明，想试试接入一个新的数据源
