### ISSUE TITLE
关于添加自定义的算子

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/scql#280]
你好，我想请问下算子开发的具体流程，我参考了cos算子的实现，但似乎只在`pkg/expression/expression_to_stmt.go`的`convertScalatFunction`添加了
```
case ast.Cos:
		return &ast.FuncCallExpr{FnName: model.NewCIStr(expr.FuncName.L), Args: children}, nil
```
我仿照测试了Sin,但并不能成功。我是不是遗漏了什么某些必要的实现？
```
case ast.Sin:
		return &ast.FuncCallExpr{FnName: model.NewCIStr(expr.FuncName.L), Args: children}, nil
```

**Comment by Repo-Zhuang** [comment]
比如我想实现类似这样的查询语句。但可能我需要的不是Sum，而是某种我想自定义的函数`f(amount)`
```SELECT SUM(amount) AS total_amount FROM orders WHERE customer_name = 'John';```

**Comment by jingshi-ant** [comment]
SCQL现状是兼容的MYSQL的function/operator，暂不支持自定义的函数。
即使是通用的算子，比如SUM，如果要在SCQL中实现的话，需要实现：interpreter里的rewrite及node逻辑（expression_to_stmt.go, build_execution_node.go），engine对应的明文算子(reduce.cc)、密文算子(reduce.cc)

**Comment by Repo-Zhuang** [comment]
好的，谢谢

**Comment by jingshi-ant** [comment]
单方算子cos已经实现了。参考: https://github.com/secretflow/scql/blob/main/pkg/expression/expression_to_stmt.go#L142
 所谓的单方算子，可以认为是下层到runsql阶段，将计算任务托管给datasource/mysql的算子，大部分场景下只能查询自己的表。

**Comment by Repo-Zhuang** [comment]
好的，了解。十分感谢。
