### ISSUE TITLE
关于CCL设置为PLAINTEX安全性能的疑问

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#281]
1.如果联邦查询的两张表的所有字段分别对两个参与方CCL设置了PLANTEXT,是否就意味着基于这两张表构造的sql语句的计算过程和结果全都是明文进行运算的？
2.使用PLAINTEXT_AFTER_JOIN过程中，join这个运算过程是加密的是吧，然后join之后假如说要进行其他计算，相当于也是用的明文数据进行接下来的运算（默认下面的计算需要的字段CCL也是设置的PLAINTEXT）？
3.目前SCQL支持三方查询吗？

**Comment by jingshi-ant** [comment]
1.不一定，SCQL有些算子只有密文计算过程，比如JOIN都是PSI完成的；当然如果都是PLAINTEXT，其它group by等算子可能跑在明文下。
2.join是加密的，使用的是PSI。后续计算很可能是加密的，如果CCL可见的话。
3.支持。

**Comment by Handikang** [comment]
好的，感谢，我刚看到scql更新了可以使用kuscia进行部署，我看到关于数据源的配置的，可以使用kuscia的 Datamesh模块，作为数据源路由，咱们有关于这个模块更加详细的解释么，使用kuscia部署scql是否意味着scql可以并发执行任务，提高了scql的调度能力？
还有一个问题我想请教一下，就是关于scql数据源的配置有没有比较方便的方式，如果在gflag.conf更底层去修改的话，是不是要修改engine下关于数据源适配的c++部分？

**Comment by jingshi-ant** [comment]
1.DataMesh是Kuscia的概念，相关概念以及使用方式Kuscia官网上有相关资料，建议进一步了解~ 另外从资源隔离来讲，kuscia是有利于提高资源调度能力的，当然scql本身就支持并发任务。
2.数据源的配置因为考虑了灵活性，在配置上确实会繁琐一点（使用mysql数据源的成本会低一些），适配的代码在datasource目录下，有adaptor相关的代码。
