### ISSUE TITLE
关于按照P2P模式部署SCQL后，demo的最后一步没有跑通。

### ISSUE THREAD

**Issue by eyuxiansheng** [secretflow/scql#286]
alice端的配置：
**config.yml**
![image](https://github.com/secretflow/scql/assets/49189541/b4cdca96-eab1-4d1b-bdba-3406e2b4d613)

**docker-compose.yaml**
![image](https://github.com/secretflow/scql/assets/49189541/c8fd10e6-1d6c-4198-a959-86f0526f5b86)

**gflags.conf**
![image](https://github.com/secretflow/scql/assets/49189541/cfcc3f6d-e354-4fbf-92ad-29a3ce277519)

**party_info.json**
![image](https://github.com/secretflow/scql/assets/49189541/54f47053-c7fa-4d2b-9b65-e8597bb23300)

bob端的配置：
**config.yml**
![image](https://github.com/secretflow/scql/assets/49189541/ffa32f1a-223f-4423-b755-e2373dc09a33)

**docker-compose.yaml**
![image](https://github.com/secretflow/scql/assets/49189541/4394ee08-729f-4393-912c-ed4e82ab6260)

**gflags.conf**
![image](https://github.com/secretflow/scql/assets/49189541/8037ca95-4614-4f7c-b611-fdbe43de1046)

**party_info.json**
![image](https://github.com/secretflow/scql/assets/49189541/1803996f-375b-4387-b0af-0a3e79d5df61)

按照官方文档测试步骤https://www.secretflow.org.cn/zh-CN/docs/scql/0.7.0b1/intro/p2p-tutorial，前面都可以跑通：
alice
![image](https://github.com/secretflow/scql/assets/49189541/b8072233-60b0-4aca-bab4-8af9e9bae046)
bob
![image](https://github.com/secretflow/scql/assets/49189541/e03bc5b1-0501-4a27-a691-0790f73bf31f)
但是在alice执行“查询”的时候，报错：
![image](https://github.com/secretflow/scql/assets/49189541/3d7b8132-5897-4ebb-a04a-5a4e566b7425)

我的两台服务器系统都是centos7.
哪个大佬帮忙看下这个是哪里出问题了？是端口配置问题吗？

**Comment by jingshi-ant** [comment]
上个issue里回复了，改下broker的for_peer配置，去掉http:// 前缀后重启broker试试。（docker restart xxx-broker---）

**Comment by eyuxiansheng** [comment]
> 上个issue里回复了，改下broker的for_peer配置，去掉http:// 前缀后重启broker试试。（docker restart xxx-broker---）

真的是这样！太强了！感谢！

**Comment by eyuxiansheng** [comment]
> 上个issue里回复了，改下broker的for_peer配置，去掉http:// 前缀后重启broker试试。（docker restart xxx-broker---）

我在测试的时候创建了很多工程：
![962c008445e13ed2d2e42b01c6383f5](https://github.com/secretflow/scql/assets/49189541/83e45bc3-74ad-4314-b4b8-e8c1933bc398)

如何删除指定的工程呢？

**Comment by jingshi-ant** [comment]
暂不支持删除工程。（该操作危险性高）
