### ISSUE TITLE
一个参与方只能创建一个用户的限制问题

### ISSUE THREAD

**Issue by WandQ** [secretflow/scql#289]
我尝试在创建alice之后再创建一个alice1用户，提示如下：
CREATE USER `alice1` PARTY_CODE 'alice' IDENTIFIED BY 'some_password' WITH '2024-05-24T08:56:12.699100252Z' 'MTv+1AU6bFNmUNn1hWQ4CA41Lx5gAtro5zYR/sB/UlOl7Hy7Sv/P0HZp/EUH4ZJh0jPMlIEga9lvYbKV2j1HCQ==' 'MCowBQYDK2VwAyEAn1Wp4NQDaWB2imtlysT/wC2vgPZSLww8ipH77sgOP3Q='
[fetch]err: Code: 300, message:only one user is allowed to exist in a party, user alice is already exist in party alice

一个参与方只能存在一个user账户，这个设定是出于什么考虑呢？如果我取消这个限制是否会导致bug

**Comment by tongke6** [comment]
用户和参与方是一一对应的。

是为了防止伪造身份攻击。
