### ISSUE TITLE
关于SCQL如何动态读取gflag.conf的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#291]
我看到engine使用的gflag来读取命令行参数运行的，然后每次修改宿主机的gflag.conf都需要重启engine容器将配置文件重新加载到容器中，想请教一下有没有不需要重启engine服务的方式实现gflag.conf的动态更新和读取。

**Comment by jingshi-ant** [comment]
1.当前没有低成本实现动态更新engine conf的办法。
2.如果只是数据源的动态更新，可以通过提供自定义的router server来实现。

**Comment by Handikang** [comment]
好的，非常感谢，那么要是提供自定义的数据源路由，还有哪块是阻碍执行一个完整的查询任务的点呢？还有麻烦看一下288这个issue

https://github.com/secretflow/scql/issues/288

**Comment by jingshi-ant** [comment]
问题能否具体些呢？

**Comment by Handikang** [comment]
好的，就如你所说的第2条，如果要实现自定义的数据源路由，具体应该修改哪块代码呢，是整个datasource文件夹都要重写吗？
假如https://github.com/secretflow/scql/tree/main/engine/datasource下面的都重写，实现了数据源动态更新，是否还要修改其他代码才能实现SCQL联合查询的完整功能，换句话说相对应修改了数据源路由的逻辑，相对应受影响的哪块代码也需要修改？
我理解每次查询的时候，engine都是需要读取gflag配置文件通过数据库.数据表唯一确定数据源id,然后去连接数据库

> 1.当前没有低成本实现动态更新engine conf的办法。 2.如果只是数据源的动态更新，可以通过提供自定义的router server来实现。

**Comment by jingshi-ant** [comment]
思路：参考datasource目录下http_router.proto的接口，自己实现对应的server。 
每个任务都会向server请求数据库，只要server能支持动态更改，就能支持动态数据源了。

**Comment by Handikang** [comment]
好的，非常感谢
