### ISSUE TITLE
SCQL是否可以支持任意多个数据提供方吗？

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/scql#297]
您好，请问SCQL可以支持任意多个数据提供方吗？即底层mpc协议可以支持外包计算模式吗？此外，我在使用镜像时发现每个计算必须挂载一个表，是否是每个计算方不能只作为计算方存在，必须要输入数据？

**Comment by jingshi-ant** [comment]
SCQL可以支持多个参与方，每个参与方可以作为数据提供方，或者只是计算方。底层mpc的SEMI2K可以支持多个参与方，ABY3目前只支持3方场景。
demo中为了简洁，是典型的两方场景，多方场景也欢迎您根据实际业务场景验证~

**Comment by zzx-QDU** [comment]
我的意思是是否可以允许一些参与方只提供数据，不参与计算。

**Comment by zzx-QDU** [comment]
就是可不可以支持秘密共享的外包计算模式？

**Comment by jingshi-ant** [comment]
赞不支持，当前每个数据提供方都需要参与计算。

**Comment by zzx-QDU** [comment]
好的，感谢帮助。但是实际业务场景中往往是任意多个数据提供方，这就需要通过外包模式将计算方缩小到两到三个节点上，如果数据提供方必须参与计算，那么我感觉很影响实际使用。
