### ISSUE TITLE
CCL 问题

### ISSUE THREAD

**Issue by 472002463** [secretflow/scql#30]
CCL 的操作推导我有点不太理解。
是最终SELECT 的字段为PLAINTEXT 即可展示的意思吧。
![image](https://user-images.githubusercontent.com/33944862/232945392-97d36e31-f610-45f9-b00c-0831b7b90d72.png)

![image](https://user-images.githubusercontent.com/33944862/232955913-c9e434af-66bf-417c-8ea7-160c97059cae.png)
比如对于文档样例中，alice授予PLAINTEXT_AFTER_JOIN给bob，bob授予PLAINTEXT_AFTER_JOIN给alice
按照文档的推导。应该id为PLAINTEXT。那为啥会出现UNKNOWN。下面的异常信息我要怎么解读呢

![image](https://user-images.githubusercontent.com/33944862/232955794-939f7afb-f1d1-495b-8c08-9f5e225ead3e.png)

**Comment by tongke6** [comment]
这是因为 `ta.id` 没有对 alice 设置 CCL 导致的。因为 alice 是 ta 的 owner，可直接设置为 `PLAINTEXT`

**Comment by 472002463** [comment]
> 这是因为 `ta.id` 没有对 alice 设置 CCL 导致的。因为 alice 是 ta 的 owner，可直接设置为 `PLAINTEXT`
![image](https://user-images.githubusercontent.com/33944862/232957224-c4ba8689-704a-4f6d-9bab-166df02f9636.png)
现在将 ta.id 授予了alice PLAINTEXT,但是结果依旧没变。

![image](https://user-images.githubusercontent.com/33944862/232957764-766c5fb2-53b9-48cf-9547-da8420d6ee73.png)

**Comment by tongke6** [comment]
同理，`tb.id` 也要对 bob 设为 `PLAINTEXT`

**Comment by 472002463** [comment]
> 同理，`tb.id` 也要对 bob 设为 `PLAINTEXT`

我刚才试了下，确实可以了。但是我有点疑惑，`owner`对于自己的表都需要授权，这里的意义是在于哪里。
是打造同一个机构下的不同用户的权限限制的功能吗？，如同一个机构下的超管和各个分级的管理员的关系？
也就是说，如果要用到某个字段，那么必须`owner`必须要对这个字段进行`PLAINTEXT`授权是吗

**Comment by tongke6** [comment]
@472002463 好问题~

目前明确要求表 owner 对自己的表用到的字段设置为 `PLAINTEXT`。

当然，这个也可以从流程上化简一下，表的所有字段对表 owner 默认为 `PLAINTEXT`，后续会考虑变成默认行为。

**Comment by 472002463** [comment]
@tongke6 谢谢，非常感谢你的耐心回答。
