### ISSUE TITLE
关于 二元运算的密态计算

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#300]
### Issue Type

CCL

### Have you searched for existing issues?

Yes

### Question Details

```shell
在两方join的条件下，join的输入列ccl控制是要求(PLAINTEXT_AFTER_JOIN, PLAINTEXT)中的一种，这样以来经过谓词下推用户本地查出来明文列如果想和另外的参与方做二元运算，又不想让对方知道明文，该场景下该如何实现，比如 alice.money > bob.money，这种场景下希望两方的money是密态的，然后比较的结果可以明文披露，该如何处理。
```

**Comment by kaixin-haha** [comment]
也就是说： 
A方和B方join 的结果c 
 结果c和其他参与方D做二元运算
 要求：二元运算 数据是密文的，查询结果是明文的

**Comment by kaixin-haha** [comment]
请问您是数据提供方吗？

**Comment by tongke6** [comment]
@jiushun 把 money 字段对对方设置成 `PLAINTEXT_AFTER_COMPARE`

**Comment by jiushun** [comment]
> 也就是说： A方和B方join 的结果c 结果c和其他参与方D做二元运算 要求：二元运算 数据是密文的，查询结果是明文的

是有这种场景

**Comment by jiushun** [comment]
> @jiushun 把 money 字段对对方设置成 `PLAINTEXT_AFTER_COMPARE`

我尝试一下
