### ISSUE TITLE
scql 案例 执行最后一句的时候报错了,求指点，

### ISSUE THREAD

**Issue by byeyang** [secretflow/scql#301]
### Issue Type

Install/Build

### Have you searched for existing issues?

Yes

### OS Platform and Distribution

linux  kylin

### SCQL Version

0.7.0b1

### What happend and What you expected to happen.

```shell
broker用的是mysql ,engine用的是postgresql
(base) [root@localhost scql]# docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                       NAMES
3d4fb74e91f8   secretflow/scql:latest   "/home/admin/bin/bro…"   47 minutes ago   Up 47 minutes   0.0.0.0:8081->8080/tcp, :::8081->8080/tcp   p2p-tutorial-broker_alice-1
547d0d33b9a8   secretflow/scql:latest   "/home/admin/bin/scq…"   47 minutes ago   Up 47 minutes                                               p2p-tutorial-engine_bob-1
32d617a97803   secretflow/scql:latest   "/home/admin/bin/bro…"   47 minutes ago   Up 47 minutes   0.0.0.0:8082->8080/tcp, :::8082->8080/tcp   p2p-tutorial-broker_bob-1
575d3e477a9e   secretflow/scql:latest   "/home/admin/bin/scq…"   47 minutes ago   Up 47 minutes                                               p2p-tutorial-engine_alice-1
(base) [root@localhost scql]# ./brokerctl run "SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;"  --project-id "demo" --host http://localhost:8081 --timeout 3
Error: run query: DoQuery response: {
  "status": {
    "code": 320,
    "message": "; (peer: bob, code: 320, msg: RunExecutionPlan run jobs(5d719fd5-288d-11ef-a971-0242ac120004) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Connection Error: invalid connection option \"db\"\n)"
  }
}
Usage:
  brokerctl run <sql query> [flags]

Flags:
  -h, --help   help for run

Global Flags:
      --host string         host to access broker, e.g: http://localhost:8080
      --project-id string   unique identifier for project
      --timeout int         timeout seconds for http requests to broker (default 1)

(base) [root@localhost scql]#
```

### Configuration used to run SCQL.

```shell
alice.yaml

intra_server:
  protocol: http
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
  protocol: https
  cert_file: "/home/admin/tls/cert.crt"
  key_file: "/home/admin/tls/key.key"
log_level: debug
party_code: alice
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/private_key.pem"
intra_host: broker_alice:8080
engine:
  timeout: 120s
  protocol: https
  content_type: application/json
  uris:
    - for_peer: engine_alice:8003
      for_self: engine_alice:8003
storage:
  type: mysql
  conn_str: "root:daqq1024.@tcp(192.168.1.245:3306)/brokeralice?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
__________________________________________
bob.yaml

intra_server:
  protocol: http
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
  protocol: https
  cert_file: "/home/admin/tls/cert.crt"
  key_file: "/home/admin/tls/key.key"
log_level: debug
party_code: bob
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/private_key.pem"
intra_host: broker_bob:8080
engine:
  timeout: 120s
  protocol: https
  content_type: application/json
  uris:
    - for_peer: engine_bob:8003
      for_self: engine_bob:8003
storage:
  type: mysql
  conn_str: "root:daqq1024.@tcp(192.168.1.245:3306)/brokerbob?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m

__________________________________________________________________________________
alice.conf
--listen_port=8003
--datasource_router=embed
--enable_driver_authorization=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"postgres db","kind":"POSTGRESQL","connection_str":"dbname=alice;user=postgres;host=127.0.0.1;port=5432;password=postgres"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=false
--enable_peer_auth=false
# https flags
--server_enable_ssl=true
--server_ssl_certificate=/home/admin/engine/conf/cert.crt
--server_ssl_private_key=/home/admin/engine/conf/key.key
# set peer_engine_enable_ssl_as_client to true when peer SCQLEngine has https enabled
--peer_engine_enable_ssl_as_client=true
# set false when SCQLBroker IntraServer not enable https
--driver_enable_ssl_as_client=false
_________________________
bob.conf
--listen_port=8003
--datasource_router=embed
--enable_driver_authorization=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"postgres db","kind":"POSTGRESQL","connection_str":"dbname=bob;user=postgres;host=127.0.0.1;port=5432;password=postgres"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=false
--enable_peer_auth=false
# https flags
--server_enable_ssl=true
--server_ssl_certificate=/home/admin/engine/conf/cert.crt
--server_ssl_private_key=/home/admin/engine/conf/key.key
# set peer_engine_enable_ssl_as_client to true when peer SCQLEngine has https enabled
--peer_engine_enable_ssl_as_client=true
# set false when SCQLBroker IntraServer not enable https
--driver_enable_ssl_as_client=false
```

### SCQL log output.

```shell
Alice.log

2024-06-12 07:28:29.568 [warning] [listener.cc:GetListener:64] [sciengine] Listener for link_id:5d719fd5-288d-11ef-a971-0242ac120004 not exist.
2024-06-12 07:28:30.578 [info] [session_manager.cc:CreateSession:88] [sciengine] create session(5d719fd5-288d-11ef-a971-0242ac120004) succ, cost(1009ms), current running session=1
2024-06-12 07:28:30.578 [info] [engine_service_impl.cc:CheckGraphChecksum:162] [sciengine] check graph checksum
2024-06-12 07:28:30.580 [info] [engine_service_impl.cc:RunPlanCore:400] [sciengine] session(5d719fd5-288d-11ef-a971-0242ac120004) start to execute node(runsql.0), op(RunSQL)
2024-06-12 07:28:30.581 [error] [engine_service_impl.cc:RunPlanSync:475] [sciengine] RunExecutionPlan run jobs(5d719fd5-288d-11ef-a971-0242ac120004) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Connection Error: invalid connection option "db"

2024-06-12 07:28:30.585 [info] [session_manager.cc:RemoveSession:172] [sciengine] session(5d719fd5-288d-11ef-a971-0242ac120004) removed, running_cost(1017ms), current running session=0
2024-06-12 07:28:30.586 [warning] [channel.h:~Channel:163] [sciengine] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
2024-06-12 07:28:30.588 [info] [engine_service_impl.cc:StopJob:136] [sciengine] EngineServiceImpl::StopJob(5d719fd5-288d-11ef-a971-0242ac120004), reason()
2024-06-12 07:28:30.588 [warning] [session_manager.cc:StopSession:120] [sciengine] session(5d719fd5-288d-11ef-a971-0242ac120004) not exists.
____________________________________________________________________________
bob.log

2024-06-12 07:28:30.577 [info] [session_manager.cc:CreateSession:88] [sciengine] create session(5d719fd5-288d-11ef-a971-0242ac120004) succ, cost(1017ms), current running session=1
2024-06-12 07:28:30.577 [info] [engine_service_impl.cc:CheckGraphChecksum:162] [sciengine] check graph checksum
2024-06-12 07:28:30.581 [info] [engine_service_impl.cc:RunPlanCore:400] [sciengine] session(5d719fd5-288d-11ef-a971-0242ac120004) start to execute node(runsql.1), op(RunSQL)
2024-06-12 07:28:30.581 [error] [engine_service_impl.cc:RunPlanSync:475] [sciengine] RunExecutionPlan run jobs(5d719fd5-288d-11ef-a971-0242ac120004) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Connection Error: invalid connection option "db"

2024-06-12 07:28:30.585 [info] [session_manager.cc:RemoveSession:172] [sciengine] session(5d719fd5-288d-11ef-a971-0242ac120004) removed, running_cost(1026ms), current running session=0
2024-06-12 07:28:30.585 [warning] [channel.h:~Channel:163] [sciengine] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
2024-06-12 07:28:30.589 [info] [engine_service_impl.cc:StopJob:136] [sciengine] EngineServiceImpl::StopJob(5d719fd5-288d-11ef-a971-0242ac120004), reason()
2024-06-12 07:28:30.589 [warning] [session_manager.cc:StopSession:120] [sciengine] session(5d719fd5-288d-11ef-a971-0242ac120004) not exists.
```

**Comment by jingshi-ant** [comment]
您好，报错提示的是connection_str的格式问题，文档示例里应该有错误。。db --> dbname
[connection_str](https://www.secretflow.org.cn/zh-CN/docs/scql/0.7.0b1/reference/p2p-deploy-config#embed-router)

**Comment by byeyang** [comment]
> 您好，报错提示的是connection_str的格式问题，文档示例里应该有错误。。db --> dbname [connection_str](https://www.secretflow.org.cn/zh-CN/docs/scql/0.7.0b1/reference/p2p-deploy-config#embed-router)

您好，改了之后，出现这个错误了
(base) [root@localhost scql]# psql -h 192.168.1.245 -p 5432 -d bob -U postgres
Password for user postgres: 
psql (10.5)
Type "help" for help.

alice=# \q
(base) [root@localhost scql]# ./brokerctl run "SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;"  --project-id "demo" --host http://localhost:8081 --timeout 3
Error: run query: DoQuery response: {
  "status": {
    "code": 320,
    "message": "; (peer: bob, code: 320, msg: RunExecutionPlan run jobs(b85fd889-29fa-11ef-a08b-0242ac120005) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Connection Error: connection to server on socket \"/tmp/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n)"
  }
}
Usage:
  brokerctl run <sql query> [flags]

Flags:
  -h, --help   help for run

Global Flags:
      --host string         host to access broker, e.g: http://localhost:8080
      --project-id string   unique identifier for project
      --timeout int         timeout seconds for http requests to broker (default 1)

(base) [root@localhost scql]# docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                       NAMES
a33da900f9ab   secretflow/scql:latest   "/home/admin/bin/bro…"   39 minutes ago   Up 39 minutes   0.0.0.0:8082->8080/tcp, :::8082->8080/tcp   p2p-tutorial-broker_bob-1
6e427acd4f8d   secretflow/scql:latest   "/home/admin/bin/scq…"   39 minutes ago   Up 39 minutes                                               p2p-tutorial-engine_alice-1
ef7655258a11   secretflow/scql:latest   "/home/admin/bin/bro…"   39 minutes ago   Up 39 minutes   0.0.0.0:8081->8080/tcp, :::8081->8080/tcp   p2p-tutorial-broker_alice-1
2145f17248b6   secretflow/scql:latest   "/home/admin/bin/scq…"   39 minutes ago   Up 39 minutes                                               p2p-tutorial-engine_bob-1

**Comment by tongke6** [comment]
@byeyang 抱歉，文档中的示例有误，请按如下的格式改写：
![image](https://github.com/secretflow/scql/assets/124763920/56fc05e9-7edc-4ce2-9567-d7d3eaacb0f1)

举例来说，将alice 的 connection_str 由 `db=alice;user=postgres;host=192.168.1.245;port=5432;auto-reconnect=true` 
改成 `dbname=alice host=192.168.1.245 port=5432 user=postgres` 

BTW，postgres 设置了不需要密码吗？

**Comment by byeyang** [comment]
> @byeyang 抱歉，文档中的示例有误，请按如下的格式改写： ![image](https://private-user-images.githubusercontent.com/124763920/339653090-56fc05e9-7edc-4ce2-9567-d7d3eaacb0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTIzMjEsIm5iZiI6MTcxODM1MjAyMSwicGF0aCI6Ii8xMjQ3NjM5MjAvMzM5NjUzMDkwLTU2ZmMwNWU5LTdlZGMtNGNlMi05NTY3LWQ3ZDNlYWFjYjBmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwODAwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjJiZmM0MzQxMjE1NDI2ZWQzZGVjMTE5MGE2Njc0YzMwMjQ0ZWZiZWQzMzExYzAzNTQ5ZTgyYzRlYjcxN2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZKQ8d22YR-aO-brNX0LJXxwXIJIS_l3xMxzqw6RDRi4)
> 
> 举例来说，将alice 的 connection_str 由 `db=alice;user=postgres;host=192.168.1.245;port=5432;auto-reconnect=true` 改成 `dbname=alice host=192.168.1.245 port=5432 user=postgres`
> 
> BTW，postgres 设置了不需要密码吗？

已经设置密码了，如dbname=bob;user=postgres;host=127.0.0.1;port=5432;password=postgres，依旧报这个错：(base) [root@localhost scql]# ./brokerctl run "SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;" --project-id "demo" --host http://localhost:8081/ --timeout 3
Error: run query: DoQuery response: {
"status": {
"code": 320,
"message": "; (peer: bob, code: 320, msg: RunExecutionPlan run jobs(b85fd889-29fa-11ef-a08b-0242ac120005) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Connection Error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n)"

**Comment by byeyang** [comment]
这里该怎么指定tcp 连接 ，为什么会报socket 的错？--embed_router_conf={"datasources":[{"id":"ds001","name":"postgres db","kind":"POSTGRESQL","connection_str":"dbname=alice;user=postgres;host=127.0.0.1;port=5432;password=postgres"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}

**Comment by tongke6** [comment]
@byeyang 注意看，postgres 连接串字段的分隔符不是 `;` 而是空格 ` `

**Comment by byeyang** [comment]
> @byeyang 注意看，postgres 连接串字段的分隔符不是 `;` 而是空格 ` `

感谢~困扰了很久~~终于不是报那个错了，，新的错误已经出现，数据库alice ,bob 都有对应的表，但是这里报表不存在。。
(base) [root@localhost scql]# ./brokerctl run "SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;"  --project-id "demo" --host http://localhost:8081 --timeout 3
Error: run query: DoQuery response: {
  "status": {
    "code": 320,
    "message": "; (peer: bob, code: 320, msg: RunExecutionPlan run jobs(52754a74-2d41-11ef-92b8-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: PostgreSQL: [PostgreSQL]: postgresql_stmt_prepare error: ERROR:  relation \"bob.user_stats\" does not exist\nLINE 1: ...user_stats.is_active,user_stats.order_amount from bob.user_s...\n                                                             ^\n select user_stats.ID,user_stats.is_active,user_stats.order_amount from bob.user_stats where user_stats.is_active=1)"
  }
}
Usage:
  brokerctl run <sql query> [flags]

Flags:
  -h, --help   help for run

Global Flags:
      --host string         host to access broker, e.g: http://localhost:8080
      --project-id string   unique identifier for project
      --timeout int         timeout seconds for http requests to broker (default 1)

(base) [root@localhost scql]#

**Comment by tongke6** [comment]
postgres 的 full qualified table name 的形式是 `database.schema.table`。

回到上面的 case，`bob.user_stats` 中 bob 是 database name，`user_stats` 是 table name，估计这就是找不到表的原因。
可以在注册的时候把 ref table 改成实际的 `schema.table`，而不是 `database.table` 。


reference: https://www.postgresql.org/docs/9.1/ddl-schemas.html

**Comment by byeyang** [comment]
> postgres 的 full qualified table name 的形式是 `database.schema.table`。
> 
> 回到上面的 case，`bob.user_stats` 中 bob 是 database name，`user_stats` 是 table name，估计这就是找不到表的原因。 可以在注册的时候把 ref table 改成实际的 `schema.table`，而不是 `database.table` 。
> 
> reference: https://www.postgresql.org/docs/9.1/ddl-schemas.html

小白给大佬磕一个，谢谢~这次成功了啊啊~~。
提一嘴出现了和其他帖子一样的。
(base) [root@localhost scql]# ./brokerctl run "SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;"  --project-id "demo" --host http://localhost:8081 --timeout 100
Error: run query: DoQuery response: {
  "status": {
    "code": 320,
    "message": "; (peer: bob, code: 320, msg: RunExecutionPlan run jobs(9e1d3d55-2d54-11ef-92b8-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: PostgreSQL: [PostgreSQL]: postgresql_stmt_prepare error: ERROR:  operator does not exist: boolean = integer\nLINE 1: ...r_amount from public.user_stats where user_stats.is_active=1\n                                                                     ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n select user_stats.ID,user_stats.is_active,user_stats.order_amount from public.user_stats where user_stats.is_active=1)"
  }
}
Usage:
  brokerctl run <sql query> [flags]

Flags:
  -h, --help   help for run

Global Flags:
      --host string         host to access broker, e.g: http://localhost:8080
      --project-id string   unique identifier for project
      --timeout int         timeout seconds for http requests to broker (default 1)

(base) [root@localhost scql]# ./brokerctl run "SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 GROUP BY ta.credit_rank;"  --project-id "demo" --host http://localhost:8081 --timeout 100
run query succeeded
Warning : for safety, we filter the results for groups which contain less than 4 items.
[fetch]
2 rows in set: (0.607223515s)
+-------------+-----+-------------------+-------------------+
| credit_rank | cnt |    avg_income     |    avg_amount     |
+-------------+-----+-------------------+-------------------+
|           6 |   5 | 271227.7413368225 | 4463.935741424561 |
|           5 |   8 | 21069.87943649292 | 5888.066307067871 |
+-------------+-----+-------------------+-------------------+
(base) [root@localhost scql]#
