### ISSUE TITLE
关于数据源

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#303]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
麻烦问一下，scql底层支持的数据源除了mysql、csv、odbc，后面会有规划类似spark等的数据源吗
```

**Comment by kaixin-haha** [comment]
短期内没有。请问下您目前有什么场景，我们可以暂时记录下

**Comment by jiushun** [comment]
> 短期内没有。请问下您目前有什么场景，我们可以暂时记录下

我们也在寻找这类的场景，目前想了解下该项目有没有这方面的规划，因为之前看隐语视频介绍过用户的数据源类型多，要针对不同数据源进行对接

**Comment by kaixin-haha** [comment]
你好，暂时没有这部分能力的开源计划，如果后续有该部分的计划将会通知您，感谢您对隐语社区的关注
