### ISSUE TITLE
求平均数时整形溢出

### ISSUE THREAD

**Issue by Casieee** [secretflow/scql#31]
**Describe the bug**
在求平均数时，会出现整形溢出的问题

**To Reproduce**
在 examples/docker-compose/mysql/initdb 中的 alice_init.sql、bob_init.sql 中插入 10000 条数据。按照 quickstart 的步骤进行操作。

**Screenshots**
两次结果不同，且出现负数
![image](https://user-images.githubusercontent.com/73929403/232992488-0b0a2762-6f2c-4e5e-b102-9cbac9df664b.png)

**Expected behavior**
使用相同的数据在 mysql 中执行结果如下
![image](https://user-images.githubusercontent.com/73929403/232992179-c5cc64e8-73d6-4ebf-8f16-1b127d351b73.png)

**Environments (please complete the following information):**
 - OS: Ubuntu 20.04
 - SCQL Image: secretflow/scql:latest(IMAGE ID: 2c68c888711d)
 - Docker version 20.10.18

**Comment by tongke6** [comment]
@Casieee 请问是只修改了数据集以及规模吗？

修改的数据方便贴在下面吗，我们尝试复现一下

**Comment by tongke6** [comment]
@Casieee 可以尝试改一下 scdb 的配置，将 spu 的 field 改成 `FM128` 

https://github.com/secretflow/scql/blob/main/examples/docker-compose/scdb/conf/config.yml#L24

您的这个 case 在 FM64 下会溢出，详情见：https://www.secretflow.org.cn/docs/spu/en/reference/fxp.html

**Comment by Casieee** [comment]
谢谢！只修改了数据集和规模，按照您提供的方法，已经解决了。
