### ISSUE TITLE
关于使用http_router.proto如何自定义数据源服务的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#316]
1.想要实现动态配置数据源根据http_router.proto生成代码实现自定义服务，我理解是不是要参照mock_router_server.py实现自己的服务，然后在engine的配置文件gflags.conf中将http_router的endpoint写上，然后可以根据实际的服务来动态构建请求从而实现动态数据源路由，从而避免了使用embed的数据源路由每次更新数据源重启服务的痛苦?
2.这样的方式同样适用于csv文件类型或者其他文件类型的动态数据源配置么？

**Comment by jingshi-ant** [comment]
1. 是的。
2. 支持。

**Comment by Handikang** [comment]
好的，那如果我变动了SCQL的代码，最简便的测试方法是什么，是写测试文件么，还是打包docker镜像测试

**Comment by jingshi-ant** [comment]
ut测试能覆盖改动的地方效率会更高，建议优先ut测试，最终打包docker镜像进行验证。

**Comment by Handikang** [comment]
好的，感谢，我使用.proto文件生成了一段简单的c++服务端代码，最终make的时候显示错误，我看和Abseil有关，但是我重新下载编译之后也是一样的错误，报错如下：
![image](https://github.com/secretflow/scql/assets/42713276/a62cf1f7-1d5d-4157-9313-232170eacf29)
我猜报错是和Abseil的版本、protobuf版本、grpc版本有关么
我的grpc版本是v1.63.1,protobuf版本是v3.12.4,Abseil是master分支

**Comment by tongke6** [comment]
> 好的，感谢，我使用.proto文件生成了一段简单的c++服务端代码，最终make的时候显示错误，我看和Abseil有关，但是我重新下载编译之后也是一样的错误，报错如下： ![image](https://private-user-images.githubusercontent.com/42713276/346845804-a62cf1f7-1d5d-4157-9313-232170eacf29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDg4MTcsIm5iZiI6MTcyMDUwODUxNywicGF0aCI6Ii80MjcxMzI3Ni8zNDY4NDU4MDQtYTYyY2YxZjctMWQ1ZC00MTU3LTkzMTMtMjMyMTcwZWFjZjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA3MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMjBhYjY4ZmQxZjFhNjcyYjhhN2Q1Y2FmMzI3ZDkyZTc0YTUzNzBjYmI0ZWE1Y2I4ODdlOTYwOWIxYmNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2qv2_Rsrl8LJspoWzB3hEYrOyP_YGrMcl_GiPPxJMec) 我猜报错是和Abseil的版本、protobuf版本、grpc版本有关么 我的grpc版本是v1.63.1,protobuf版本是v3.12.4,Abseil是master分支

@Handikang 这个问题和此 repo 不相关，请自行解决～
