### ISSUE TITLE
在数据源中使能ENABLE_DATA_ODBC，编译报错，求助

### ISSUE THREAD

**Issue by jianjew** [secretflow/scql#333]
目前系统中是通过POCO框架支持mysql 和postgresql 数据源，现想支持更多的数据源，使用POCO框架中的ODBC支持更多的数据源，配置如下（本地是postgresql odbc测试）：
1、容器中安装apt install odbc-postgresql；配置好/etc/odbc.ini后，可以通过isql -v 连接到数据库；
2、poco.BUILD源码修改：
"ENABLE_DATA_ODBC": "OFF", 修改为 "ENABLE_DATA_ODBC": "ON",
out_static_libs 中新增一个"libPocoDataODBC.a",

编译时，报如下链接错误，请问这里怎么处理
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: undefined symbol: SQLGetConnectAttrA
>>> referenced by SessionImpl.cpp
>>>               SessionImpl.cpp.o:(Poco::Data::ODBC::SessionImpl::isConnected() const (.localalias)) in archive bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoDataODBC.a
>>> referenced by SessionImpl.cpp
>>>               SessionImpl.cpp.o:(Poco::Data::ODBC::SessionImpl::close()) in archive bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoDataODBC.a
>>> referenced by SessionImpl.cpp
>>>               SessionImpl.cpp.o:(Poco::Data::ODBC::SessionImpl::getConnectionTimeout() const) in archive bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoDataODBC.a
>>> referenced 5 more times

ld.lld: error: undefined symbol: SQLGetDiagRecA
>>> referenced by SessionImpl.cpp
>>>               SessionImpl.cpp.o:(Poco::Data::ODBC::Diagnostics<void*, (short)2>::diagnostics() (.isra.0)) in archive bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoDataODBC.a
>>> referenced by SessionImpl.cpp
>>>               SessionImpl.cpp.o:(Poco::Data::ODBC::SessionImpl::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoDataODBC.a
>>> referenced by ODBCStatementImpl.cpp
>>>               ODBCStatementImpl.cpp.o:(Poco::Data::ODBC::ODBCStatementImpl::clear()) in archive bazel-out/k8-fastbuild/bin/external/org_pocoproject_poco/poco/lib/libPocoDataODBC.a
>>> referenced 4 more times

**Comment by jianjew** [comment]
还是说odbc-postgresql不能通过apt进行安装，需要通过http_archive进行下载，并使用configure_make进行安装

**Comment by deanzxl** [comment]
请问这个问题怎么解决的？
