### ISSUE TITLE
关于SCQL如何远程debug的疑问

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#338]
1.SCQL的构建我看支持image-dev调试镜像的打包，这样是不是还是需要将调试镜像部署到p2p中，然后映射dlv的默认端口2345，然后配置vscode的launsh.json，通过调用broker的接口或者用brokerctl来触发远程debug?
2.有没有除了写单元测试，和上面我提到的远程debug的更为方便更为完备的远程debug方法？
3.如何远程debug引擎的代码（c++）?

**Comment by tongke6** [comment]
image-dev 只是给镜像里安装了一些 debug 工具；关于如何 debug golang 和 c++ program，可自行搜索哈

**Comment by Handikang** [comment]
好的，那部分我自己查查，那可以远程debug&nbsp; scql么，如何完成触发sql执行，看代码错误，只能部署到compose上，通过接口触发吗

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 晚上6:41
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/scql] 关于SCQL如何远程debug的疑问 (Issue #338)




 
image-dev 只是给镜像里安装了一些 debug 工具；关于如何 debug golang 和 c++ program，可自行搜索哈

**Comment by tongke6** [comment]
dlv 和 gdb 都可以 attach 正在运行的进程吧

**Comment by Handikang** [comment]
好的，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 晚上6:55
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/scql] 关于SCQL如何远程debug的疑问 (Issue #338)




 
dlv 和 gdb 都可以 attach 正在运行的进程吧
