### ISSUE TITLE
关于SCQL使用now语法报tensor类型和期待的数据类型不匹配的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#343]
![image](https://github.com/user-attachments/assets/e4ead3b5-ac7b-43ac-971c-60eb035f8710)

![image](https://github.com/user-attachments/assets/601cc636-c864-4190-a52e-7a2e0bdfb309)

![image](https://github.com/user-attachments/assets/d0b0eab7-7f4b-4bf2-aae8-77224483c78a)

我想问下这个是不是无法在join之后再用now()

**Comment by lanyy9527** [comment]
> type(=int64) doesnt match scheme type(=datatime)
您好，根据异常信息显示是遇到了类型不匹配的问题，请检查下表中的字段类型与查询中的字段类型是否匹配

**Comment by tongke6** [comment]
请提供下使用的 scql 版本号信息

**Comment by Handikang** [comment]
0.7.0b1



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 晚上6:46
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/scql] 关于SCQL使用now语法报tensor类型和期待的数据类型不匹配的问题 (Issue #343)




 
请提供下使用的 scql 版本号信息

**Comment by tongke6** [comment]
你好，已确认存在此问题，我们会在下下个版本进行支持。

**Comment by Handikang** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月3日(周二) 上午10:00
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/scql] 关于SCQL使用now语法报tensor类型和期待的数据类型不匹配的问题 (Issue #343)




 
你好，已确认存在此问题，我们会在下下个版本进行支持。

**Comment by tongke6** [comment]
Fixed in https://github.com/secretflow/scql/releases/tag/0.9.2b1
