### ISSUE TITLE
scql 支持的数据规模

### ISSUE THREAD

**Issue by friendsAI** [secretflow/scql#344]
### Issue Type

Perfomance

### Have you searched for existing issues?

Yes

### Question Details

```shell
如果是简单的两表联查，支持的最大数据规模是多大？
```

**Comment by lanyy9527** [comment]
您好，支持的最大数据规模更多是取决于您的系统配置和资源限制，咱这边具体的场景是什么呢？

**Comment by friendsAI** [comment]
16核（x86_64）, 内存 64
