### ISSUE TITLE
请问下  scql p2p的 broker要怎么根据源码编译呀。

### ISSUE THREAD

**Issue by a-b-c-3-2-1** [secretflow/scql#349]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
go新手，希望得到一些指导性的建议，感谢。
```

**Comment by wangzul** [comment]
编译环境参考
https://github.com/secretflow/devtools/blob/main/dockerfiles/scql-ci.DockerFile
https://github.com/secretflow/devtools/blob/main/dockerfiles/ubuntu-base-ci.DockerFile

go依赖拉不下来
go 代理go env -w GOPROXY=https://goproxy.cn,direct

编译命令参考
https://github.com/secretflow/scql/blob/main/CONTRIBUTING.md

编译通过后【产物存放路径】
bazel-bin/engine/exe/scqlengine 
bin/broker*

启动方式【配置文件参考官网P2P部署】
./scqlengine --flagfile=node.gflags.conf 
./broker -config=node.config.yml
