### ISSUE TITLE
关于SCQL的源码的执行流程

### ISSUE THREAD

**Issue by TY-cc** [secretflow/scql#35]
非常感谢隐语开源的SCQL，这里提一个很不好意思的想法。

我的本意是想结合SCQL介绍的步骤图来查看学习SCQL代码的执行逻辑，但是因为对go语言的不是很了解，源码中注释较少，对源码的学习比较吃力。所以非常不好意思的来问问有没有想过资料，介绍关于源码的执行逻辑的。感谢感谢

**Comment by taochen-ant** [comment]
你好，感谢你的提问，目前我们暂时没有更多关于源码的执行逻辑的说明。相关文档均已发布在https://www.secretflow.org.cn/docs/scql/en/。

**Comment by TY-cc** [comment]
好的，感谢回复
