### ISSUE TITLE
ssl相关

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#350]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04

### SCQL Version

SCQL 0.8.1b1

### What happend and What you expected to happen.

```shell
开启了 ssl 并启用 peer_engine_enable_ssl_as_client  peer_engine_enable_ssl_client_verification  配置peer_engine_ssl_client_ca_certificate 出现了一个brpc的警告，Use DEL+ADD instead of EPOLLONESHOT+MOD due to kernel bug. Performance will be much lower.
```

### Configuration used to run SCQL.

```shell
--listen_port=8003
--enable_separate_link_port=true
--link_port=8004
--enable_driver_authorization=false
# party authentication flags
--enable_self_auth=false
--enable_peer_auth=false
# https flags
--server_enable_ssl=true
--server_ssl_certificate=/xxx/examples/tls/engine_alice-ca.crt
--server_ssl_private_key=/xxx/examples/tls/engine_alice-ca.key
# set peer_engine_enable_ssl_as_client to true when peer SCQLEngine has https enabled
--peer_engine_enable_ssl_as_client=true
--peer_engine_enable_ssl_client_verification=true
--peer_engine_ssl_client_ca_certificate=/xxx/examples/tls/root-ca.crt
# set false when SCQLBroker IntraServer not enable https
--driver_enable_ssl_as_client=false
```

### SCQL log output.

```shell
external/com_github_brpc_brpc/src/bthread/fd.cpp:335] Use DEL+ADD instead of EPOLLONESHOT+MOD due to kernel bug. Performance will be much lower.
```

**Comment by BrainWH** [comment]
你好，可以把问题描述的详细一些，目前是遇到了卡点吗还是想了解具体的配置？

**Comment by jiushun** [comment]
> 你好，可以把问题描述的详细一些，目前是遇到了卡点吗还是想了解具体的配置？

您好，上面的配置文件是不是一个标准的ssl加密通信的配置，--peer_engine_enable_ssl_as_client=true这个选项开启之后，还要开启下面的验证操作，才能是一个完整的验证过程，但是在开启ssl相关东西时候，日志打印了一个 Use DEL+ADD instead of EPOLLONESHOT+MOD due to kernel bug. Performance will be much lower.，不知道性能会不会有影响

**Comment by tongke6** [comment]
忽略这个 warning 日志就好。
只要编译的时候没有定义宏 `BAIDU_KERNEL_FIXED_EPOLLONESHOT_BUG` 就会打这个日志，而且没有定义这个宏，用的就是 DEL+ADD，不用担心。
https://github.com/apache/brpc/blob/9643150b8f40c06979cb3ba8b9a170ee326d20bd/src/bthread/fd.cpp#L369
