### ISSUE TITLE
SQL查询语句报错

### ISSUE THREAD

**Issue by voidwings** [secretflow/scql#351]
系统 Linux 22.04 LTS， SCQL 版本 0.8.1b1，在P2P模式下运行以下查询时报错。
./brokerctl run "SELECT ta.ID, ta.income FROM ta WHERE ta.income > (SELECT AVG(ta.income) AS avg_income FROM ta INNER JOIN tb ON ta.ID = tb.ID);"  --project-id "demo" --host http://localhost:8081 --timeout 30

错误码：
![image](https://github.com/user-attachments/assets/df80ce80-83bc-4f39-9e0b-8895f6a7dfeb)

日志：

![271B3C95-DD9A-483A-C7C9-EA002195F52B](https://github.com/user-attachments/assets/e2d38188-f8c6-4bc1-bbd0-571309981d35)

经测试，在mysql下可执行此查询。似乎是rewrite的时候出问题了？

**Comment by voidwings** [comment]
> 您好，SCQL版本是 0.8.1b1 吗？

是0.8.1b1的，我打错了

**Comment by lanyy9527** [comment]
您好，经过我们测试后发现，目前确实是不支持该语法的，请问您这边的具体场景是怎样的呢？

**Comment by voidwings** [comment]
我看SCQL实现进度里写的SELECT语句完全支持 WHERE子句，所以实际上是不支持子查询语法的吗？

**Comment by lanyy9527** [comment]
两个语句分开执行是OK的，可能目前对嵌套语句的支持还不完善

**Comment by tongke6** [comment]
> 我看SCQL实现进度里写的SELECT语句完全支持 WHERE子句，所以实际上是不支持子查询语法的吗？

是的，子查询支持的不全。目前应该只支持 in 的 subquery
