### ISSUE TITLE
请问有scql中心化部署（alice和bob分别在不同的机器上）的说明吗？

### ISSUE THREAD

**Issue by lichengjie1112** [secretflow/scql#356]
![image](https://github.com/user-attachments/assets/6e5730db-87b3-455a-b511-eaf54cf7d824)
基于此文档：
https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/intro/tutorial
前面步骤均已完成
到创建数据库、用户和数据表这一步
参与方的alice和bob分别在不同的机器上
这种情况是不是不能完全照着文档中的命令执行了？
![image](https://github.com/user-attachments/assets/76a48baf-e2a3-4a2d-914b-fce7a448b761)

**Comment by BrainWH** [comment]
你好。单机和多机的原理是一致的，可以参考https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/topics/deployment/how-to-deploy-centralized-cluster

**Comment by lichengjie1112** [comment]
> 你好。单机和多机的原理是一致的，可以参考https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/topics/deployment/how-to-deploy-centralized-cluster

好的，现在遇到的问题是，创建完用户alice和bob，查询数据库的时候报authentication failed
![image](https://github.com/user-attachments/assets/730e5ab0-8191-48e8-a7b4-96c8629a360a)
创建用户的语句是用./scqltool genCreateUserStmt --user bob --passwd 123456 --party bob --pem examples/scdb-tutorial/engine/bob/conf/ed25519key.pem生成的，请问跟users.json有关系吗？
![image](https://github.com/user-attachments/assets/611cfb5d-c6f3-4cb9-9d9f-ba867a42d2c1)

**Comment by lanyy9527** [comment]
查看下配置 authorized_profile.json 内容是否匹配

**Comment by tongke6** [comment]
> > 你好。单机和多机的原理是一致的，可以参考https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/topics/deployment/how-to-deploy-centralized-cluster
> 
> 好的，现在遇到的问题是，创建完用户alice和bob，查询数据库的时候报authentication failed ![image](https://private-user-images.githubusercontent.com/153856826/366787643-730e5ab0-8191-48e8-a7b4-96c8629a360a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTQyMDIsIm5iZiI6MTcyNjIxMzkwMiwicGF0aCI6Ii8xNTM4NTY4MjYvMzY2Nzg3NjQzLTczMGU1YWIwLTgxOTEtNDhlOC1hN2I0LTk2Yzg2MjlhMzYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNzUxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGY4YjNmMzc5ZTBiMDBlYjFmZmY5NTA2MDQ2OGM0MDJlNTQzNzg1MjVkZjlhOWIxMjk2MTVlMmMxYmIzZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n15BFz2V2q-cMCYpCXTm5PfCuPLv77YJW49dL-fOtx0) 创建用户的语句是用./scqltool genCreateUserStmt --user bob --passwd 123456 --party bob --pem examples/scdb-tutorial/engine/bob/conf/ed25519key.pem生成的，请问跟users.json有关系吗？ ![image](https://private-user-images.githubusercontent.com/153856826/366788198-611cfb5d-c6f3-4cb9-9d9f-ba867a42d2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTQyMDIsIm5iZiI6MTcyNjIxMzkwMiwicGF0aCI6Ii8xNTM4NTY4MjYvMzY2Nzg4MTk4LTYxMWNmYjVkLWM2ZjMtNGNiOS05ZDlmLWJhODY3YTQyZDJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNzUxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGVjZTVjM2EwMmQ0ZDkwN2I5Y2JhZGE3NjNjMDQyOWM0NzMzMDY4YjBiZGEyNjE5NTZhODc1Yzc5ZTg1ZDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wnJ4bKkAy6Hm2Y7mxF118e9o669s61hbBWGmcrfVS5E)

scdbclient 指定的是这个 users.json 文件吗？
