### ISSUE TITLE
scql是否支持k8s部署

### ISSUE THREAD

**Issue by ShaneGu4Real** [secretflow/scql#357]
### Issue Type

Feature

### Have you searched for existing issues?

Yes

### Question Details

```shell
您好，请问scql和secretnote是否支持k8s部署，如果支持，应该怎么部署，谢谢
```

**Comment by BrainWH** [comment]
你好，目前scql和secretnote是不支持k8s部署的。scql可以尝试用kuscia部署，https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/topics/deployment/run-scql-on-kuscia

**Comment by ShaneGu4Real** [comment]
@BrainWH  您好，能否scql和secretnote分开在k8s内部署，后续有没有支持scql和secretnote部署在k8s里的计划？如果有大概什么时间，谢谢

**Comment by BrainWH** [comment]
你好，scql提供了docker image，本身就是支持部署到k8s的，如果想了解部署相关的，可以深入了解在kuscia中的部署，https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/topics/deployment/run-scql-on-kuscia

**Comment by ShaneGu4Real** [comment]
@BrainWH 在kuscia里可以用scql，secretnote通过简单的改造是否可以在k8s里部署 和部署在kuscia里的scql结合使用吗，如果可以应该怎么改，另外官方是否有计划支撑secretnote在k8s里部署，如果有大概什么时间，谢谢

**Comment by BrainWH** [comment]
你好，我想了解一下，咱们的场景是什么？

**Comment by tongke6** [comment]
应该是可以的，应用和 infra k8s 本身是解耦的。

把 scqlbroker 和 scqlengine 使用 k8s deployment 模式部署起来即可，请查看 k8s 相关的文档。

**Comment by ShaneGu4Real** [comment]
@tongke6 您好，问题1：secretnote可以在k8s里部署吗，如果可以，应该怎么改造。
问题2：后续官方有支持secretnote部署k8s的计划吗，如果有，大概什么时间。
麻烦解答下上述问题，谢谢

**Comment by tongke6** [comment]
@ShaneGu4Real 

1. 这是和 k8s 相关的问题，请自行探索尝试哈。2. 无。
