### ISSUE TITLE
scql 配置gflags.conf 报bug

### ISSUE THREAD

**Issue by friendsAI** [secretflow/scql#361]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### OS Platform and Distribution

linux v10

### SCQL Version

0.8.1b

### What happend and What you expected to happen.

```shell
在p2p模式下，希望 engine 之间的通信协议是http。根据官方资料，在gflag.conf 文件中增加 peer_engine_protocol 配置项，并设置值为 http 。重启docker后，再运行之前测试正常的查询语句，报错如下：
Error: run query: DoQuery response: {
  "status":  {
    "code":  320,
    "message":  "RunExecutionPlan create session(957ac98e-764c-11ef-a03b-0242ac1c0003) failed, catch std::exception=[engine/link/channel_manager.cc:57] BrpcChannel Init failed, ret=-1, remote_addr=192.168.90.168:8003, load_balancer=1, role=, protocol=http "
  }
}
```

### Configuration used to run SCQL.

```shell
--peer_engine_protocol=http
```

### SCQL log output.

```shell
engine 报错
```

**Comment by BrainWH** [comment]
你好，可以贴下gflag.conf 的配置信息

**Comment by friendsAI** [comment]
--listen_port=8003
--datasource_router=embed
--enable_driver_authorization=false
--server_enable_ssl=false
--driver_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources": [{"id": "ds001", "name": "mysql db", "kind": "MYSQL", "connection_str": "db=bob;user=root;password=*******;host=192.168.12.123;auto-reconnect=true"}], "rules": [{"db": "*", "table": "*", "datasource_id": "ds001"}]}
--enable_self_auth=false
--enable_peer_auth=false
--peer_engine_protocol=http

**Comment by jingshi-ant** [comment]
试试http:proto？http的配置我没有验证过
--peer_engine_protocol=http:proto

**Comment by friendsAI** [comment]
--peer_engine_protocol=http:proto，这个我也试过了，一样不行的。不过报错信息不一样：
Error: run query: DoQuery response: {
  "status":  {
    "code":  300,
    "message":  "runQuery distribute: Post \"http://192.168.12.123:5005/inter/query/distribute\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
  }
}

**Comment by jingshi-ant** [comment]
check下engine报错日志

**Comment by friendsAI** [comment]
请问，engine报错日志  在哪个文件呢？

**Comment by jingshi-ant** [comment]
找到engine对应的container id： docker ps
查看日志： docker logs xxx

**Comment by friendsAI** [comment]
2024-09-19 08:38:31.9198 ERROR executor.go:98 |RequestID:|SessionID:8b18efd9-7662-11ef-913e-0242ac1d0002|ActionName:EngineStub@RunExecutionPlan|CostTime:26.986135ms|Reason:InvalidResponse|ErrorMsg:Error: code=320, msg="RunExecutionPlan create session(8b18efd9-7662-11ef-913e-0242ac1d0002) failed, catch std::exception=[engine/link/channel_manager.cc:57] BrpcChannel Init failed, ret=-1, remote_addr=192.168.12.123:8003, load_balancer=1, role=, protocol=http "|Request:
2024-09-19 08:38:31.9198 ERROR query_handler.go:195 runsql err: Error: code=320, msg="RunExecutionPlan create session(8b18efd9-7662-11ef-913e-0242ac1d0002) failed, catch std::exception=[engine/link/channel_manager.cc:57] BrpcChannel Init failed, ret=-1, remote_addr=192.168.12.123:8003, load_balancer=1, role=, protocol=http "
[mysql] 2024/09/19 08:49:48 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2024/09/19 08:53:48 packets.go:123: closing bad idle connection: unexpected read from socket

**Comment by jingshi-ant** [comment]
[scqlengine] http does not support connection_type=single
需要改下配置--peer_engine_connection_type=pooled

**Comment by friendsAI** [comment]
好的，多谢。我先试试能否正常跑起来。
另外，修改了这些配置，engine 之间的通信协议就是http了吧？

**Comment by jingshi-ant** [comment]
建议验证试试看

**Comment by friendsAI** [comment]
可以了。但是timeout 得设长一点
