### ISSUE TITLE
关于SCQL新增order by算子整个流程的疑问

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#362]
1.这边想请教一下SCQL如果要适配order by算子在broker中sql解析应该从哪里开始添加关于order by的算子？
2.完了之后engine那边除了实现order by之后是不是也要对接好底层的tensor和parser?
3.官方在SQL解析侧有关于新增算子的详细流程？

还请老师们多加指点!

**Comment by lanyy9527** [comment]
暂时还没有「新增算子」的相关文档，目前我们正在做order by算子的支持工作；
