### ISSUE TITLE
如何构建SCQL镜像？

### ISSUE THREAD

**Issue by guanglaiguo** [secretflow/scql#363]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
请问一下，如何构建SCQL镜像？Kuscia构建镜像的流程在文档中有描述：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/development/build_kuscia_cn，提供了make build和make image命令，而SCQL镜像的构建好像无法直接make image，具体构建流程是什么呢？
```

**Comment by 1139763082** [comment]
官网暂时没有执行文档，可以参考下这个：https://github.com/secretflow/scql/tree/main/docker

**Comment by guanglaiguo** [comment]
> 官网暂时没有执行文档，可以参考下这个：https://github.com/secretflow/scql/tree/main/docker

感谢感谢~我尝试构建一下

**Comment by 1139763082** [comment]
> @1139763082 我从GitHub上下载了scql镜像版本scql-0.9.0b1，解压进入docker目录下执行**bash build.sh -t scql:0.9.0b1**命令后报错如下： [root@localhost scql-0.9.0b1]# cd docker/ [root@localhost docker]# ls build.sh README.md scql-anolis.Dockerfile scql-ubuntu.Dockerfile [root@localhost docker]# **bash build.sh -t scql:0.9.0b1** +++ dirname build.sh ++ cd . ++ pwd
> 
> * SCRIPT_DIR=/scql-0.9.0b1/docker
>   ++ cd /scql-0.9.0b1/docker/..
>   ++ pwd
> * WORK_DIR=/scql-0.9.0b1
> * echo 'build image scql:scql:0.9.0b1'
>   build image scql:scql:0.9.0b1
> * MOUNT_OPTIONS=
> * false
>   ++ arch
> * MACHINE_TYPE=x86_64
> * HOST_PLATFORM=
> * '[' x86_64 == x86_64 ']'
> * HOST_PLATFORM=linux/amd64
> * '[' -z '' ']'
> * TARGET_PLATFORM=linux/amd64
> * BUILDER=secretflow/scql-ci:latest
> * '[' ubuntu == anolis ']'
>   ++ docker run -it --rm --detach --mount type=bind,source=/scql-0.9.0b1,target=/home/admin/dev/ -w /home/admin/dev secretflow/scql-ci:latest tail -f /dev/null
>   Unable to find image 'secretflow/scql-ci:latest' locally
>   docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
> 
> 请问老师知道是哪里的问题么？？感谢感谢~~

网络问题，开代理试一下
