### ISSUE TITLE
SCQL Broker API调用的问题

### ISSUE THREAD

**Issue by lfwxyC** [secretflow/scql#367]
### Issue Type

Documentation

### Have you searched for existing issues?

Yes

### Question Details

```shell
请问SCQL Broker API支持gRPC调用吗
```

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by 1139763082** [comment]
暂时不支持，了解下您那边使用gRPC的原因是什么

**Comment by lfwxyC** [comment]
在代码里使用http调用api，返回的格式不是Json，需要额外的解析操作，感觉比较麻烦

**Comment by tongke6** [comment]
指定好请求的 content-type 为 `application/json`，response 就会使用 json 返回的

**Comment by lfwxyC** [comment]
![image](https://github.com/user-attachments/assets/850aa176-e27a-4bcb-b149-68e1c2c09e55)
这是我用postman请求项目列表，response是乱码

**Comment by tongke6** [comment]
镜像版本是最新的吗？

**Comment by tongke6** [comment]
duplicate with https://github.com/secretflow/scql/issues/368

**Comment by lfwxyC** [comment]
> 镜像版本是最新的吗？

用的0.6.0b1版本是乱码，升级到0.9.0b1后没问题了，感谢
