### ISSUE TITLE
P2P部署后如何加入新的参与方

### ISSUE THREAD

**Issue by lfwxyC** [secretflow/scql#369]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
P2P部署后，参与方信息保存在party_info.json文件中，如果想要新的参与方加入，需要修改party_info.json文件，再重启broker吗？有没有不重启broker的方式，实现参与方的动态更新？
```

**Comment by jingshi-ant** [comment]
如果使用文件配置参与方信息，需要修改party_info.json文件，再重启broker。
动态更新的话，可以参考配置项里的discovery.type配置项（consul，但需要额外的开发及维护）：https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/reference/p2p-deploy-config#configuration-options-of-scqlbroker

**Comment by lfwxyC** [comment]
好的，我研究一下consul，非常感谢

**Comment by tongke6** [comment]
Yes。是在 kuscia 里运行，要把 discovery.type 改成 kuscia
