### ISSUE TITLE
如何在单个容器中测试完整流程

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/scql#370]
您好，我们目前对代码做出一些小修改后，如果想测试下完整的执行流程，需要先打包镜像，然后用两个新容器进行测试。请问能不能直接在开发容器里测试一个安全SQL的完整流程？

**Comment by jingshi-ant** [comment]
1.测试代码逻辑的变更，建议优先考虑ut覆盖，对应的路径下_test.go/_test.cc可以快速验证。
2.暂时不能在开发容器里直接走完整SQL流程。

**Comment by zzx-QDU** [comment]
好的，感谢。
