### ISSUE TITLE
scql查询邀约id

### ISSUE THREAD

**Issue by moon-177** [secretflow/scql#375]
### Issue Type

CCL

### Have you searched for existing issues?

Yes

### Question Details

```shell
请问/intra/invitation/list接口，支持根据项目id查询对应的邀约信息嘛？或者是否提供其他接口可以查询邀约id？
```

**Comment by BrainWH** [comment]
你好，可以的，可以参照https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.0b1/reference/broker-api#IntraBrokerService_ListInvitations，给请求 body 设置成 "{}"，或者设置请求的 content-type 为 "application/json"

**Comment by tongke6** [comment]
> 请问/intra/invitation/list接口，支持根据项目id查询对应的邀约信息嘛？或者是否提供其他接口可以查询邀约id？
@moon-177 为什么有这个需求呀？看邀请信息才知道是来自哪个项目的邀请
