### ISSUE TITLE
scql运行的硬件基础是什么

### ISSUE THREAD

**Issue by kpretty** [secretflow/scql#38]
**Describe the bug**
在运行 example 的 docker-compose 时 scqlengine 始终起不来，最后进入容器手动执行 
```shell
./scqlengine --flagfile=/home/admin/engine/conf/gflags.conf 
```
报 Illegal instruction (core dumped)
<img width="671" alt="image" src="https://user-images.githubusercontent.com/77819741/233925021-bef18768-e993-4c4f-bc82-c8feab313dc1.png">

**Environments (please complete the following information):**
 - OS: linux
 - 内核：3.10.0-957.el7.x86_64
 - cpu信息
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/77819741/233925879-a13a1fa1-6e90-4355-806e-17ff0b8694bf.png">

**Comment by taochen-ant** [comment]
你好，能麻烦描述一下你是如何运行example的docker compose吗？

**Comment by kpretty** [comment]
@taochen-ant 正常执行的 docker-compose up -d

**Comment by kpretty** [comment]
进入容器执行的截图是因为 docker-compose up 后 scqlengine 的两个容器没有任何日志就异常退出了，所以我将 scqlengine 容器启动命令的 CMD 修改成 sleep 99999 后进入容器手动执行启动命令才看到 Illegal instruction (core dumped) 的异常

**Comment by kpretty** [comment]
@taochen-ant 谢谢

**Comment by kpretty** [comment]
确实是因为缺少avx指令集
