### ISSUE TITLE
关于shuffle和SortByKey协议

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/scql#383]
我在《SecretFlow-SCQL: A Secure Collaborative Query pLatform》这篇论文了解到scql实现了Shuffle和SortByKey protocol。我想问一下如果我想单独测试一下这两个协议，该如何进行呢，相关的函数代码在哪里呢

**Comment by tongke6** [comment]
这篇论文相关的实验在 vldb2024 branch 里，详见：
https://github.com/secretflow/scql/tree/vldb2024/vldb
