### ISSUE TITLE
在做SCQL官方测试例子时，报USER ALICE IS NOT THE OWNER OF XXX

### ISSUE THREAD

**Issue by shifengbj** [secretflow/scql#39]
如上，调用时报错如下，请问如何处理？ 

![截屏2023-04-25 下午2 51 50](https://user-images.githubusercontent.com/10797457/234197369-777cd7b9-23b2-4b6f-92aa-b845f4f10d4e.png)

**Comment by taochen-ant** [comment]
看起来是alice的token不能被grm识别导致的，麻烦能展示一下examples/docker-compose/scdb/conf/toy_grm.json 和examples/docker-compose/client/users.json 这两个文件的内容吗？

**Comment by shifengbj** [comment]
这个烦请关闭，是因为TOKEN访问的问题。
