### ISSUE TITLE
如何实现buildSQL？

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/scql#390]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
您好，我想在0.7版本build_execution_node.go中增加一个buildSort函数用以实现order by。但是我没有搞清楚如何设置输入和输出。之前我参与过Scape的开发和维护，Scape中是可以直接用固定接口获取每个节点的输入表和输出表，但是Scql中不同类型的节点获取输入的方法有点不同。

以下是我尝试写的代码

func (t *translator) buildSort(ln *SortNode) (err error) {
	sort, ok := ln.lp.(*core.LogicalSort)
	if !ok {
		return fmt.Errorf("buildSort: assert failed expected *core.LogicalSort, get %T", ln.LP())
	}
	child := ln.Children()[0]
	childColIdToTensor := t.getNodeResultTensor(child)

	sortKeys := []*Tensor{}
	for _, key := range sort.ByItems {
		sortkey, err := t.getTensorFromColumn(key, childColIdToTensor)
		if err != nil {
			return fmt.Errorf("buildSort: %v", err)
		}
		sortKeys = append(sortKeys, sortkey)
	}
	var sortPayload []*Tensor
	sortPayload = append(sortPayload, sortKeys...)
	sortPayload = append(sortPayload, child.ResultTable()...)
	out, err := t.ep.AddSortNode("sort", sortKeys, sortPayload)
	if err != nil {
		return fmt.Errorf("buildSort: %v", err)
	}
}

我有两个问题，一是我如何用sort.ByItems从childColIdToTensor获取sortkey，目前
sortkey, err := t.getTensorFromColumn(key, childColIdToTensor) 这一行代码是报错的；另一个问题是最后的输出应该如何进行处理？

感谢帮助！另外我刚开始接触go语言，也请见谅。
```

**Comment by fucangfy** [comment]
1. 可以换成t.getTensorFromExpression(key.Expr, childColIdToTensor)试试
2. 你的AddSortNode得到的output node，需要在childColIdToTensor里面关联上UniqueId，类似：
```
for i, col := range sort.Schema().Columns {
	childColIdToTensor[col.UniqueID] = out[i]
}
```
我们后续的版本会实现这一功能，到时候可以参考一下

**Comment by zzx-QDU** [comment]
这是我们修改后的代码：

func (t *translator) buildSort(ln *SortNode) (err error) {
	sort, ok := ln.lp.(*core.LogicalSort)
	if !ok {
		return fmt.Errorf("buildSort: assert failed expected *core.LogicalSort, get %T", ln.LP())
	}
	child := ln.Children()[0]
	childColIdToTensor := t.getNodeResultTensor(child)

	sortKeys := []*Tensor{}
	for _, key := range sort.ByItems {
		sortkey, err := t.getTensorFromExpression(key.Expr, childColIdToTensor)
		if err != nil {
			return fmt.Errorf("buildSort: %v", err)
		}
		sortKeys = append(sortKeys, sortkey)
	}
	var sortPayload []*Tensor
	sortPayload = append(sortPayload, sortKeys...)
	sortPayload = append(sortPayload, child.ResultTable()...)
	out, err := t.ep.AddSortNode("sort", sortKeys, sortPayload)
	if err != nil {
		return fmt.Errorf("buildSort: %v", err)
	}
	//sortedKeys := out[0:len(sortKeys)]
	sortedTensors := out[len(sortKeys):]
	sortedChildColIdToTensor := map[int64]*Tensor{}
	for i, tensor := range sortedTensors {
		sortedChildColIdToTensor[child.Schema().Columns[i].UniqueID] = tensor
	}
	err = setResultTable(ln, sortedChildColIdToTensor)
	if err != nil {
		return fmt.Errorf("buildSort: %v", err)
	}

	return nil
}

虽然能够成功运行，但是调用的mpc算子不对。我们测试用的语句是
select a.age from user_credit as a join user_stats as b on a.id=b.id order by a.age ASC
我们是对join的结果进行order by，应该调用secret sort，但调用的是plain sort，然后就报错了。报错信息如下：

2024-11-01 09:50:43.212 [error] [engine_service_impl.cc:RunPlanSync:570] [sciengine] RunExecutionPlan 执行任务(c1f0c3a9-9836-11ef-a931-22bec305ef85)失败, 捕获std::exception=[engine/operator/sort.cc:58] SortInPlain is unimplemented

为什么会调用plain的sort？

**Comment by zzx-QDU** [comment]
是CCL的问题，已解决。
