### ISSUE TITLE
使用scdb的异步查询一直是104状态，使用同步查询很快，表数据是示例数据，也就10几条数据

### ISSUE THREAD

**Issue by EtanWatson** [secretflow/scql#393]
### Issue Type

Perfomance

### Have you searched for existing issues?

Yes

### Question Details

```shell
使用/public/submit_query查询，状态一直处于104，但是使用/public/submit_and_get很快返回结果
{
  "biz_request_id": "1234",
  "query": "select * from demo.ta",
  "user": {
    "user": {
      "account_system_type": "NATIVE_USER",
      "native_user": {
        "name": "alice",
        "password": "some_password"
      }
    }
  }
}
```

**Comment by EtanWatson** [comment]
异步查询会让查询速度变得很慢吗？？

**Comment by EtanWatson** [comment]
![image](https://github.com/user-attachments/assets/046b7c2a-817c-4ef2-b68d-1afc1d257c20) 这个是一直没有结果返回

**Comment by jingshi-ant** [comment]
异步查询的性能预期和同步查询是一样的。只不过异步适合长任务，同步适合短任务场景
一直没返回的话，可以查看scdb、engine的日志，确认作业状态细节。

**Comment by tongke6** [comment]
估计是 scdb 的配置填写有问题，检查一下 scdb_host 的配置项。
下发给 engine 的 `RunExecutionPlanRequest` 里有一个 callback_url 字段，它是由 scdb_host 拼接而成，可以测试一下用它是否可以访问到 scdb。

**Comment by EtanWatson** [comment]
> 估计是 scdb 的配置填写有问题，检查一下 scdb_host 的配置项。 下发给 engine 的 `RunExecutionPlanRequest` 里有一个 callback_url 字段，它是由 scdb_host 拼接而成，可以测试一下用它是否可以访问到 scdb。
谢谢老师，应该是scdb_host:加了http导致的，他拼接的时候好像会多拼一个http，老师还想咨询一下，如果结果数据量很大的话，用http这种接口返回是不是会有问题，还有啥好的方式不

**Comment by EtanWatson** [comment]
> 谢谢老师，应该是scdb_host:加了http导致的，他拼接的时候好像会多拼一个http，老师还想咨询一下，如果结果数据量很大的话，用http这种接口返回是不是会有问题，还有啥好的方式不

谢谢老师，应该是scdb_host:加了http导致的，他拼接的时候好像会多拼一个http，老师还想咨询一下，如果结果数据量很大的话，用http这种接口返回是不是会有问题，还有啥好的方式不

**Comment by tongke6** [comment]
有多大的规模呀？

可以通过 select ... into outfile 将结果写到 csv 文件里

**Comment by tongke6** [comment]
@EtanWatson 是的。into 语法见：https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/reference/lang/manual

**Comment by EtanWatson** [comment]
> @EtanWatson 是的。into 语法见：https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/reference/lang/manual

好的，谢谢老师
