### ISSUE TITLE
make_share操作输出的是加性秘密分享形式的张量吗，为什么test文件里输出和输入相同？

### ISSUE THREAD

**Issue by rrsakura** [secretflow/scql#394]
### Issue Type

Feature

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://github.com/secretflow/scql/blob/main/engine/operator/make_share.cc

### Question Details

```shell
看代码描述make_share操作输出的应该是加性秘密分享形式的张量，为什么test文件里输出张量和输入张量相同？并且请问秘密分享后是如何做比较的呢？
```

**Comment by tongke6** [comment]
> 看代码描述make_share操作输出的应该是加性秘密分享形式的张量，为什么test文件里输出张量和输入张量相同？并且请问秘密分享后是如何做比较的呢？

make_share 的输出的确是加性秘密分享形式的张量，测试里并没有写输出，只给了一个 output_name。测试比较的时候，是再把输出 reveal 后和输入比较，测试 make_share 的行为，其实也依赖 reveal 是实现正确的。
