### ISSUE TITLE
关于SCQL的CCL一些问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/scql#396]
当前我用的是0.7.0b1版本的SCQL,最近想用下最新版本的CCL**[PLAINTEXT_AS_JOIN_PAYLOAD]**,然后我基于0.7.0b1版本合了关于新增PLAINTEXT_AS_JOIN_PAYLOAD所有需要修改的部分，但是最终测试的时候在engine那边engine_service_impl.cc报了校验和（checksum）不一致，所以我有如下两个问题
1.engine那边是否需要修改对应的代码以适配PLAINTEXT_AS_JOIN_PAYLOAD。
2.针对PLAINTEXT_AFTER_JOIN和PLAINTEXT_AS_JOIN_PAYLOAD的约束，是说join之后就是明文的，在engine里面也是走的明文，还是说到最终sql语句选取这个列作为结果可以呈现出来。想知道这里面的明文披露，指的是CCL层面，还是MPC的层面。

**Comment by tongke6** [comment]
1. 建议直接使用对应的版本。
2. 文档里有描述的：https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/topics/ccl/intro#types-of-ccl-constraints
