### ISSUE TITLE
数据授权

### ISSUE THREAD

**Issue by gurenwangyue** [secretflow/scql#397]
### Issue Type

CCL

### Have you searched for existing issues?

Yes

### Question Details

```shell
我在试用P2P模式部署两个节点（SCQL），分别为alice和bob方，alice/bob可以对另外一方数据授权，这种情况是不是有问题啊？如果有问题的话，那相关参数是哪些呢
```

**Comment by tongke6** [comment]
Sorry,  我没有理解你的问题，能否具体描述一下？

比如，alice/bob 可以对另外一方数据进行授权，是什么意思？目前只有数据 owner 可以对数据进行授权，不存在你说的问题。

**Comment by gurenwangyue** [comment]
我使用P2P模式创建了两个节点（各一台机器），其中alice是10.83.179.9，bob是10.83.179.12，在任意一个节点都可以执行以下全部操作，这样是没问题的吗：
==============Alice创建项目并邀请Bob加入=================

./brokerctl create project --project-id "demo" --host http://10.83.179.9:8180
./brokerctl get project --host http://10.83.179.9:8180
./brokerctl invite bob --project-id "demo" --host http://10.83.179.9:8180

./brokerctl get invitation --host http://10.83.179.12:8180
./brokerctl process invitation 1 --response "accept" --project-id "demo" --host http://10.83.179.12:8180
./brokerctl get project --host http://10.83.179.12:8180



#===================创建数据表====================

./brokerctl create table ta --project-id "demo" --columns "ID string, credit_rank int, income int, age int" --ref-table alice.user_credit --db-type mysql --host http://10.83.179.9:8180
./brokerctl get table ta --host http://10.83.179.9:8180 --project-id "demo"

./brokerctl create table tb --project-id "demo" --columns "ID string, order_amount double, is_active int" --ref-table bob.user_stats --db-type mysql --host http://10.83.179.12:8180
./brokerctl get table tb --host http://10.83.179.12:8180 --project-id "demo"

=========================授权CCL===========================

./brokerctl grant alice PLAINTEXT --project-id "demo" --table-name ta --column-name ID --host http://10.83.179.9:8180
./brokerctl grant alice PLAINTEXT --project-id "demo" --table-name ta --column-name credit_rank --host http://10.83.179.9:8180
./brokerctl grant alice PLAINTEXT --project-id "demo" --table-name ta --column-name income --host http://10.83.179.9:8180
./brokerctl grant alice PLAINTEXT --project-id "demo" --table-name ta --column-name age --host http://10.83.179.9:8180

./brokerctl grant bob PLAINTEXT_AFTER_JOIN --project-id "demo" --table-name ta --column-name ID --host http://10.83.179.9:8180
./brokerctl grant bob PLAINTEXT_AFTER_GROUP_BY --project-id "demo" --table-name ta --column-name credit_rank --host http://10.83.179.9:8180
./brokerctl grant bob PLAINTEXT_AFTER_AGGREGATE --project-id "demo" --table-name ta --column-name income --host http://10.83.179.9:8180
./brokerctl grant bob PLAINTEXT_AFTER_COMPARE --project-id "demo" --table-name ta --column-name age --host http://10.83.179.9:8180
./brokerctl grant bob PLAINTEXT --project-id "demo" --table-name tb --column-name ID --host http://10.83.179.12:8180
./brokerctl grant bob PLAINTEXT --project-id "demo" --table-name tb --column-name order_amount --host http://10.83.179.12:8180
./brokerctl grant bob PLAINTEXT --project-id "demo" --table-name tb --column-name is_active --host http://10.83.179.12:8180

./brokerctl grant alice PLAINTEXT_AFTER_JOIN --project-id "demo" --table-name tb --column-name ID --host http://10.83.179.12:8180
./brokerctl grant alice PLAINTEXT_AFTER_COMPARE --project-id "demo" --table-name tb --column-name is_active --host http://10.83.179.12:8180
./brokerctl grant alice PLAINTEXT_AFTER_AGGREGATE --project-id "demo" --table-name tb --column-name order_amount --host http://10.83.179.12:8180

**Comment by tongke6** [comment]
这是用一个上帝视角模拟两个机构。在实际的部署情况下，alice 是无法访问 bob 的 broker intra 端口的，也就是 broker intra 服务只能域内访问。

**Comment by gurenwangyue** [comment]
那在实际部署中通过哪个或者哪些参数来避免Alice/bob无法互相访问对方的broker  intra端口的呢

**Comment by gurenwangyue** [comment]
我把 conf.yml文件修改这host的配置（两边一致）：
![image](https://github.com/user-attachments/assets/603b4e0d-84b9-4258-ab9a-696f2cb18a59)
重启docker-compo
se后，报这个错，该如何解决啊
![image](https://github.com/user-attachments/assets/399f1be1-90e8-4b47-af56-4dee6ea172ba)

**Comment by tongke6** [comment]
容器里的 localhost 地址无法 published 到 host 上给外面访问？可以尝试 google 一下看看那 docker 端口 bind 的问题哈

**Comment by gurenwangyue** [comment]
好的 谢谢大佬
