### ISSUE TITLE
使用scdb调用接口，ccl和配置的权限不太一样

### ISSUE THREAD

**Issue by EtanWatson** [secretflow/scql#398]
老师好，我这边配置了两个角色，一个zongbu，一个prov，使用scdb给角色赋权后，总部查询权限如下，总部所属样例表赋权如下（使用样例表user_credit）
![image](https://github.com/user-attachments/assets/81005ad2-773c-4b8f-a16f-a681eb1492b6)
省分查询权限如下使用样例表user_stats
![image](https://github.com/user-attachments/assets/ab03ab6d-4fb6-4e12-9711-23c40a474eee)

双方各自表均不使用明文展示，总部使用一下示例sql查询报错
```
SELECT user_credit.credit_rank, COUNT(*) as cnt, AVG(user_credit.income) as avg_income, AVG(user_stats.order_amount) as avg_amount FROM scql_4973be830f874b3fb77b78240b8ef391.user_credit INNER JOIN scql_4973be830f874b3fb77b78240b8ef391.user_stats ON user_credit.ID = user_stats.ID WHERE user_credit.age >= 20 AND user_credit.age <= 30 AND user_stats.is_active=1 GROUP BY user_credit.credit_rank
```
![image](https://github.com/user-attachments/assets/222cf4bb-5f77-4cbc-b3e1-0ab40368af37)
但是我总部表的age就是配置的PLAINTEXT_AFTER_COMPARE，是需要配置明文才行吗

**Comment by zimu-yuxi** [comment]
参考这个[示例](https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/intro/tutorial#grant-ccl)看下

**Comment by EtanWatson** [comment]
> 参考这个[示例](https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/intro/tutorial#grant-ccl)看下

老师，这个示例我看了，如果有两个参与方，需要将自己的表可以做比较的字段配置成明文，给合作方该字段配置为PLAINTEXT_AFTER_COMPARE，这个字段合作方发起的时候，才能在compare中使用是吗

**Comment by EtanWatson** [comment]
> > 参考这个[示例](https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/intro/tutorial#grant-ccl)看下
> 
> 老师，这个示例我看了，如果有两个参与方，需要将自己的表可以做比较的字段配置成明文，给合作方该字段配置为PLAINTEXT_AFTER_COMPARE，这个字段合作方发起的时候，才能在compare中使用是吗

如果我双方都配置成PLAINTEXT_AFTER_COMPARE，好像做compare的时候就会显示权限够不

**Comment by zimu-yuxi** [comment]
> > > 参考这个[示例](https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/intro/tutorial#grant-ccl)看下
> > 
> > 
> > 老师，这个示例我看了，如果有两个参与方，需要将自己的表可以做比较的字段配置成明文，给合作方该字段配置为PLAINTEXT_AFTER_COMPARE，这个字段合作方发起的时候，才能在compare中使用是吗
> 
> 如果我双方都配置成PLAINTEXT_AFTER_COMPARE，好像做compare的时候就会显示权限够不

1.为什么要对本方数据给本方授权CCL呢？
2.可以看下这里的[介绍](https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/topics/ccl/intro#how-ccl-works)，了解下CCL是如何工作的
