### ISSUE TITLE
文件输出及结果写回数据源

### ISSUE THREAD

**Issue by jiushun** [secretflow/scql#399]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
在官网上看到有将结果insert table的特性，能否给一些测试的SQL，包括输出到文件和结果写回数据源
```

**Comment by jingshi-ant** [comment]
insert table 只能将数据写到DB里，不支持写到文件（写文件参考into outfile语法）。
支持的语法如下：
![image](https://github.com/user-attachments/assets/d197cf04-6184-4ee4-b8e2-fdc4ac0a6960)
另外在写入前，需要在engine gflags.conf中配置DB的连接串，并在DB中创建需要写入的table。
配置参考：https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/reference/p2p-deploy-config
![image](https://github.com/user-attachments/assets/4a0a2c7b-5daf-41e7-a8a8-05e137d4c628)

**Comment by jiushun** [comment]
> insert table 只能将数据写到DB里，不支持写到文件（写文件参考into outfile语法）。 支持的语法如下： ![image](https://private-user-images.githubusercontent.com/124752045/386449663-d197cf04-6184-4ee4-b8e2-fdc4ac0a6960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTkzNjgsIm5iZiI6MTczMTgxOTA2OCwicGF0aCI6Ii8xMjQ3NTIwNDUvMzg2NDQ5NjYzLWQxOTdjZjA0LTYxODQtNGVlNC1iOGUyLWZkYzRhYzBhNjk2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNDUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzczZjU4Yjg3YzM5MTk3NjFlMjIyMThmNmJiMTdlZjczNjhmZmNkM2Q0MjBjODU3ZGU3NGEwMTc4ZWVhZGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iqg9tfyOp9tWCVG3KukxVMNp16e4hA1yYHUrUjRef2g) 另外在写入前，需要在engine gflags.conf中配置DB的连接串，并在DB中创建需要写入的table。 配置参考：https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/reference/p2p-deploy-config ![image](https://private-user-images.githubusercontent.com/124752045/386449982-4a0a2c7b-5daf-41e7-a8a8-05e137d4c628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTkzNjgsIm5iZiI6MTczMTgxOTA2OCwicGF0aCI6Ii8xMjQ3NTIwNDUvMzg2NDQ5OTgyLTRhMGEyYzdiLTVkYWYtNDFlNy1hOGE4LTA1ZTEzN2Q0YzYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNDUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzJiNTU5MjcwNTI1M2I5ZmNlZWY2OTFlM2RlYjIxMTM1NjcwN2M4ZDI1MzU5NzBiM2YwOTEyMWFjYzBjOGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K16S-_0P8hJfKxk6eOLphICFV2jVk7fcSW938tU8V8Q)

好的，谢谢！
