### ISSUE TITLE
关于 scql 自定义 root 用户默认密码

### ISSUE THREAD

**Issue by kpretty** [secretflow/scql#41]
当前版本支持自定义 root 密码的功能吗？我在 docekr-compose.yml 中看到初始化 mysql 的脚本中写死了 root 密码
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/77819741/236146851-28421ff5-1105-4ddf-a5ba-1a4369889db1.png">
想请问一下这里使用的加密算法是什么，

**Comment by tyrone-yu** [comment]
进行了两次 sha256 加密后得到的
后续会增加密码修改的功能，以及初始密码随机生成的功能

**Comment by kpretty** [comment]
thx

**Comment by taochen-ant** [comment]
mysql 的脚本中写入 root 密码是为了方便quickstart展示，除此之外，用户可以选择下列方案更改root密码

1、配置环境变量：在启动SCDB时可以通过指定环境变量SCQL_ROOT_PASSWORD来指定密码，
2、随机生成密码：如果没有指定密码，SCDB在启动时会自动生成一个随机密码，并将其打印在控制台
对于方案一，你可以参考[getting_started/deployment.rst](https://github.com/secretflow/scql/blob/main/docs/getting_started/deployment.rst#24-create-docker-compose-file)中2.4中的docker compose配置。对于方案二，你只要不指定SCQL_ROOT_PASSWORD环境变量，SCDB启动后，就会在日志中打印相关信息
需要注意，如果采用这两种方案，在启动SCDB前，你需要将 mysql 的脚本中的root密码删除掉,避免重复创建root用户

我们在后续会支持修改密码的功能。
