### ISSUE TITLE
基于k8s容器部署，p2p模式下，邀请参与方返回404报错，如何进行问题定位？

### ISSUE THREAD

**Issue by Korano0521** [secretflow/scql#410]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/topics/deployment/how-to-deploy-p2p-cluster

### Question Details

```shell
scql版本0.9.1b1
基于p2p部署指引，将其中docker-compose部分修改为 k8s deployment+svc(loadbalance)方式对broker和engine进行部署；brokerctl为本地编译运行；
brokerctl控制alice/bob创建/查询project均成功，但后续邀请参与方时返回以下报错：
root@xxx: ./brokerctl invite bob --project_id "demo" --host http://10.189.177.9:8080
Error: InviteMember response:{
  "status": {
    "code": 300,
    "message": "InviteMember not success: error occur when inviting bob error status: 404 Not Found, body: 404 page not found"
  }
};

部署详细信息：
阿里云ACK服务框架+SLB负载均衡代理
broker:
config.yml中，uris两个参数,for_peer配置为alice broker的loadbalance外部ip:port,for_self为alice broker的svc服务名:port,其余为默认配置；
party_info.json中，endpont均根据对应broker的loadbalance设置为http://<loadbalance ip>:<loadbalance port>
```

**Comment by Korano0521** [comment]
broker服务日志正常，与文档一致；
engine服务日志持续返回如下Socket warning：
 [warning] [input_messenger.cpp:BRPC:381] [scqlengine] Fail to read from Socket{id=xxxxxxxxx fd=10 addr=10.189.177.x:xxxx:xxxx}{0x55c70c1d2d00}: Connection reset by peer

**Comment by Korano0521** [comment]
1 成员邀请阶段报错，目前broker的party_info.json中，url配置为：
"endpoint": "http://<loadbalance ip>:8080"
其中8080是deployment container暴露端口/svc代理端口
在alice侧容器内 执行命令curl http://<bob loadbalance ip>:8080/inter/project/invite 返回404 page not found, 网络是通畅的但是服务路径下无返回；
 在bob侧容器内 执行命令curl localhost:8080/inter/project/invite 也返回404 page not found
若配置为
"endpoint": "https://<loadbalance ip>:8080"
则直接返回
http: server gave HTTP response to HTTPS client

tls部分配置，遵循部署“快速指引”部分，使用的是brokerctl初始化生成的系列证书

2 engine无操作 为启动后的日志；其余日志部分未见报错，应该是正常的

**Comment by Korano0521** [comment]
> 辛苦确认下：1.现在成员邀请阶段还是报错吗？（邀请报404是因为alice broker没法连接上bob broker，需要再broker的party_info.json中配置两方broker的url + 证书） 2.engine的日志，是什么操作下打印的呢？此时已经创建项目成功，下发作业了吗？如果是跑作业过程中的warning，可能是网络抖动导致的，有其它报错日志吗


1 成员邀请阶段报错，目前broker的party_info.json中，url配置为：
"endpoint": "http://<loadbalance ip>:8080"
其中8080是deployment container暴露端口/svc代理端口
在alice侧容器内 执行命令curl http://<bob loadbalance ip>:8080/inter/project/invite 返回404 page not found, 网络是通畅的但是服务路径下无返回；
 在bob侧容器内 执行命令curl localhost:8080/inter/project/invite 也返回404 page not found
若配置为
"endpoint": "https://<loadbalance ip>:8080"
则直接返回
http: server gave HTTP response to HTTPS client

tls部分配置，遵循部署“快速指引”部分，使用的是brokerctl初始化生成的系列证书

2 engine无操作 为启动后的日志，未执行任何项目任务；其余日志部分未见报错，应该是正常的

**Comment by jingshi-ant** [comment]
broker应该有两个端口（container也需要expose两个端口），其中8080端口是内部端口，用于和用户交互，party_info.json中应该填inter端口，确定下端口号也是8080吗？

**Comment by Korano0521** [comment]
> broker应该有两个端口（container也需要expose两个端口），其中8080端口是内部端口，用于和用户交互，party_info.json中应该填inter端口，确定下端口号也是8080吗？

目前修改为 broker开放了8080(http)和8081(https), engine开放了8003(http)和8081(https)端口，404问题已消失；
通过config.yml设置http通信并关闭了所有的tls设置
目前项目创建和互相的数据授权 均成功了
非常感谢！

**Comment by Korano0521** [comment]
Issue closed
