### ISSUE TITLE
SCQL中的通信是否可以走nginx代理？

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/scql#431]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
您好，我们一个项目中可使用的端口非常有限，因此想通过使用nginx代理，目前我们已经确认grpc的通信行得通，但是engine使用的是brpc，我们想知道engine间的通信能否走nginx代理？

感谢帮助！
```

**Comment by zimu-yuxi** [comment]
可以，是有遇到什么问题吗？

**Comment by zzx-QDU** [comment]
就是我们想要让SCQL的通信都走nginx代理，通过加后缀让不同端口的通信分到同一个端口下面。我们想请教下，这种方法是否具备可行性？

**Comment by zimu-yuxi** [comment]
可以考虑通过kuscia来管理scql

**Comment by zzx-QDU** [comment]
通过kuscia可以让scql的通信只走一个端口吗
