### ISSUE TITLE
在scqlclient中使用alice使用sql语句查询bob的数据时，报错320

### ISSUE THREAD

**Issue by blue-moon-dreamer** [secretflow/scql#60]
我按照quickstart中的教程到最后一步query时，报错320
[fetch]err: Code: 320, message:RunExecutionPlan run jobs(03f7d286-044d-11ee-93fe-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Unknown database 'alice'
我尝试了登录alice用户时单独查询Alice的数据，没有问题，只要涉及到bob的数据就会报一样的错
**scdb日志**：
scdb-scdb-1   | 2023-06-06 17:31:52.665 INFO server.go:146 |GIN|status=200|method=POST|path=/public/submit_and_get|ip=172.18.0.1|latency=250.673032ms|
scdb-scdb-1   | 2023-06-06 17:32:12.665 DEBUG app.go:211 [Translator] plan in one string: DataScan(tb)->Aggr(avg(demo.tb.order_amount))->Projection([Column#4])
scdb-scdb-1   | 2023-06-06 17:32:12.665 DEBUG app.go:211 [Translator] plan in one string: DataScan(tb)->Aggr(avg(demo.tb.order_amount))->Projection([Column#4])
scdb-scdb-1   | 2023-06-06 17:32:12.665 DEBUG app.go:212 [Translator] logical plan: 
scdb-scdb-1   | digraph G {
scdb-scdb-1   | 1 [label="DataScan(tb)"]
scdb-scdb-1   | 2 [label="Agg([avg(demo.tb.order_amount)])"]
scdb-scdb-1   | 3 [label="Projection([Column#4])"]
scdb-scdb-1   | 2 -> 1
scdb-scdb-1   | 3 -> 2
scdb-scdb-1   | }
scdb-scdb-1   | 
scdb-scdb-1   | 2023-06-06 17:32:12.665 DEBUG app.go:212 [Translator] logical plan: 
scdb-scdb-1   | digraph G {
scdb-scdb-1   | 1 [label="DataScan(tb)"]
scdb-scdb-1   | 2 [label="Agg([avg(demo.tb.order_amount)])"]
scdb-scdb-1   | 3 [label="Projection([Column#4])"]
scdb-scdb-1   | 2 -> 1
scdb-scdb-1   | 3 -> 2
scdb-scdb-1   | }
scdb-scdb-1   | 
scdb-scdb-1   | 2023-06-06 17:32:12.665 DEBUG app.go:278 CCL: [party_code:"bob" visibility:PLAINTEXT database_name:"demo" table_name:"tb" column_name:"id" party_code:"bob" visibility:PLAINTEXT database_name:"demo" table_name:"tb" column_name:"is_active" party_code:"bob" visibility:PLAINTEXT database_name:"demo" table_name:"tb" column_name:"order_amount" party_code:"alice" visibility:PLAINTEXT_AFTER_JOIN database_name:"demo" table_name:"tb" column_name:"id" party_code:"alice" visibility:PLAINTEXT_AFTER_COMPARE database_name:"demo" table_name:"tb" column_name:"is_active" party_code:"alice" visibility:PLAINTEXT_AFTER_AGGREGATE database_name:"demo" table_name:"tb" column_name:"order_amount"]
scdb-scdb-1   | 2023-06-06 17:32:12.665 DEBUG app.go:278 CCL: [party_code:"bob" visibility:PLAINTEXT database_name:"demo" table_name:"tb" column_name:"id" party_code:"bob" visibility:PLAINTEXT database_name:"demo" table_name:"tb" column_name:"is_active" party_code:"bob" visibility:PLAINTEXT database_name:"demo" table_name:"tb" column_name:"order_amount" party_code:"alice" visibility:PLAINTEXT_AFTER_JOIN database_name:"demo" table_name:"tb" column_name:"id" party_code:"alice" visibility:PLAINTEXT_AFTER_COMPARE database_name:"demo" table_name:"tb" column_name:"is_active" party_code:"alice" visibility:PLAINTEXT_AFTER_AGGREGATE database_name:"demo" table_name:"tb" column_name:"order_amount"]
scdb-scdb-1   | 2023-06-06 17:32:12.665 INFO app.go:167 [Translator] execution plan: 
scdb-scdb-1   | digraph G {
scdb-scdb-1   | 0 [label="runsql:{in:[],out:[Out:{t_0,},],attr:[sql:select avg(user_stats.order_amount) as avg_amount from bob.user_stats,table_refs:[bob.user_stats],],url:[172.20.10.3:8080,]}"]
scdb-scdb-1   | 1 [label="publish:{in:[In:{t_0,},],out:[Out:{t_1,},],attr:[],url:[172.20.10.3:8080,]}"]
scdb-scdb-1   | 0 -> 1 [label = "t_0:{Column#4:PRIVATE:FLOAT}"]
scdb-scdb-1   | }
scdb-scdb-1   | 
scdb-scdb-1   | 2023-06-06 17:32:12.665 INFO app.go:167 [Translator] execution plan: 
scdb-scdb-1   | digraph G {
scdb-scdb-1   | 0 [label="runsql:{in:[],out:[Out:{t_0,},],attr:[sql:select avg(user_stats.order_amount) as avg_amount from bob.user_stats,table_refs:[bob.user_stats],],url:[172.20.10.3:8080,]}"]
scdb-scdb-1   | 1 [label="publish:{in:[In:{t_0,},],out:[Out:{t_1,},],attr:[],url:[172.20.10.3:8080,]}"]
scdb-scdb-1   | 0 -> 1 [label = "t_0:{Column#4:PRIVATE:FLOAT}"]
scdb-scdb-1   | }
scdb-scdb-1   | 
scdb-scdb-1   | 2023-06-06 17:32:12.665 INFO sync_executor.go:143 |RequestID:|SessionID:03f7d286-044d-11ee-93fe-0242ac120002|ActionName:Executor@RunExecutionPlan|CostTime:439.825109ms|Reason:|ErrorMsg:|Request:{"session_params":{"party_code":"bob","parties":[{"code":"bob","name":"bob","host":"172.20.10.3:8080"}],"session_id":"03f7d286-044d-11ee-93fe-0242ac120002","spu_runtime_cfg":{"protocol":"SEMI2K","field":"FM64","public_random_seed":"2177031441009175909","sigmoid_mode":"SIGMOID_REAL","ttp_beaver_config":{}}},"nodes":{"0":{"node_name":"runsql.0","op_type":"RunSQL","outputs":{"Out":{"tensors":[{"name":"Column#4.0","elem_type":"FLOAT","option":"REFERENCE","annotation":{"status":"TENSORSTATUS_PRIVATE"}}]}},"attributes":{"sql":{"t":{"name":".0","elem_type":"STRING","ss":{"ss":["select avg(user_stats.order_amount) as avg_amount from bob.user_stats"]}}},"table_refs":{"t":{"name":".0","shape":{"dim":[{"dim_value":"1"}]},"elem_type":"STRING","ss":{"ss":["bob.user_stats"]}}}}},"1":{"node_name":"publish.1","op_type":"Publish","inputs":{"In":{"tensors":[{"name":"Column#4.0","elem_type":"FLOAT","option":"REFERENCE","annotation":{"status":"TENSORSTATUS_PRIVATE"}}]}},"outputs":{"Out":{"tensors":[{"name":"avg_amount.1","elem_type":"FLOAT"}]}}}},"policy":{"worker_num":1,"subdags":[{"jobs":[{"node_ids":["0"]}]},{"jobs":[{"node_ids":["1"]}]}]}}|PartyCode:bob|Url:http://172.20.10.3:8080/SCQLEngineService/RunExecutionPlan
scdb-scdb-1   | 2023-06-06 17:32:12.665 ERROR sync_executor.go:89 |RequestID:|SessionID:03f7d286-044d-11ee-93fe-0242ac120002|ActionName:EngineStub@RunExecutionPlan|CostTime:475.871559ms|Reason:InvalidResponse|ErrorMsg:Error: code=320, msg="RunExecutionPlan run jobs(03f7d286-044d-11ee-93fe-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Unknown database 'alice' "|Request:
scdb-scdb-1   | 2023-06-06 17:32:12.665 ERROR submit_and_get_handler.go:65 |RequestID:|SessionID:03f7d286-044d-11ee-93fe-0242ac120002|ActionName:SCDBSubmitAndGetHandler@/public/submit_and_get|CostTime:855.661864ms|Reason:InvalidRequest|ErrorMsg:RunExecutionPlan run jobs(03f7d286-044d-11ee-93fe-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Unknown database 'alice' |Request:user:{user:{account_system_type:NATIVE_USER native_user:{name:"alice"}}} query:"select AVG(tb.order_amount) as avg_amount from tb" db_name:"demo"|ClientIP:172.18.0.1
scdb-scdb-1   | 2023-06-06 17:32:12.665 INFO server.go:146 |GIN|status=200|method=POST|path=/public/submit_and_get|ip=172.18.0.1|latency=855.853943ms|
scdb-scdb-1   | 2023-06-06 17:32:12.665 INFO sync_executor.go:143 |RequestID:|SessionID:03f7d286-044d-11ee-93fe-0242ac120002|ActionName:Executor@RunExecutionPlan|CostTime:439.825109ms|Reason:|ErrorMsg:|Request:{"session_params":{"party_code":"bob","parties":[{"code":"bob","name":"bob","host":"172.20.10.3:8080"}],"session_id":"03f7d286-044d-11ee-93fe-0242ac120002","spu_runtime_cfg":{"protocol":"SEMI2K","field":"FM64","public_random_seed":"2177031441009175909","sigmoid_mode":"SIGMOID_REAL","ttp_beaver_config":{}}},"nodes":{"0":{"node_name":"runsql.0","op_type":"RunSQL","outputs":{"Out":{"tensors":[{"name":"Column#4.0","elem_type":"FLOAT","option":"REFERENCE","annotation":{"status":"TENSORSTATUS_PRIVATE"}}]}},"attributes":{"sql":{"t":{"name":".0","elem_type":"STRING","ss":{"ss":["select avg(user_stats.order_amount) as avg_amount from bob.user_stats"]}}},"table_refs":{"t":{"name":".0","shape":{"dim":[{"dim_value":"1"}]},"elem_type":"STRING","ss":{"ss":["bob.user_stats"]}}}}},"1":{"node_name":"publish.1","op_type":"Publish","inputs":{"In":{"tensors":[{"name":"Column#4.0","elem_type":"FLOAT","option":"REFERENCE","annotation":{"status":"TENSORSTATUS_PRIVATE"}}]}},"outputs":{"Out":{"tensors":[{"name":"avg_amount.1","elem_type":"FLOAT"}]}}}},"policy":{"worker_num":1,"subdags":[{"jobs":[{"node_ids":["0"]}]},{"jobs":[{"node_ids":["1"]}]}]}}|PartyCode:bob|Url:http://172.20.10.3:8080/SCQLEngineService/RunExecutionPlan
scdb-scdb-1   | 2023-06-06 17:32:12.665 ERROR sync_executor.go:89 |RequestID:|SessionID:03f7d286-044d-11ee-93fe-0242ac120002|ActionName:EngineStub@RunExecutionPlan|CostTime:475.871559ms|Reason:InvalidResponse|ErrorMsg:Error: code=320, msg="RunExecutionPlan run jobs(03f7d286-044d-11ee-93fe-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Unknown database 'alice' "|Request:
scdb-scdb-1   | 2023-06-06 17:32:12.665 ERROR submit_and_get_handler.go:65 |RequestID:|SessionID:03f7d286-044d-11ee-93fe-0242ac120002|ActionName:SCDBSubmitAndGetHandler@/public/submit_and_get|CostTime:855.661864ms|Reason:InvalidRequest|ErrorMsg:RunExecutionPlan run jobs(03f7d286-044d-11ee-93fe-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Unknown database 'alice' |Request:user:{user:{account_system_type:NATIVE_USER native_user:{name:"alice"}}} query:"select AVG(tb.order_amount) as avg_amount from tb" db_name:"demo"|ClientIP:172.18.0.1
scdb-scdb-1   | 2023-06-06 17:32:12.665 INFO server.go:146 |GIN|status=200|method=POST|path=/public/submit_and_get|ip=172.18.0.1|latency=855.853943ms|

**bob日志：**
engine-engine-1  | 2023-06-06 17:32:12.528 [info] [session_manager.cc:CreateSession:75] create session(03f7d286-044d-11ee-93fe-0242ac120002) succ, cost(3ms), current running session=1
engine-engine-1  | 2023-06-06 17:32:12.534 [info] [engine_service_impl.cc:RunPlan:402] session(03f7d286-044d-11ee-93fe-0242ac120002) start to execute node(runsql.0), op(RunSQL)
engine-engine-1  | 2023-06-06 17:32:12.812 [error] [engine_service_impl.cc:RunExecutionPlan:251] RunExecutionPlan run jobs(03f7d286-044d-11ee-93fe-0242ac120002) failed, catch std::exception=[engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco::Data::DataException: Connection attempt failed: Unknown database 'alice'

**Comment by taochen-ant** [comment]
你好，请问一下你提交的query是什么？

**Comment by blue-moon-dreamer** [comment]
SELECT AVG(tb.order_amount) as avg_amount FROM tb

**Comment by blue-moon-dreamer** [comment]
找到问题了，bob的配置文件有个地方没有对应修改，谢谢！
