### ISSUE TITLE
将 SCQL《SCQL Manual》英文文档逐句翻译成中文文档

### ISSUE THREAD

**Issue by Candicepan** [secretflow/scql#66]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍
- 任务名称：将 SCQL《[SCQL Manual](https://www.secretflow.org.cn/docs/scql/latest/en-US/reference/scql_manual)》英文文档逐句翻译成中文文档
- 技术方向：SCQL/docs
- 任务难度：基础

## 详细要求

将 SCQL《[SCQL Manual](https://www.secretflow.org.cn/docs/scql/latest/en-US/reference/scql_manual)》英文文档按操作指引逐句翻译成中文文档，以完善中文文档内容

- 操作指引：[操作指引](https://www.yuque.com/secret-flow/admin/uwv3kw683w24czs8#ymZYq)中有 step by step 的操作介绍，可按照文档方式进行实现
- 文档范例：可在[这里](https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/reference/scql_security_statement)查看文档范例
- 提交要求：请在完成整篇文章翻译后，再提交 PR
- 翻译规范：为了让翻译后的文档更具有统一性，在翻译时可以参考[文档翻译规范](https://www.yuque.com/secret-flow/admin/uwv3kw683w24czs8#pV0sp)中的小 tips

## 能力要求
- 了解基本 git 操作
- 外语水平良好

**Comment by awusan125** [comment]
awusan125 Give it to me
