### ISSUE TITLE
通过submit_and_get执行多表查询sql，报表不存在，但是改成单表查询都没问题

### ISSUE THREAD

**Issue by cdt5050** [secretflow/scql#79]
通过submit_and_get执行多表查询sql，报表不存在，如下错误： （但是改成单表查询都没问题）
{"status": {"code": 320, "message": "RunExecutionPlan run jobs (1794b0a9-0b69-11ee-96f3-02623d5cb5a5) failed, catch std: :exception= [engine/datasource/odbc_adaptor.cc:56] catch unexpected Poco: : Data: : DataException: MySQL: [MySQL]: [Comment]: mysql_stmt_prepare errorit[mysql_stmt_error]: Table 'P_6675706548347473920.d_6676721710290440192' doesn't existt\ [mysql_stmt_errno]: 1146\t [mysql_stmt_sqlstate]: 42502\[statemnt]: select id from P_6675706548347473920. d_6676721710290440192 ", "details": [I}, "out_columns": [I, "scob_session_id": "1794b0a9-0b69-11ee-96f3-02623d5cb5a5",
"affected_rows": "0"}

**Comment by cdt5050** [comment]
下面是接口的input
{"user":{"user":{"account_system_type":"NATIVE_USER","native_user":{"name":"p_1000","password":"Some_password_2023"}},"grm_token":"j+g5OZWwIWvgoAZ4Z/uSjDW8+K/WM9jhKk/S86SGgKw="},"query":"SELECT auisxfs.d_6676721710290440192.id FROM d_6676720197706977280 inner JOIN d_6676721710290440192 on d_6676720197706977280.id = d_6676721710290440192.id","db_name":"auisxfs"}

**Comment by tongke6** [comment]
@cdt5050 toyGRM 的配置文件内容方便贴一下吗？

错误信息里，报的是表 `P_6675706548347473920.d_6676721710290440192` 不存在，这个表存在于机构侧的数据源里面吗？

**Comment by cdt5050** [comment]
我使用的是stdgrm，已经实现了三个接口，看接口的输入输出跟官网也是一致的。 一般这种错误是跟GRM有关吗？

**Comment by tongke6** [comment]
感觉是 GRM 里的映射关系有点问题

**Comment by tongke6** [comment]
@cdt5050 方便贴下在 scql 里的建表语句，以及单表查询可以的语句吗？我看下是哪张表关系没对上

**Comment by cdt5050** [comment]
-- p_6675706548347473920.d_6676721710290440192 definition
-- 从端的表
CREATE TABLE `d_6676721710290440192` (
  `id` varchar(255) DEFAULT NULL,
  `x1` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- p_6675706548347473920.d_6678154360100229120 definition

-- p_6675706548347473920.d_6676720197706977280 definition

-- 主端的表
CREATE TABLE `d_6676720197706977280` (
  `id` varchar(255) DEFAULT NULL,
  `x0` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

在主端select id from from d_6676720197706977280   数据库设置p_6675706548347473920(scql创建的库名与实际相同)
在从端select id from from d_6676721710290440192    数据库设置p_6675706548347473920(scql创建的库名与实际相同)
两边查自己的库都是没有问题的

**Comment by cdt5050** [comment]
这个问题已经解决，仔细研读了下开发文档，是顺序没有对应好。建议文档加上注意字样哈

**Comment by tongke6** [comment]
@cdt5050 是哪里的顺序没对应上导致的问题呀？我们也好看看文档上是否要再优化一下

**Comment by cdt5050** [comment]
比如输入顺序为[p_1000,p_2000]， 那么输出的顺序必须对应

**Comment by tongke6** [comment]
了解。
如你上面的高亮所示，文档是有这块说明的；我们后面会再强调一下，谢谢~
