### ISSUE TITLE
Failed to build scdb code when execute make command

### ISSUE THREAD

**Issue by sixiaoming** [secretflow/scql#8]
Building project in scql-ci:latest container guided by ["build"](https://github.com/secretflow/scql#build--unittest) successfully until exec "make" command:
`(base) [root@0e72ca6cc984 scql]# make
rm -f bin/*
rm -f *.coverprofile
Found `go`
go fmt ./pkg/...
go vet -unsafeptr=false ./pkg/...
github.com/secretflow/scql/pkg/scdb/server [github.com/secretflow/scql/pkg/scdb/server.test]
pkg/scdb/server/config.go:202:3: unknown field 'RevealSecretCondition' in struct literal of type spu.RuntimeConfig
pkg/scdb/server/config.go:203:3: unknown field 'RevealSecretIndices' in struct literal of type spu.RuntimeConfig
make: *** [Makefile:40: vet] Error 2`

[Makefile#40](https://github.com/secretflow/scql/blob/main/Makefile#L40)

**Comment by anakinxc** [comment]
@tyrone-yu Can you take a look?

Thanks

**Comment by tyrone-yu** [comment]
> 

Thank you for bringing this issue to our attention and letting us know. We have fixed the issue(https://github.com/secretflow/scql/pull/7) and will merge it into the repository later. Please try it later and let us know if there are still any issues.
