### ISSUE TITLE
跨域相关问题

### ISSUE THREAD

**Issue by DINOREXNB** [secretflow/scql#86]
将自定义的客户端的服务器地址修改为http://localhost:80
向部署在docker的scdb发送请求，想通过submit_and_get获取信息，但是浏览器控制台仍然报错：
```
Access to XMLHttpRequest at 'http://localhost:8080/public/submit_and_get' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
POST http://localhost:8080/ net::ERR_FAILED 403 (Forbidden)
```

<img width="471" alt="截屏2023-06-19 23 09 47" src="https://github.com/secretflow/scql/assets/130140331/a9055062-115b-4b74-b2d3-bf1ef6cb210a">

**Comment by tongke6** [comment]
@DINOREXNB sorry， 我没有太理解你的问题。我有如下问题需要你帮忙确认

1. 你是通过 scdbclient 向部署在 docker 里的 scdb发送请求，还是使用自己实现的 client 去发送的请求？
2. 部署在 docker 里的 scdb 的服务，可以通过 localhost 80 端口访问到吗？

**Comment by DINOREXNB** [comment]
1.通过自己实现的client去访问
2.可以
3.是的

**Comment by tongke6** [comment]
@DINOREXNB 你可以尝试修改一下代码，重新编译一下

将你上面截图位置的代码改一下，AllowOrigins 里面的 `:80` 端口去掉试下

**Comment by DINOREXNB** [comment]
我补充一下我的具体步骤：
我打算用自己编写的网页客户端发送post请求，调用/public/submit_and_get获取数据，但是因为端口号不同导致了跨域问题，我在看了scdb/server/server.go的源代码后发现允许的请求头只有http://localhost:80，所以我现在准备修改此行，我按照文档的delpoyment在docker部署了scdb，但是在docker里面，我并没有找到server.go文件,请问我该如何操作以完成修改

**Comment by tongke6** [comment]
@DINOREXNB 修改代码需要重新编译构建 docker 镜像。

`docker/build.sh` 脚本可能对你有帮助~
