### ISSUE TITLE
SCDB部署后如何加入新的参与方

### ISSUE THREAD

**Issue by blue-moon-dreamer** [secretflow/scql#93]
根据隐语提供的文档，和参与方有关的信息保存在grm的json文件中。当我部署完成SCDB后，现在有一个新的参与方需要加入，我该如何添加这个新的参与方的信息，是直接修改grm的json文件吗？需要重启SCDB服务吗？

**Comment by tongke6** [comment]
你的理解是对的，需要修改 toyGRM 的 json 文件，然后重启 SCDB 服务。

**Comment by blue-moon-dreamer** [comment]
隐语有考虑后期通过开放接口之类的方式来增加参与方吗？

**Comment by tongke6** [comment]
@blue-moon-dreamer 我们已经开放了相关接口，详见 GRM 相关文档：
1. https://www.secretflow.org.cn/docs/scql/latest/en-US/reference/grm 
2. https://www.secretflow.org.cn/docs/scql/latest/en-US/development/integrate_scql_system

上游集成方可以通过实现自己的 GRM 服务，实现动态的参与方管理、表schema信息注册等功能

**Comment by blue-moon-dreamer** [comment]
好的，感谢，我们研究一下
